### ISSUE TITLE
Feature Request: OpenGL support

### ISSUE THREAD

**Issue by Ruedii** [LGhassen/Scatterer#1]
Currently, as far as I know, only Direct3D 11 is supported.

Because of limitations, Direct3D 9 cannot be easily supported without massive performance penalties, and loss of quality.  I understand this.  

However, almost all of the extensions in Direct3D 11 are can be implemented in the common OpenGL extension set.

If you would like me to look into options I can.

**Comment by blackrack** [comment]
Actually, directx 9 works best right now, directx 11 and Opengl are included but I haven't really done much work on them.

Most of the shader code on the repository hasn't been updated in a while. I'll update them and then you can look at them if you wish.

**Comment by Corax** [comment]
DirectX is Windows only, whereas better OpenGL support would improve the experience for Mac and Linux users as well - might be worth considering.

**Comment by blackrack** [comment]
I know, I just don't plan on working on these right now since the shaders aren't anywhere near final and I'm changing stuff around all the time. Once I'm satisfied wih the shaders I'll add some decent openGL support.

**Comment by LGhassen** [comment]
OpenGL is pretty much completely fixed in the newest version.
