### ISSUE TITLE
A few Scatterer errors in debug mode

### ISSUE THREAD

**Issue by siimav** [LGhassen/Scatterer#108]
Found a few errors and exceptions related to Scatterer when loading KSP 1.10.1 in debug mode. This is from my full RSS/RO/RP-1 install.
[Scattererdebug.txt](https://github.com/LGhassen/Scatterer/files/5308672/Scattererdebug.txt)

**Comment by LGhassen** [comment]
Indeed I saw these on someone else's log, but since they only happen in debug mode I'm not sure I should even bother.

**Comment by siimav** [comment]
Not sure about the others but I think at least the `is not allowed to be called from a MonoBehaviour constructor` issues deserve fixing.

**Comment by LGhassen** [comment]
I think these are all fixed
