### ISSUE TITLE
Unable to change scatteringExposure for Kerbin

### ISSUE THREAD

**Issue by RJVB09** [LGhassen/Scatterer#109]
I use scatteringExposure to make atmospheres fit at lower lighting conditions. However in my planetpack i was trying to change the brightness of my homeworld's atmosphere, as it turns out only the "inner" parts on the actual planet got darker and not the actual atmosphere.

![screenshot582](https://user-images.githubusercontent.com/49564898/96274490-d4a30600-0fd0-11eb-94b0-7ff4d5734ea9.png)

Here's what it's supposed to look like, done with the ingame config tool (it changed back to the picture above when the game was restarted, even when i changed it in the config)
![screenshot586](https://user-images.githubusercontent.com/49564898/96274709-221f7300-0fd1-11eb-86b4-aa3b1e173cf9.png)

**Comment by LGhassen** [comment]
Have you tried sky exposure?

**Comment by RJVB09** [comment]
> 
> 
> Have you tried sky exposure?

yep, no result. works with the ingame tool but not with the config

**Comment by LGhassen** [comment]
Are you modifying the correct ModuleManager patch responsible for the config? Also, when using ModuleManager patches, using the UI to change settings may result in Junk being written to either the Laythe config or other configs.

**Comment by RJVB09** [comment]
Yep, I think so, since i'm aware of the Laythe config thing

**Comment by LGhassen** [comment]
@RJVB09 Do you still have this issue?

**Comment by RJVB09** [comment]
> 
> 
> @RJVB09 Do you still have this issue?

Yeah it's still there, i've also noticed i'm unable to change the IVA light color and that the IVA light source is always at the sun and never at any other object that is not the sun. (as if there can't be two of them ¯\_(ツ)_/¯)

**Comment by RJVB09** [comment]
No, it seems to be fixed 👍
