### ISSUE TITLE
Window Postion on Startup Should Be Persistent

### ISSUE THREAD

**Issue by JustaSimpleUser** [LGhassen/Scatterer#11]
The Scatterer features selection window that is displayed on startup consistently appears in the upper left hand corner of the KSP start screen.  When it conflicts with other mod windows it can be moved.  The position is not remembered, however.  I suggest that the window position be persistent between game sessions.

**Comment by LGhassen** [comment]
I've added this feature recently, you can find it in any of the KSP 1.1 builds.
The position is remembered independently for the main menu screen and for in-game.
