### ISSUE TITLE
Crash loading or creating a save

### ISSUE THREAD

**Issue by conao68** [LGhassen/Scatterer#110]
KSP: 1.10.1 Windows 64bit
Problem: Crash loading or creating a save

Mods installed: (see the full list in Dropbox)
- Scatterer 0.0632
- EnvironmentalVisualEnhancements 1.10.1-3
- EnvironmentalVisualEnhancements -Stock Planets Config 1.2.2-1

Reproduction steps:

The game loads without a problem but crashes when loading or creating a save. It shows a dialog box just before crashing. Removing Scatterer solved the issue.

Log:

The picture of the dialog box, the log file, and the full list of mods are available in the link below.

https://www.dropbox.com/sh/w9g6qob8t23rxg1/AAAXRP6qRc6li53RfZE7q8zSa?dl=0

**Comment by LGhassen** [comment]
Why are you attempting to run the game in Directx 12?

**Comment by conao68** [comment]
Honestly, I don't know. I guess it was suggested by some mod. I even had to Google it to find out how to disable it but now it works!

Thanks a lot for your very quick support!
