### ISSUE TITLE
Glitchy shadows at KSC

### ISSUE THREAD

**Issue by Phelidai** [LGhassen/Scatterer#112]
KSP: 1.8.1 Windows 64bit

Problem: Odd shadows at the KSC both in the KSC menu and in flight near it.

I've narrowed the issue down to scatterer alone, and I just can't seem to get it to go away. The shadows don't have anything to do with the sun's position, however they don't show up at night as expected. They are circular around the buildings. They also flicker and jump a lot when the camera is moved.
![screenshot79](https://user-images.githubusercontent.com/61567118/102819752-f5008f80-4388-11eb-85a2-bff88b87c0cd.png)

Log file: 
[output_log.txt](https://github.com/LGhassen/Scatterer/files/5726390/output_log.txt)

Note: I did realize I still had EVE enabled when I took the screenshot and log, but I previously booted up KSP with only scatterer as a visual mod and got the same result.

**Comment by LGhassen** [comment]
The log you sent me doesn't have scatterer in it. In any case, turn up your in-game quality settings or disable scatterer's terrain shadows/long-distance shadows and restarts the game.

**Comment by Phelidai** [comment]
Must've sent the wrong log, apologies. Will try the fix.

**Comment by eberkain** [comment]
looks like shadows cast by clouds from EVE to me.

**Comment by LGhassen** [comment]
Closing because of no further feedback.
