### ISSUE TITLE
Water looks very strange (1.11, 0.722)

### ISSUE THREAD

**Issue by georgedorn** [LGhassen/Scatterer#114]
KSP: 1.11, Linux 64 bit
Problem:  Water looks like a wall, like the texture isn't being mapped to the surface correctly?
Mods installed:
EVE (with default config), small number of utility mods (alarm clock, all'yall, mechjeb2).  Problem exists with or without EVE.

Log: https://gdorn.circuitlocution.com/nextcloud/index.php/s/gqRpbpqzrmmaYN3

![scatterer_0722_ocean](https://user-images.githubusercontent.com/239067/103107894-a0168080-45f7-11eb-994d-802053ca1efd.png)

I've also tried with and without `-force-glcore` and with antialiasing set to 4 and 8.  I'm using a completely fresh install of scatterer with the default config as well.

Furthermore, downgrading to scatterer 0.632 (along with the corresponding sunflare and config) makes the water look right again.

**Comment by eberkain** [comment]
I am using these and not having this issue, but I'm on windows so I suspect that is involved. 

KSP 1.11
scatter 0.722
EVE Redux 1.11.1.1 /w normal BoulderCo configs
Parallax 1.1.1 /w stock textures
Kopernicus 1.11 r58

If you go land in the water what does it look like?  Is this only in the space center view?

**Comment by LGhassen** [comment]
Indeed I am getting the same issue as @georgedorn if I force opengl (-force-opengl) on windows. If I stay on Directx11 on windows as I suspect @eberkain is doing as well everything works normally. Thanks for the report, it's reproduced so I'll see what I broke.

**Comment by georgedorn** [comment]
I guess maybe opengl is the default on linux, then?  I'll give `-force-d3d11` and `-force-wayland` a go to get some more data points.

**Comment by LGhassen** [comment]
@georgedorn it's a regression in the latest version. And btw there is no directx support on linux so you can't run it with any of these arguments. You might want to try dxvk or proton if you want to do that (been told they run better than opengl)

**Comment by LGhassen** [comment]
Fixed in 0.0723
