### ISSUE TITLE
NullReferenceException Spam "at scatterer.OceanNode.get_offsetVector3"

### ISSUE THREAD

**Issue by fluff-y** [LGhassen/Scatterer#115]
Occurs often during reentry, from a free-return trajectory or LEO.
After manually clicking on "Apply settings/Rebuild ocean" in Scatterer Menu (Alt-F10), the NullReference Spam stops, the visuals become normal and the frame rate recovers.

GameDetails: KSP-1.9.1, RSS/RSSVE, Scatterer 0.0723

**Comment by LGhassen** [comment]
Can you include logs?

**Comment by LGhassen** [comment]
This should be fixed in the latest version (0.0772), if it still happens you can reopen this.
