### ISSUE TITLE
Hard crash after recovering a vehicle to Space Center

### ISSUE THREAD

**Issue by nagleaidan** [LGhassen/Scatterer#116]
I recovered a plane after landing at the Desert Airfield and KSP crashed. Looking at the log, it loaded into the Space Center, started instantiating mods, and then crashed on `scatterer.ScattererCelestialBodiesManager:findCelestialBodies()`. Not really expecting a 'fix', as it was a one time thing on an install with more than just Scatterer, but figured it'd be worth giving you the logs in case other people report it.

KSP v1.11.0
Scatterer v0.0723

[Player.log](https://github.com/LGhassen/Scatterer/files/5863771/Player.log)
[KSP.log](https://github.com/LGhassen/Scatterer/files/5863774/KSP.log)

<details>
<summary>List of Mods</summary>

6 Crew Science Lab (SixCrewScienceLab 1.2)
6 Seat Mk3 Cockpit (SixSeatMk3cockpit 1.2)
AntennaSleep (AntennaSleep 1.1)
Astrogator (Astrogator v0.10.2)
AutoAGL (AutoAGL 1.2)
Basic DeltaV (BasicDeltaV 6.0)
Basic Orbit (BasicOrbit 9.0)
BetterBurnTime (BetterBurnTime 1.10)
BetterCrewAssignment (BetterCrewAssignment 1.4.1)
BetterTimeWarpContinued (BetterTimeWarpCont 2.3.12.6)
BreakingGround-DLC (BreakingGround-DLC (unmanaged))
Chatterer (Chatterer 0.9.99)
ClickThrough Blocker (ClickThroughBlocker 1:0.1.10.15)
CommNet Antennas Info (CommNetAntennasInfo 3.0.3)
CommNet Relays (ContractConfigurator-CommNetRelays v2.1.0)
Community Tech Tree (CommunityTechTree 1:3.4.3)
Contract Configurator (ContractConfigurator 1.30.5)
Contract Pack: Bases and Stations Reborn (ContractConfigurator-KerbinSpaceStation 2:3.7.2.3)
Contract Pack: Clever Sats (ContractConfigurator-CleverSats 1.4)
Contract Pack: Exploration Plus (ContractConfigurator-ExplorationPlus 2.0.1)
Contract Pack: Field Research (ContractConfigurator-FieldResearch 1.2.2)
Contract Pack: Giving Aircraft a Purpose (GAP) (GAP 1.6.1)
Contract Pack: Kerbal Academy (ContractConfigurator-KerbalAcademy 1.1.10)
Contract Pack: Tourism Plus (ContractConfigurator-Tourism 1.5.2)
Craft Manager (CraftManager 1.2.0)
Crew Light (CrewLight 1:1.20.0)
Crowd Sourced Science (CrowdSourcedScience v6.0)
Custom Barn Kit (CustomBarnKit 1.1.21.0)
Dated QuickSaves (DatedQuickSaves 1.2.4.4)
Distant Object Enhancement Continued (DistantObject v2.0.2.0)
Distant Object Enhancement Continued default config (DistantObject-default v2.0.2.0)
Double Tap Brakes (DoubleTapBrakes 2.0.0.1)
Earn Your Stripes! (EarnYourStripes 4.0.2)
Easy Vessel Switch (EVS) (EasyVesselSwitch 2.2)
Environmental Visual Enhancements (EnvironmentalVisualEnhancements 3:1.10.1-3)
Extended information about scientific experiments in VAB (ScienceSituationInfo 1:1.3.4)
Flight Tracker (FlightTracker 3.0.0.1)
Hide Empty Tech Tree Nodes (HideEmptyTechNodes 1.2.0)
IndicatorLights (IndicatorLights 1.7)
Kerbal Alarm Clock (KerbalAlarmClock v3.13.0.0)
Kerbal Changelog (KerbalChangelog v1.3.0)
Kerbal Health (KerbalHealth v1.5.1)
Kerbal Wind Tunnel (WindTunnel 1.3.0)
KRASH - Kerbal Ramification Artifical Simulation Hub (simulation mod for KSP) (KRASH 0.5.33.3)
KXAPI (KXAPI 1.2.0)
MagiCore (MagiCore 1.3.2.3)
Making History (MakingHistory-DLC 1.11.0)
Mandatory RCS (MandatoryRCS 1:1.8)
Maneuver Node Evolved (ManeuverNodeEvolved 5.0)
Module Manager (ModuleManager 4.1.4)
Navball Docking Alignment Indicator CE-2 (NavballDockAlignIndCE 1.1.1)
PlanetShine (PlanetShine 0.2.6.3)
PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.3)
Pood's Milky Way Skybox (PoodsMilkyWaySkybox v.1.3.0)
Portrait Stats (PortraitStats 18.0)
Precise Editor (PreciseEditor v1.4.1)
Project Manager (ProjectManager v2.4)
QuickBrake (QuickBrake 1:1.4.0.7)
RCS Build Aid (RCSBuildAid v1.0.5)
ReStock (ReStock 1.3.0)
ReStock+ (ReStockPlus 1.3.0)
S.A.V.E (SAVE 1.10.2-3192)
scatterer (Scatterer 3:v0.0723)
Scatterer Default Config (Scatterer-config 3:v0.0723)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0723)
Science Relay (ScienceRelay 6.0)
ScienceAlert ReAlerted (ScienceAlert 1.9.8.9)
Sensible Screenshot (SensibleScreenshot 1.2.5.3)
Signal Delay (SignalDelay v0.2.13)
Space Age (SpaceAge v1.3.1)
Spectra (Spectra v1.4.0)
StockNoContracts (StockNoContracts v1.03)
TextureReplacer (TextureReplacer v4.3.1)
Timekeeper (Timekeeper v1.0.2)
Toolbar Controller (ToolbarController 1:0.1.9.4)
Tracking Station Evolved (TrackingStationEvolved 6.0)
Trajectories (Trajectories v2.3.4)
UnKerballed Start (UnKerballedStart 1.2.0)
Waypoint Manager (WaypointManager 2.8.2.6)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.1)

</details>

**Comment by TheRealWiwaxia** [comment]
I can confirm this bug as well, using scatterer in Real Solar System/Realism Overhaul. However, the bug occurs pretty frequently, usually after a couple of recoveries or even on a non recovery related scene change.

**Comment by Tonas1997** [comment]
Confirmed as well for version 0.0770, as that's the recommended release for RSSVE. Same stack trace and everything.

**Comment by LGhassen** [comment]
I've already fixed this but not made a release yet, should be fixed for next version.

**Comment by Tuupertunut** [comment]
Is this fix committed on some branch? I'd like to be an early adopter. :stuck_out_tongue:

**Comment by LGhassen** [comment]
You can try the public test version and confirm if it fixes it: https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip19-112-scatterer-atmospheric-scattering-00772-18062021/&do=findComment&comment=4022983
