### ISSUE TITLE
atmosphere blend mode adds together wrong, objects seen through atmospheres tend to become overexposed.

### ISSUE THREAD

**Issue by GregroxMun** [LGhassen/Scatterer#118]
Scatterer atmospheres tend to brighten background objects behind them, such as stars on the skybox, and when a scatterer atmosphere is seen from inside or behind another scatterer atmosphere, the result is that the atmosphere in the sky is overexposed.

This has been addressed somewhat by extinction but it seems to not be completely fixed, there still appears to be some unrealistic behavior.

Some examples of the incorrect behavior:

![image](https://user-images.githubusercontent.com/9667986/108026828-1d0e1700-6ff7-11eb-944d-02065be5446b.png)

_Stolen from Bill & Jeb's Most Excellent Adventure by Cupcake Landers, here we can see Alternis Jool (which is exposed correctly when seen alone in space) with EVE clouds and a scatterer atmosphere, has become overexposed, too bright, when seen in Alternis Kerbin's sky._

![image](https://user-images.githubusercontent.com/9667986/108027116-a291c700-6ff7-11eb-93c5-29b1adb90b1e.png)

_Lito in Whirligig World, atmosphere at the limb is too bright, adding onto the skybox instead of absorbing light from it_

![image](https://user-images.githubusercontent.com/9667986/108027196-c523e000-6ff7-11eb-9d31-49ffa129a9df.png)

_Lito's atmosphere rim gets much brighter when in front of Reander instead of the skybox_

Here are some photos of the correct behavior in real life:

![image](https://user-images.githubusercontent.com/9667986/108024818-4c228980-6ff3-11eb-9285-5439382bf217.png)

![image](https://user-images.githubusercontent.com/9667986/108025228-1cc04c80-6ff4-11eb-98e1-f1518593969c.png)

_Refraction occurs in real atmospheres, but this post isn't about refraction--just demonstrating that the Moon does get reddened, but it has to get really squashed before that can happen_

![image](https://user-images.githubusercontent.com/9667986/108024915-7f651880-6ff3-11eb-81d5-7557969c43d6.png)

_Titan has some regular blue rayleigh scattering going on in addition to the orange haze, but when seen against the very bright Saturn:_

![image](https://user-images.githubusercontent.com/9667986/108024985-a4598b80-6ff3-11eb-9eef-d13994fa274f.png)

_We see only orange._

SpaceEngine seems to get it right: Here's two atmospheres visually intersecting as seen from a third:

![image](https://user-images.githubusercontent.com/9667986/108026412-5003db00-6ff6-11eb-8752-aed0c89ab91b.png)

And here are some pictures of a correct implementation in a work-in-progress version of the game Personal Space. Posts about scattering: [Scatterbrained.](https://forums.tigsource.com/index.php?topic=66163.msg1409054#msg1409054) [Scatterbrained II.](https://forums.tigsource.com/index.php?topic=68612.msg1415699#msg1415699)

![image](https://user-images.githubusercontent.com/9667986/108025163-fbf7f700-6ff3-11eb-8905-c02ca85a5f74.png)

![image](https://user-images.githubusercontent.com/9667986/108025167-ff8b7e00-6ff3-11eb-8133-3a64b1a10c83.png)

Now I stress that my argument mostly comes from a few real world examples and a sort of visual intuition and I don't actually know what I'm talking about. What follows is a paraphrased conversation between me and someone who does:

Me: so you know how in scatterer, atmospheres make the background brighter and two scatterer atmosphere will add and be too bright? I know you fixed this in your implementation of scattering in personal space at one point
where atmospheres always scatter out more light even if you stack atmospheres. do you know what the math for that kind of blend is? (Or slightly more formal language for what I'm describing)

_NovaSilisko (Personal Space developer and less relevantly, former KSP developer)_

_For one I kinda kludged together some extinction math. The other is what i usually see referred to as "one-minus" blending. Let me see if i can find the relevant bit:_

    final = bg + (1.0 - bg) * newstuff

_is the gist of it. Then there is my questionable extinction function:_

    inline float3 Extinct(in float3 sourceColor, in float columnDensity, in float3 netCoeff)
    {
        float3 extinction = exp(-columnDensity * netCoeff * _Opacity);
        return sourceColor * extinction;
    }

_render order is important as well_

**Comment by LGhassen** [comment]
@GregroxMun I did some tests and the soft additive blending + back to front sorting are both working correctly. However extinction doesn't scale correctly with experimentalAtmoScale and may be too weak in general. Will look into it again soon.

**Comment by LGhassen** [comment]
Fixed in latest version
