### ISSUE TITLE
Strange Sunflare

### ISSUE THREAD

**Issue by CindyRIng** [LGhassen/Scatterer#119]
![image](https://user-images.githubusercontent.com/67212205/108614877-5e5c5780-7439-11eb-80b5-f3d67506fffc.png)

**Comment by CindyRIng** [comment]
The strange Ksp SunFlare ,which is not provided by the scatterer has been shown.

**Comment by CindyRIng** [comment]
![image](https://user-images.githubusercontent.com/67212205/108619447-e6555800-745f-11eb-8acb-d79a05ab3406.png)

This is the flare of previous version that is before the 00720

**Comment by CheetahCyberBoi** [comment]
You've installed some kind of Flare pack, because i install the latest one and it's fine.

**Comment by LGhassen** [comment]
> You've installed some kind of Flare pack, because i install the latest one and it's fine.

This is correct
