### ISSUE TITLE
Ocean Z- fighting

### ISSUE THREAD

**Issue by Cooboo117** [LGhassen/Scatterer#12]
The ocean fights with the land and does really weird things, any ideas ??

**Comment by LGhassen** [comment]
If you're talking about the z-fighting that starts at 15 kms up it's fixed and will be released soon.
If you're talking about how it appears to be fighting the shore close to the camera (less than 1000m) it's also fixed and will be released soon. If it's something else describe the issue more in detail.

**Comment by Cooboo117** [comment]
Nope thats spot on... I can't wait for it to be fixed

**Comment by Galenmacil** [comment]
I recently identified the problem with flickering/Z-Fighting ocean. This is with KSP 1.1.2: The flickering will only happen if the framerate is constant above 50. Below it, no flickering.

**Comment by LGhassen** [comment]
The framerate-related flickering is now fixed. The z-fighting will be fixed in the future.
