### ISSUE TITLE
Scattering effects not loading in JNSQ

### ISSUE THREAD

**Issue by Emilius73** [LGhassen/Scatterer#120]
**KSP 1.11.2, Windows 64-bit**

Problem: Atmospheric scatter effects not loading

Mods installed:

- Scatterer
- JNSQ
- Kopernicus (stable branch release 36)
- EVE Redux
- PlanetShine
- Distant Object Enhancement
- Module Manager 4.1.4

**How to reproduce:** Unclear. Problem appeared when loading into the KSC, when in flight and when using the map view in flight. Scattering does load when in the tracking station.

KSP log:

[Player.log](https://github.com/LGhassen/Scatterer/files/6166340/Player.log)

**Comment by Emilius73** [comment]
![image](https://user-images.githubusercontent.com/75502285/111674797-061f3800-87e2-11eb-9638-6c9c6aa30ab5.png)

![image](https://user-images.githubusercontent.com/75502285/111674821-0ae3ec00-87e2-11eb-8294-b41dccaa7bc9.png)

![image](https://user-images.githubusercontent.com/75502285/111674851-13d4bd80-87e2-11eb-8368-68a6b66fa1a4.png)

**Comment by Emilius73** [comment]
![image](https://user-images.githubusercontent.com/75502285/111674920-2cdd6e80-87e2-11eb-9e8a-02bdc2194a23.png)

**Comment by LGhassen** [comment]
I'm not sure honestly what's going on, can you try scatterer with default config? I'm suspecting something is missing in the JNSQ ocean config.

**Comment by LGhassen** [comment]
Closed due to no followup
