### ISSUE TITLE
ocean is totally transperent but is physicaly there

### ISSUE THREAD

**Issue by passivealpaca** [LGhassen/Scatterer#123]
i just turned off the ocean shaders and it became transparent but is physicaly there i just wanted to use scatterer for atmosphere only and wanted the orignal ksp ocean back why this happens i dont use any mods besides visual ones eve,scatterer(probably),sve

please fix it

**Comment by LGhassen** [comment]
In the last public release you need to restart the game for this to fix itself. In the new preview build you can switch immediately.
