### ISSUE TITLE
no sunflare in flight scene, but works on map scene

### ISSUE THREAD

**Issue by kurgut** [LGhassen/Scatterer#124]
KSP : 1.9.1 Windows 64bit
Scatterer v0.0723

Problem : no sunflare on flight scene, but works on map scene

->flight scene : 
![screenshot20](https://user-images.githubusercontent.com/39562611/116750137-4c330280-aa02-11eb-96b8-257e9484ff68.png)

->map scene : 
![screenshot21](https://user-images.githubusercontent.com/39562611/116750152-4fc68980-aa02-11eb-8755-5f767e22dfaf.png)

Mods installed :
ModuleManager v4.1.4.0
scatterer v0.723.0.0

Scatterer settings .cfg : 
[scatterer settings.txt](https://github.com/LGhassen/Scatterer/files/6407711/scatterer.settings.txt)

Log :
[Player.log](https://github.com/LGhassen/Scatterer/files/6407851/Player.log)

I didn't touch the sunflare settings.

Reproduction : 
On a clean install, happens when turning KSP graphical settings down ->
textures : quarter res
render quality : fastest or fast
pixelcount light : 0
shadow cascades : 0

**workaround : To make the sunflare show again, siwtch renderquality back to at least = simple in KSP settings**

So I don't know If it's really an issue or not, as it concerns KSP game settings. But on low end computers (as mine), could it be possible for the sunflare to show even with renderquality tuned down ?

Thank you,
bets regards,
Kurg

**Comment by LGhassen** [comment]
This is unreproducible in 0.0767 and likely fixed by the change I made to force the depth buffer mode.

Can you try the pre-release here and see if you still get it? https://github.com/LGhassen/Scatterer/releases/tag/0.0767

I will close this issue, if it still happens you can reopen it.

**Comment by kurgut** [comment]
@LGhassen  It's fixed, sunflare is rendered in flight scene either with fast or fastest KSP settings.

Thanks for all your work and for this release !
