### ISSUE TITLE
strange harsh terminator line

### ISSUE THREAD

**Issue by sweatbox64** [LGhassen/Scatterer#125]
KSP: 1.11.2 Windows 64bit
Problem: Terminator line is very harsh. 

Mods installed: 

Scatterer 0.0723

EVE Redux 1.11.2.1

Spectra 1.4.0

Reproduction steps:

With the above three installed, launch the game. Then, either navigate to the tracking station or a ship in orbit near kerbin (preferred as the line is difficult to see in the tracking station). It should be fairly obvious what the issue is from there.

Log:

https://www.dropbox.com/s/6szcfur2d2bgk90/output_log.txt?dl=0

Screenshots: 

It is even visible from near the ground: https://cdn.discordapp.com/attachments/494689411041198082/839827350870163456/20210506063336_1.jpg

https://cdn.discordapp.com/attachments/494689411041198082/839823440957014046/20210506051802_1.jpg
https://cdn.discordapp.com/attachments/494689411041198082/839823433193881640/20210506051807_1.jpg
https://cdn.discordapp.com/attachments/494689411041198082/839823439589015562/20210506051814_1.jpg

**Comment by LGhassen** [comment]
This is just the specific configuration of Spectra that produces this. I have informed everyone of some changes that were introduced in 0.0723 to EVE integration, and that configs may need to be adjusted (to taste).

**Comment by sweatbox64** [comment]
Thank you. I will consult the Spectra page for a possible solution. Thank you for your dedication and hard work on one of my favorite mods.

**Comment by sweatbox64** [comment]
> This is just the specific configuration of Spectra that produces this. I have informed everyone of some changes that were introduced in 0.0723 to EVE integration, and that configs may need to be adjusted (to taste).

Thank you. I will consult the Spectra page for a possible solution. Thank you for your dedication and hard work on one of my favorite mods.
