### ISSUE TITLE
Image of objects freeze on screen while traveling through atmosphere

### ISSUE THREAD

**Issue by TravelerTwo** [LGhassen/Scatterer#126]
KSP: 1.11.2 Windows 64bit

Problem: https://imgur.com/a/M6hZX2p
An image of the thing traveling through the atmosphere and becomes frozen in place. The craft still works like it should but there's an image of the craft from a few moments earlier superimposed on the craft itself. Curiously the image is "behind" the craft in IVA, but can you see it through the windows.

Mods installed:

000_AT_Utils
000_USITools
CommunityCategoryKit
CommunityResourcePack
CommunityTechTree
DistantObject
EasyVesselSwitch
Firespitter
GroundConstruction
JNSQ
Kopernicus
kOS
ModularFlightIntegrator
PlanetShine
ReStock
SCANsat
scatterer v0.0770
TriggerTech
UmbraSpaceIndustries

Reproduction steps:

Drop an object from space into the atmosphere.

**Comment by LGhassen** [comment]
Thanks for the report. As see on the forum this should fix it: https://mega.nz/file/HFJiGTIR#A5QQrxBK_eFgDZ3nw4yz4uHSp3aKPllSv22H-nFWF3s

I'm closing the issue for now, you can reopen it if it's not fixed.

Unless further issues are found I will make a public release including this fix soon.
