### ISSUE TITLE
Scatterer ocean forming a cube!

### ISSUE THREAD

**Issue by Ceriousyt** [LGhassen/Scatterer#127]
This issue is present since 0.0770

Here you can see the problem: https://youtu.be/sEGFmApD7j0

In the prevoious version everything worked but at a big performance cost, now after installing 1.12.0 the newer version also does not work.

Gpu: Amd R9 m290x 2gb dx11
Ksp 1.11.2 & 1.12.0 share the same problem.

[KSP.log](https://github.com/LGhassen/Scatterer/files/6719740/KSP.log)

**Comment by LGhassen** [comment]
Include log file please.

**Comment by Ceriousyt** [comment]
Done!

**Comment by LGhassen** [comment]
You appear to be using the APU's integrated graphics (AMD Radeon HD 8650G) instead of the dedicated GPU. I assume this isn't intentional? Can you try running on the dedicated GPU?

**Comment by Ceriousyt** [comment]
> You appear to be using the APU's integrated graphics (AMD Radeon HD 8650G) instead of the dedicated GPU. I assume this isn't intentional? Can you try running on the dedicated GPU?

How? Im using win8.1 since amd does not (as far as I know) provide drivers for my gpu combo. I tried high performance, searched in catalyst, haven't found anything.

**Comment by LGhassen** [comment]
I know nvidia had some options to select using integrated or forcing the discrete card, but I can't say for AMD, so I suggest that you search inline. I'd expect rhe option to be hidden in catalyst somewhere.

**Comment by Ceriousyt** [comment]
> I know nvidia had some options to select using integrated or forcing the discrete card, but I can't say for AMD, so I suggest that you search online. I'd expect the option to be hidden in catalyst somewhere.

I have now found the correct option, and the msi afterburner monitoring software shows the r9 m290x being the active gpu, I have better performance, but the issue is still present.

**Comment by LGhassen** [comment]
Send the new log file please.

**Comment by LGhassen** [comment]
Report from @daimdaimyo posted here https://github.com/LGhassen/Scatterer/issues/153

**Comment by LGhassen** [comment]
@Ceriousyt can you test if this fixes your issue? replace the files from the latest release with these
https://mega.nz/file/SdR3EQBB#NRqw1c8zaWgwDhELUhFTm0rc0QxP_VeSz14XXAWCvT8

**Comment by daimdaimyo** [comment]
@LGhassen 
![image](https://user-images.githubusercontent.com/79315701/161441698-e86b3ba5-eca2-4d09-94ae-8a9dd6306351.png)

**Comment by LGhassen** [comment]
Thanks for testing, I will send you another build soon

**Comment by LGhassen** [comment]
@daimdaimyo you made sure to use the .dll and shaders from 835 with the configs if 831 right?

**Comment by Ceriousyt** [comment]
This Issue is actually long gone, fotgot to close It, I built a new pc, the
6800xt doesn't have the same Issue my r9 had.

вс, 3 апр. 2022 г., 21:11 LGhassen ***@***.***>:

**Comment by Ceriousyt** [comment]
It seems my R9 was lacking some required dx11 featuresets, it ran on the
A10 5750m APU.

вс, 3 апр. 2022 г., 19:41 LGhassen ***@***.***>:

**Comment by daimdaimyo** [comment]
> @daimdaimyo you made sure to use the .dll and shaders from 835 with the configs of 831 right?

Yes I did

**Comment by LGhassen** [comment]
@daimdaimyo test if either of these builds fixes it:

- build a: https://mega.nz/file/3QoHiTRK#jyLGd45CXhHATtMBFyr9-IDOLUM0ykijs7H5Z6nWFos

- build b: https://mega.nz/file/jNJQTKxA#pfFJw4Eshc5sIIyb-TGGfa8AdPaAfrYWXnbKlkYjILI

**Comment by daimdaimyo** [comment]
@LGhassen I am sorry that I didn't tested this a month a ago. I didn't have the time to play at that month BUT I just tested it today and here are the results:

Build a:
![screenshot4](https://user-images.githubusercontent.com/79315701/169482198-e8fe42b7-6735-42e2-bd5f-002d1ddc533e.png)

Build b:
![screenshot6](https://user-images.githubusercontent.com/79315701/169482633-75f5bd58-5420-468d-98f2-3d9a0f7587df.png)

Build c:
![screenshot8](https://user-images.githubusercontent.com/79315701/169484216-4655e7f6-1e9d-4832-ad5f-4b8ee5ee64b6.png)
![screenshot9](https://user-images.githubusercontent.com/79315701/169484222-9e0e95ef-97a7-40cf-a9a7-4430e171ab2e.png)

So the problem disappeared on both Build A and C except for Build B.
Thank you so much!

Btw I tried the latest released and this problem still occurs
![screenshot12](https://user-images.githubusercontent.com/79315701/169485158-3b841dd8-31a5-47d1-bf17-0705e22e8bd0.png)

But once again, Thank you so much!

**Comment by LGhassen** [comment]
@daimdaimyo thank you, I didn't include the changes in last release because I was still waiting on feedback. I will send you a new build based on the latest release you can test.

**Comment by Dojan88** [comment]
I'm getting this bug also. I tried turning all the other settings under ocean shaders off, but to no avail. Everything is fine with ocean shaders disabled.

Scatterer v0.0835 from CKAN. Many other mods also, but I get this with only scatterer installed fresh.
AMD Radeon HD6870 1GB gddr5, with driver version 15.301.1901-160226a-318064E, Core I7 950, 18 GB ram, 1080p

Thanks for your amazing work :) Anything else I can do to help? 

[KSP.log](https://github.com/LGhassen/Scatterer/files/8793200/KSP.log)

**Comment by daimdaimyo** [comment]
> I'm getting this bug also. I tried turning all the other settings under ocean shaders off, but to no avail. Everything is fine with ocean shaders disabled.
> 
> Scatterer v0.0835 from CKAN. Many other mods also, but I get this with only scatterer installed fresh. AMD Radeon HD6870 1GB gddr5, with driver version 15.301.1901-160226a-318064E, Core I7 950, 18 GB ram, 1080p
> 
> Thanks for your amazing work :) Anything else I can do to help?
> 
> [KSP.log](https://github.com/LGhassen/Scatterer/files/8793200/KSP.log)

Try using those builds from his previous replies. One of those files helped fixed my problem. It might fix yours.

**Comment by LGhassen** [comment]
@daimdaimyo could you test if this one works with the latest release? Just replace the .dll from [0.0835](https://github.com/LGhassen/Scatterer/releases/tag/835)

https://mega.nz/file/nBJ3SQiC#DBQBDwXzFnYOZpgqKvyMzRx4bMg2XWebITdI3meDE1c

**Comment by LGhassen** [comment]
The fix is now in the latest release (0.0837). It should work based on the tests above. If it doesn't work feel free to reopen this issue @daimdaimyo @Ceriousyt @Dojan88 .

**Comment by paper342** [comment]
I've installed the latest release, I don't get that original glitch anymore, but I now get a weird visual effect when the water is distant.

Mods:  

Scatterer
Scatterer Default Config
Scatterer Sunflare
B9 Part Switch
Click Through Blocker
Toolbar Controller
Trajectories
Zero MiniAVC
EVE Redux
Waterfall Core
BetterTimewarpContinued
Stock Waterfall Effects
Module Manager

Log: 
[KSP.log](https://github.com/LGhassen/Scatterer/files/9492783/KSP.log)



Screenshot: 
![a355](https://user-images.githubusercontent.com/93014570/188532447-d43e0a57-37a6-49f4-8d24-7959b91b150d.png)
