### ISSUE TITLE
useSubpixelMorphologicalAntialiasing  true - causes blurry cockpit in ASET

### ISSUE THREAD

**Issue by RWOne** [LGhassen/Scatterer#129]
Blurry cockpit in ASET when useSubpixelMorphologicalAntialiasing set true

**Comment by LGhassen** [comment]
Will be fixed in next version

**Comment by RWOne** [comment]
LG, just FYI, if I set that option to 2-high, that also appeared to correct it, but I'm not a coder, I bow to your expertise :)

**Comment by LGhassen** [comment]
You can try the new test version and confirm if it fixes it or not: https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip19-112-scatterer-atmospheric-scattering-00772-18062021/&do=findComment&comment=4022983

**Comment by RWOne** [comment]
Will do! Might be later this afternoon.

Should I change my config to useSubpixelMorphologicalAntialiasing = True?

I'd asume it doesnt overwrite ...
