### ISSUE TITLE
Proper .gitignore

### ISSUE THREAD

**Issue by ThomasKerman** [LGhassen/Scatterer#13]
Some people (namely @eggrobin) on the #RO IRC channel noted, that you uploaded the KSP core .dll files in your [Release](https://github.com/LGhassen/Scatterer/tree/master/scatterer/bin/Release) folder.

Since redistributing them isn't allowed, you should probably:
* Change your VS copy so that they don't get copied into the folder
* Add them to .gitignore, just in case they get added again.

Cheers

**Comment by ThomasKerman** [comment]
Also, you might want to purge the files from the whole history: https://help.github.com/articles/removing-files-from-a-repository-s-history/

Thanks to @eggrobin again

**Comment by LGhassen** [comment]
It is done, thanks @ThomasKerman and @eggrob
