### ISSUE TITLE
 prevent the far side of the planet from also having an eclipse

### ISSUE THREAD

**Issue by GregroxMun** [LGhassen/Scatterer#130]
![image](https://user-images.githubusercontent.com/9667986/124036403-f06a0300-d9cb-11eb-9c43-cdf00116c534.png)

**Comment by LGhassen** [comment]
Fixed. New public test version: https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip19-112-scatterer-atmospheric-scattering-00772-18062021/&do=findComment&comment=4022983

**Comment by ondrejchmelar** [comment]
Would this also fix this Sun water reflection or is that a scatterer issue?

https://drive.google.com/file/d/1kF3mBWqWQsJUv2my9yUqJKA-inTsmbrt/view?usp=sharing

**Comment by LGhassen** [comment]
@ondrejchmelar  you can fix that by enabling long-distance shadows and ocean surface shadows. Or just set scatterer to the "Very high" preset
