### ISSUE TITLE
Blue Layer On Kerbin Error

### ISSUE THREAD

**Issue by madmike521** [LGhassen/Scatterer#131]
KSP: **1.12.1.03142** Windows 64bit

Problem: Blue Layer On Kerbin

Mods installed: (Complete mod list screeshoot is attached, these below i think are the relevant ones)

Scatterer v0.0772

EnvironmentalVisualEnhancements Redux 1.11.3.1

Stock Visual Enhancements v1.4.1 and the scatterer config for it v1.1.6

Reproduction steps:

I have this Blue Layer on screen(check screen shoots attached), that i do not know from where it comes from. For now, this only occurs when in the SpaceCenter menu or in Kerbin flying a rocket. 
Have the issue since KSP 1.10/1.11(Don't know exactly the version it started, but one of this two for sure)

Log: [Player.log](https://github.com/LGhassen/Scatterer/files/6818616/Player.log)

<link>Output_log.txt (preferably dropbox or pastebin link)

![Screenshot (253)](https://user-images.githubusercontent.com/87446830/125683824-81e0d3b4-4848-4717-a237-f65a684d9ca3.png)
![Screenshot (254)](https://user-images.githubusercontent.com/87446830/125683841-b94bf7fd-9930-43d1-b531-b87461f6d3f4.png)
![Screenshot (259)](https://user-images.githubusercontent.com/87446830/125697404-3249f789-02ae-4e68-afc0-7fc8eff9036d.png)

**Comment by LGhassen** [comment]
Don't run in Directx 12. Remove any command line arguments, or any shortcut arguments you have added forcing Directx12, that should fix this. I'm closing this issue, If it doesn't get fixed you can reopen this.
