### ISSUE TITLE
White screen in Tracking Station on Ubuntu 20.04 with amdgpu-pro-21.20-1271047-ubuntu-20.04 driver

### ISSUE THREAD

**Issue by nased0** [LGhassen/Scatterer#132]
![Zrzut ekranu z 2021-07-26 00-03-38](https://user-images.githubusercontent.com/13164219/127077477-6ecd8846-3cfe-4830-b9ca-985379f8722e.jpg)

Hello
I have this Scatterer related problem, when I remove the Scatterer mod, I can use the Tracking Station normally.
I have Radeon RX 580 video card, Intel i7 9800X CPU, 64 GB of RAM and 256 GB SSD with Ubuntu 20.04.
I use KSP 1.12 with the following mods:
Asclepius
AutoHibernate
BeyondHome 1.5.2
CommunityCategoryKit
CommunityTechTree
ContractConfigurator
EasyVesselSwitch
KAS
KIS
Kopernicus 1.12.1-56
Kronkus
MakingLessHistory 1.0
MechJeb2
Milkyway-Skybox-SpaceEngine
ModularFlightIntegrator
Parallax 1.0.1
Parallax_StockTextures
PersistentThrust
PhotonSail
PolishFlagPack
scatterer 0.0772
Sigma
Squad
SquadExpansion
TextureReplacer

[settings.cfg.gz](https://github.com/LGhassen/Scatterer/files/6881846/settings.cfg.gz)

[KSP.log](https://github.com/LGhassen/Scatterer/files/6881836/KSP.log)

**Comment by LGhassen** [comment]
Can you test with scatterer alone?

**Comment by nased0** [comment]
I removed all mods, verified KSP files by Steam and now scatterer is working fine in the Tracking Station.
I will test what mod conflicts with scatterer, starting with Kopernikus, Parallax and Beyond Home.

**Comment by nased0** [comment]
I determined that the minimum set of mods for the glitch to occur (under Linux) is:
BeyondHome
Kopernicus
ModularFlightIntegrator
scatterer
ModuleManager

BeyondHome kind of works without Parallax mod, but there are missing textures.
When I remove ModularFlightIntegrator, glitch does not occur.

**Comment by nased0** [comment]
You can mitigate this glitch by selecting a vessel and switching to Map view, then going back to the Tracking Station.

**Comment by LGhassen** [comment]
Thank you for the detailed report.

I remember reproducing and fixing this bug with beyond home a few versions back so it's weird to see it back. I'm thinking that maybe this happens only on OpenGL. I will give it a try, in the meantime if you have the ability can you test running KSP with proton and see if it still happens (it's supposed to give you better performance too)?

**Comment by LGhassen** [comment]
I fixed this a while back so try the newest version, feel free to reopen if this still happens.
