### ISSUE TITLE
Game Crashes on Startup of a Save

### ISSUE THREAD

**Issue by FishyFish01** [LGhassen/Scatterer#133]
KSP: 1.12, 1.9, 1.9.1, and 1,8

Problem: 
Game crashes every time I try to load a save. This has always been an issue for me, so I never can play with Scatterer enabled. No matter what I try, it always crashes my game upon startup of any save (new or old.) I even tried redownloading the entire game (deleting all game files and reinstalling the entire game.) Nothing has worked. Any help would be greatly appreciated.

Mods Installed:
- Scatterer 0.0772
- Module Manager 4.2.1

Reproduction Steps:
1. Have Scatterer & noted dependencies installed.
2. Load a save.
3. Game Crashes.

Log:
[](https://www.dropbox.com/s/odvk3tz6q6x60wu/Player.log?dl=0)

I'm willing to try literally anything and everything to fix this. I have no clue what to do. Thanks.

**Comment by Tuupertunut** [comment]
Log? See https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/ for instructions.
This might be related to #116, if only I got a log I could tell.

**Comment by FishyFish01** [comment]
Oh my bad, I thought the link worked I guess not tho. I'll try again.

[https://www.dropbox.com/s/odvk3tz6q6x60wu/Player.log?dl=0]

Don't know what happened to the last link.

**Comment by FishyFish01** [comment]
Accidentally closed the issue. I'm new to this lol sorry.

**Comment by LGhassen** [comment]
@FishyFish01 don't run in Directx12. Remove your -force-d3d11 command line argument from steam or the KSP shortcut.

I have no idea who keeps telling people to force Directx12, KSP runs worse than Directx11 on it.

**Comment by FishyFish01** [comment]
How exactly do I do that?

**Comment by FishyFish01** [comment]
Oh! I found it. Nevermind. Appreciate the help. I'll check if it works now.
