### ISSUE TITLE
using SMAA causes blurred and fuzzy image

### ISSUE THREAD

**Issue by Hoskja** [LGhassen/Scatterer#134]
Using SMAA causes the image to become fuzzy and blurry if you change from craft to map view, and persists until you reload through quicksaving.

**Comment by LGhassen** [comment]
Check if this still happens with the new test version: https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip19-112-scatterer-atmospheric-scattering-00772-18062021/&do=findComment&comment=4022983

**Comment by LGhassen** [comment]
Fixed in latest version
