### ISSUE TITLE
Long distance terrain shadows bug?

### ISSUE THREAD

**Issue by VincentThacker** [LGhassen/Scatterer#136]
I get a big black shadow in the opposite side of the sky just before sunrise or immediately after sunset. It seems to be coming from the "Long Distance Terrain Shadows" feature, because it disappears when I turn it off. I know that Kerbin/Earth itself is _supposed_ to cast a shadow at sunrise and sunset, but the shape, position and color here seems completely off, especially ay 14 km altitude. Is there any way to fix/reduce this? The below screenshot is taken right after sunset and the shadow is in the East.

![1]

[1]: https://i.imgur.com/wX3nZxj.png

**Comment by LGhassen** [comment]
These are godrays, you can reduce them with "godrayStrength" or just disable them. Check the wiki:
https://github.com/LGhassen/Scatterer/wiki/PlanetsConfig#config-format
https://github.com/LGhassen/Scatterer/wiki/GeneralConfig#godrays-usegodrays
