### ISSUE TITLE
Weird things appearing in the screen

### ISSUE THREAD

**Issue by paper342** [LGhassen/Scatterer#138]
KSP: 1.12.2 Windows 64bit

Problem: Weird things appearing in the screen

Mods installed:

Scatterer 0.0772 

Reproduction steps:

Default configs, there isn't much of a way to reproduce it, I enter in my save file and it's already there

Observation: Scatterer works fine at a distance of about 100 km from Kerbin and also works fine on Duna, crafts seem blurry when zoomed out.

Log:

[KSP.log](https://github.com/LGhassen/Scatterer/files/7402174/KSP.log)

Screenshot:

![image](https://user-images.githubusercontent.com/93014570/138540277-af664a03-3e1a-4102-9d95-38933f61b3fb.png)

**Comment by LGhassen** [comment]
Closing because duplicate of https://github.com/LGhassen/Scatterer/issues/127

Thanks for the log though, this seems to be a recurring issue with AMD APUs, do you have a dedicated GPU or just the APU?

**Comment by paper342** [comment]
Hi, sorry for the late response.

I have an APU, do you have some kind of fix or are you working on it?

**Comment by paper342** [comment]
> Closing because duplicate of #127
> 
> Thanks for the log though, this seems to be a recurring issue with AMD APUs, do you have a dedicated GPU or just the APU?

Hi, sorry for the late response.

I have an APU, do you have some kind of fix or are you working on it?

**Comment by LGhassen** [comment]
@paper342 can you test this? https://github.com/LGhassen/Scatterer/issues/127#issuecomment-1086915412
