### ISSUE TITLE
Messed up surfaces after updating Scatterer and EVE

### ISSUE THREAD

**Issue by TheComputer314** [LGhassen/Scatterer#140]
![image](https://user-images.githubusercontent.com/70153520/141365701-418ad3e3-a734-4c75-9c4e-22e6cfd01d7a.png)
![image](https://user-images.githubusercontent.com/70153520/141366373-32680181-54a9-498f-b0e2-a7fb552826b9.png)
![image](https://user-images.githubusercontent.com/70153520/141366507-9cae238b-db9b-4ffa-a070-5132541ba47b.png)
![image](https://user-images.githubusercontent.com/70153520/141366788-ffffd29d-5f7f-4de8-868d-93e059b4bad6.png)
![image](https://user-images.githubusercontent.com/70153520/141366915-6a6f88c4-85eb-4244-9c9c-3278cde73bc2.png)

Game version: 1.12.2.3167 Steam.
DLC versions: Making History 1.12.1, Breaking Ground 1.7.1

Hardware: (Laptop)
CPU: AMD Ryzen 7 3700U with Radeon Vega 10 Mobile GFX
GPU: Radeon Vega 10 Mobile
RAM: 4GB soldered, 16GB SODIMM, 20GB usable
OS: Windows 11

Details:
See screenshots above.
Game hangs for a bit in the tracking station when switching focus to a planet with an atmosphere.

**Comment by TheComputer314** [comment]
Mods list:

> [x] Science! Continued (xScienceContinued 6.0.0.9)
> BetterBurnTime (BetterBurnTime 1.10)
> BetterTimeWarpContinued (BetterTimeWarpCont 2.3.12.9)
> Breaking Ground (BreakingGround-DLC 1.7.1)
> Camera Focus Changer (CameraFocusChanger 1:1.1.0.1)
> Camera Tools continued (CameraTools v1.19.1)
> ClickThrough Blocker (ClickThroughBlocker 1:0.1.10.17)
> Community Terrain Texture Pack (CommunityTerrainTexturePack 1:1.0.4)
> Distant Object Enhancement /L (DistantObject v2.1.1.6)
> Distant Object Enhancement /L default config (DistantObject-default v2.1.1.6)
> Engine Lighting Relit (EngineLightRelit 1.6.3.1)
> Environmental Visual Enhancements - Stock Planet Config files (EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1)
> Environmental Visual Enhancements Redux (EnvironmentalVisualEnhancements 3:1.11.5.1)
> EVA Enhancements Continued (EVAEnhancementsContinued 0.1.15.3)
> Extended information about scientific experiments in VAB (ScienceSituationInfo 1:1.3.5)
> Ferram Aerospace Research Continued (FerramAerospaceResearchContinued 3:0.16.0.4)
> Hangar Extender (FSHangarExtender 3.6.0.1)
> Hot Spot (HotSpot 0.9.0)
> Kerbal Engineer Redux (KerbalEngineerRedux 1.1.9.0)
> Kerbal Joint Reinforcement - Next (KerbalJointReinforcementNext v4.1.15)
> Kopernicus Planetary System Modifier (Kopernicus 2:release-1.12.1-60)
> KSP Ground Effect (GroundEffect 1.1.0-catalpa)
> Making History (MakingHistory-DLC 1.12.1)
> MechJeb 2 (MechJeb2 2.12.3.0)
> Minimum Ambient Lighting Updated (MinAmbLightUpd 1.2.6.2)
> ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
> Module Manager (ModuleManager 4.2.1)
> Parallax (Parallax 1.3.1)
> Parallax - Stock Planet Textures (Parallax-StockTextures 1.3.1)
> PlanetShine (PlanetShine 0.2.6.3)
> PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.3)
> RCS Build Aid (RCSBuildAid v1.0.6)
> scatterer (Scatterer 3:v0.0825b)
> Scatterer Default Config (Scatterer-config 3:v0.0825b)
> Scatterer Sunflare (Scatterer-sunflare 3:v0.0825b)
> SpaceTux Library (SpaceTuxLibrary 0.0.8.2)
> Station Keeping (StationKeeping 1:0.2.2.2)
> Stock Waterfall Effects (StockWaterfallEffects 0.5.2)
> Toolbar (Toolbar 1:1.8.0.7)
> Toolbar Controller (ToolbarController 1:0.1.9.6)
> Trajectories (Trajectories v2.4.3)
> Waterfall Core (Waterfall 0.6.7)
> Zero MiniAVC (ZeroMiniAVC 1:1.1.2.4)

**Comment by TheComputer314** [comment]
![image](https://user-images.githubusercontent.com/70153520/141367753-485ba38b-9295-41b3-bf23-e75b1a345a90.png)
The KSC seems bluer than normal.

**Comment by LGhassen** [comment]
The KSC is supposed to be bluer than normal so ignore that.

- Is the problem with the planets only in tracking station and main menu?
- What about map view in flight?
- What about normal flight camera but from high orbit (>160 km)?
- Do you have the game's stock anti-aliasing enabled and at which setting?
- What happens if you change/disable your AA setting? What happens if you change it then switch scenes?

**Comment by TheComputer314** [comment]
Anti-aliasing: off.
Zooming out really far in flight view seems normal, and map view also seems to be normal.
![image](https://user-images.githubusercontent.com/70153520/141372578-8bdfc254-0184-47a0-b16d-72b2c8b6fa4c.png)
![image](https://user-images.githubusercontent.com/70153520/141372598-0cb9d794-bf9e-43f5-a814-9cb43d1bdb6e.png)
![image](https://user-images.githubusercontent.com/70153520/141373212-1c95de3d-1b53-4274-95eb-ee380a8fc6a7.png)

Changing anti-aliasing fixes the tracking station but not the main menu.
![image](https://user-images.githubusercontent.com/70153520/141372958-0240c49d-bd61-4d47-acc0-8debc151ed48.png)
![image](https://user-images.githubusercontent.com/70153520/141373054-3c2d716d-ec35-4433-9ba9-ccf2e59453a4.png)

**Comment by TheComputer314** [comment]
I'm an idiot, I forgot to reenable antialiasing when taking the main menu screenshot. Antialiasing also fixed main menu.
![image](https://user-images.githubusercontent.com/70153520/141373331-3bfb4121-72b8-4dce-a53e-465f498b1b7a.png)

**Comment by LGhassen** [comment]
Thanks @TheComputer314 for testing. I think I know more or less how to fix this but I'm going to be busy for a while. Until I fix it you can keep the in-game AA enabled, scatterer will disable it in-flight to enable it's own SMAA so you won't get a performance hit, while also fixing this bug.

**Comment by TheComputer314** [comment]
Alright. Thanks.

**Comment by LGhassen** [comment]
Fixed in 0.0827
