### ISSUE TITLE
TU / TURD textures flickering on craft, with the last Scatterer, not the previous one.

### ISSUE THREAD

**Issue by Dadkitess** [LGhassen/Scatterer#141]
https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip112x-scatterer-atmospheric-scattering-00825-11112021-scattering-improvements-in-game-atmo-generation-and-multi-sun-support/&do=findComment&comment=4053754

**Comment by LGhassen** [comment]
Reportedly coming from EVE clouds flickering in the reflection probe: https://forum.kerbalspaceprogram.com/index.php?/topic/174188-112x-textures-unlimited-recolour-depot/

**Comment by LGhassen** [comment]
Fixed in 0.0827
