### ISSUE TITLE
Water is Gone

### ISSUE THREAD

**Issue by MAJN9N** [LGhassen/Scatterer#142]
The water is gone.

![screenshot10](https://user-images.githubusercontent.com/43098071/141498207-3c8220d1-ae96-46fb-ab8a-781fbdb74731.png)
![screenshot8](https://user-images.githubusercontent.com/43098071/141498255-f373c945-5411-4a30-b6ee-87f1b71b758b.png)

This is tested on an unmodded version of KSP - only Scatterer installed. The Scatterer button doesn't even work, so no way to configure anything.

KSP 1.12.2
Intel i7
RTX 2060 
32 GB RAM
Windows 10

**Comment by LGhassen** [comment]
Logs

**Comment by MAJN9N** [comment]
I closed this because right after I opened it I found a duplicate copy of an older version Scatterer in my game folder (.../GameData/GameData/scatterer (!?)). Removing that resolved the issue.

My bad, my apologies.
