### ISSUE TITLE
Unable to save custom atmoshpheric edits

### ISSUE THREAD

**Issue by TJBotSN** [LGhassen/Scatterer#145]
Atm Module manager is patching something in Scatterer removing my ability to save atmospheric edits such as reducing the scale of Kerbins atmoshphere
![Save issue Scatterer](https://user-images.githubusercontent.com/96357437/146657446-8382fb0f-9c65-4ab0-a0c1-22cc98c9e36f.jpg)
.

**Comment by TJBotSN** [comment]
The issue was Spectra, some kind of issue with Module manager im guessing

**Comment by LGhassen** [comment]
ModuleManager configs from mod are used to override configs **after** the game has started. It's the way they are designed to work. Scatterer does not override these. After you're happy with your settings find your MM patch and modify it manually.

**Comment by TJBotSN** [comment]
Okay, where am i supposed to find the MM patch (im no good a this file stuff)

**Comment by LGhassen** [comment]
Should be in the visual mod folder (spectra or whatever else is applying the visual configs).
