### ISSUE TITLE
White Ocean and Atmosphere when using the ckan version of Scatterer

### ISSUE THREAD

**Issue by davifrancis60** [LGhassen/Scatterer#147]
My water and atmosphere Suddently turned white after the new update i don't know if there is something related but this issue is currenctly happening to me im also using Astronomers Visual Pack.

**Comment by LGhassen** [comment]
Include logs and screenshots

**Comment by davifrancis60** [comment]
> Include logs and screenshots

i currently don't know how to send the logs because in kinda new to ksp but here are some screenshots of my menu and in game
![unknown](https://user-images.githubusercontent.com/97868256/149806706-e7764adc-b1de-4b48-830a-b0f2858fada8.png)
![img](https://user-images.githubusercontent.com/97868256/149806991-13139090-5c59-478d-9f2e-420718220756.png)

**Comment by LGhassen** [comment]
Still need logs, look for KSP.log in your game folders. Send a fresh version after running KSP and getting the issue.

**Comment by davifrancis60** [comment]
> Still need logs, look for KSP.log in your game folders. Send a fresh version after running KSP and getting the issue.

Here found it
[KSP.log](https://github.com/LGhassen/Scatterer/files/7891336/KSP.log)

**Comment by LGhassen** [comment]
I see no errors but you have a GameData folder inside GameData, get rid of that and clean up your install, likely you have duplicate/conflicting configs.
