### ISSUE TITLE
how  solves

### ISSUE THREAD

**Issue by edrr711** [LGhassen/Scatterer#148]
![Capturar](https://user-images.githubusercontent.com/98289953/150702587-3ab4037a-2f28-4adb-91f0-b736c4a13855.PNG)
![Captura de tela 2022-01-23 203210](https://user-images.githubusercontent.com/98289953/150702609-372b83ae-837b-4694-80f5-5a800b7822e6.png)

**Comment by LGhassen** [comment]
L.O.G.S

**Comment by edrr711** [comment]
sorry which

**Comment by edrr711** [comment]
[Scatterer.0.0829.zip](https://github.com/LGhassen/Scatterer/files/7929595/Scatterer.0.0829.zip)

**Comment by edrr711** [comment]
already replaces several times

**Comment by LGhassen** [comment]
Test this https://mega.nz/file/SQYC3LiQ#b1JQP83FAW4hAtJLkeEO7gcjzSBCFkZOTjjtf3C6IMo

**Comment by LGhassen** [comment]
Should be fixed in 0.0830
