### ISSUE TITLE
Orbital Lines Broken, and very slight blur on ships

### ISSUE THREAD

**Issue by TJBotSN** [LGhassen/Scatterer#151]
KSP: 1.12.2
Problem: Orbital Lines Broken and very slight blur on ships

Mods installed:
![image](https://user-images.githubusercontent.com/96357437/153734303-892b5013-c428-49f6-9f36-83526a1a8d47.png)

Issue:
![20220212201849_1](https://user-images.githubusercontent.com/96357437/153734306-a4c1f83f-f102-4e8f-aaaf-e2ccabf58f54.jpg)
![20220212201840_1](https://user-images.githubusercontent.com/96357437/153734309-3c749776-6255-4111-8f26-6cac162aa1c6.jpg)

The issue might not be very noticible but its pretty annoying. More importantly ive identfied that Scatterer is the cause of the issue as the orbital lines are not broken when the mod is not present.

**Comment by TJBotSN** [comment]
Seems to be the exact or similar problem with issue #134 if i turn SMAA off, the problem is solved.

**Comment by LGhassen** [comment]
Where exactly is the issue?

**Comment by TJBotSN** [comment]
The orbital lines at close view are thinner in some sections and wider in others, sorry if this is nitpicky, just catches my eye a lot.
![image](https://user-images.githubusercontent.com/96357437/153757621-bf36dd0d-f551-4369-82dd-7045325462df.png)

**Comment by LGhassen** [comment]
That's just aliasing

**Comment by TJBotSN** [comment]
Gotcha its unfortunate but ive got around it.
