### ISSUE TITLE
Shadows extremely low quality, sudden quality shifts

### ISSUE THREAD

**Issue by Kopernicus-Shadows2** [LGhassen/Scatterer#152]
The integrated shadows are very low quality under regular settings, and have very sudden and obvious quality cutoffs based upon distance:
![20220215193857_1](https://user-images.githubusercontent.com/93224219/154174016-b1068335-b357-4629-bad9-a527e0ed7ab0.jpg)
The cutoff is visible in the shadow of the deployable solar panel.

**Comment by LGhassen** [comment]
Not an issue, that's the default game's shadows. Use one of the higher presets (from scatterer menu accessed by the blue icon in the lower right corner in ksc screen) or configure your own shadows.
