### ISSUE TITLE
Ocean Shader Glitch

### ISSUE THREAD

**Issue by daimdaimyo** [LGhassen/Scatterer#153]
KSP: 1.12.3.3173 (WindowsPlayer x64) en-us -force-d3d11 (idk where to put this sorry)
OS: Windows 10 (10.0.0) 64bit
Scatterer version: v0.0831
Desciption:
When I have the ocean shaders enabled, water starts dancing around. But this issue disappear when I turn it off.
 
[KSP.log](https://github.com/LGhassen/Scatterer/files/8104405/KSP.log)
(Btw my gpu is amd radeon hd 6770m but for some reason, ksp DOESN'T recognize it. But I know that it is being used.)

My mods:
EVE Redux
KerbalJointReinforcement
Kopernicus
ModularFlightIntegrator
RealSolarSystem
RSSDateTime
RSS-Textures
RSSVE
Scatterer
![Screenshot (43)](https://user-images.githubusercontent.com/79315701/154852776-d3dfd3dd-1e6e-43b3-a5f7-91be18eb3ff6.png)

**Comment by LGhassen** [comment]
>Btw my gpu is amd radeon hd 6770m but for some reason, ksp DOESN'T recognize it. But I know that it is being used.

It is NOT being used if it doesn't appear in the log. You should probably look at that.

This is a duplicate issue of https://github.com/LGhassen/Scatterer/issues/127 so i'll just close this and add your logs there.

**Comment by daimdaimyo** [comment]
UPDATE: I tried using -force-opengl and somehow it fixed the problem. Weird.

![Screenshot (188)](https://user-images.githubusercontent.com/79315701/154888089-34eb1634-faa3-4f38-bcd2-c758a347b5ea.png)

**Comment by LGhassen** [comment]
@daimdaimyo Can you test this? https://github.com/LGhassen/Scatterer/issues/127#issuecomment-1086915412
