### ISSUE TITLE
atmospheres too thick

### ISSUE THREAD

**Issue by capwindow2** [LGhassen/Scatterer#155]
so in the instructions it says that experimentalAtmoScale, when set to certain number values, basically raises/lowers the atmosphere
well, in the atmospheric configs of all the planets, that configuration didn't exist in my files
i tried adding my own, spelled it out right, spaced it right, etc
it still wouldn't change the atmosphere height or thickness or whatever
for eve, thats the only planet i tried it on
is there any way I can actually change the planetary atmosphere height/thickness bc experimentalAtmoScale isn't working

**Comment by LGhassen** [comment]
If using versions after 0.0772 the atmospheres work differently (I haven't updated the docs but there are notes in the release notes). There is an in-game atmo tab (alt-f11 -> atmosphere) where there is an "auto rescale" field (see here https://www.youtube.com/watch?v=u6Jxgc-cYcc), use that to rescale the atmo. If using ModuleManager configs you'll have to copy out the resulting values manually to the ModuleManager config.

**Comment by capwindow2** [comment]
ok, ill have to try that today

**Comment by capwindow2** [comment]
thank you tho

**Comment by capwindow2** [comment]
Ok so
i tried using the in game menu, but it never saves any of my changes when i look at another planet- it keeps saying, in the [cfg file used] part (in red text) ModuleManager patch detected, saving disabled @LGhassen

**Comment by LGhassen** [comment]
Thay's why I said If using ModuleManager configs you'll have to copy out the resulting values manually to the ModuleManager config. Ie find the mod that modifies the config and edit the .cfg files there.

**Comment by capwindow2** [comment]
Forgive my ignorance, but... how exactly would I find the specific mod that modifies ModuleManager? I have 80+ installed right now...

**Comment by LGhassen** [comment]
That's up to you. You installed an atmosphere config mod so you should have a rough idea. Or just do a search for "Scatterer_atmosphere" in all *.cfg files in GameData.

**Comment by capwindow2** [comment]
Oh, ok
I'll try that

**Comment by MeTeOrMaSh15** [comment]
@LGhassen hey so i know this was a while ago, but i finally got around to configuring the atmospheres
but the problem is i'm using OPM and theres no scatterer configs for those planets so i won't be able to save those atmosphere profiles
what can i do?
