### ISSUE TITLE
"Halo" from atmosphere

### ISSUE THREAD

**Issue by dawidpotok** [LGhassen/Scatterer#16]
In directX 11 and OpenGL, Kerbin, Duna and Jool have strange looking atmosphere. It is visible only from sun side.On Laythe and Eve everything is fine.
Bug appears regardless of other mods.
![screenshot82](https://cloud.githubusercontent.com/assets/19761347/15805963/c888f87e-2b38-11e6-8663-99d866e52561.png)
![screenshot83](https://cloud.githubusercontent.com/assets/19761347/15805965/c88d0ae0-2b38-11e6-9d12-1b91baf198fd.png)
![screenshot84](https://cloud.githubusercontent.com/assets/19761347/15805964/c88ca51e-2b38-11e6-91fb-9d4275fc1e45.png)

**Comment by LGhassen** [comment]
Working on it

**Comment by LGhassen** [comment]
Should be fixed with newest version (except for some Mac users), could you test?

**Comment by dawidpotok** [comment]
I`ve done a quick test couple days ago on clean 1.1.3 and it seems all right.

**Comment by LGhassen** [comment]
Additionally, I've added a switch for this in the main menu for people still getting the issue.
