### ISSUE TITLE
Atmosphere blocking sun

### ISSUE THREAD

**Issue by Rodg88** [LGhassen/Scatterer#160]
As per forum post, except I've found it also happens without GPP_Rescale (or TUFX), it was just not happening in the low orbit I first tested with. So it happens in both unscaled and rescaled versions of GPP, just in higher orbits. I'm guessing it could be due to pre-0.8 configs in GPP, but it still seems like weird behavior. 

Another example
before sunset:
https://cdn.discordapp.com/attachments/717083043323445258/971105172921126952/unknown.png
sun behind atmo:
https://cdn.discordapp.com/attachments/717083043323445258/971105219117191168/unknown.png
sun behind planet:
https://cdn.discordapp.com/attachments/717083043323445258/971105328894722048/unknown.png

Player log:
https://gist.github.com/Rodg88/3ecf12279b897fd43aff7738db0773a3

The GPP configs: https://github.com/Galileo88/Galileos-Planet-Pack/tree/master/GameData/GPP/GPP_Scatterer/Planets/Gael

**Comment by Rodg88** [comment]
tested really turning down the thickness and scale, and it still occurs, just for a shorter time as there's less atmo for the sun to be behind.

**Comment by LGhassen** [comment]
Screenshots don't work, is this still an issue?

**Comment by Rodg88** [comment]
I did just test with GPP with latest scatterer, and this issue is fixed

The old screenshots:
before sunset:
![image](https://github.com/LGhassen/Scatterer/assets/2611674/4037042c-d501-4610-b16c-22613a181227)
sun behind atmo (craft is completely black):
![image](https://github.com/LGhassen/Scatterer/assets/2611674/ff3a41ff-5819-46cb-aa81-daff74b60e6c)
sun behind planet (craft is lit by ambient light again):
![image](https://github.com/LGhassen/Scatterer/assets/2611674/2b985b92-29bf-4014-81eb-24aa1fa405d1)

**Comment by LGhassen** [comment]
Thank you for the update @Rodg88
