### ISSUE TITLE
Sunflares broken on linux due to path issue

### ISSUE THREAD

**Issue by LGhassen** [LGhassen/Scatterer#163]
Reported by @Technologicat

https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip19x-112x-scatterer-atmospheric-scattering-00835-22042022-scattering-improvements-in-game-atmo-generation-and-multi-sun-support/&do=findComment&comment=4147060

**Comment by Technologicat** [comment]
Thanks for creating the issue ticket :)

Do you want a PR, or do you prefer to fix it yourself?

According to my testing, the only changes needed are the paths in `Sun.cfg`, as mentioned in the forum post.

**Comment by LGhassen** [comment]
The configs repo is out of date and I don't really build the configs from it so a PR won't help.

I can tix it myself the next time, you described it well.

**Comment by LGhassen** [comment]
Fixed in 0.0837.
