### ISSUE TITLE
white sky

### ISSUE THREAD

**Issue by Bongchong1** [LGhassen/Scatterer#168]
scatter makes ksp freeze when done loading when i open it up with no mods then when i open ksp again it shows a white atmosphere i have tried version 835, 834 and 831. 8gb ram, intel i3 and intel uhd

**Comment by Bongchong1** [comment]
[KSP.log](https://github.com/LGhassen/Scatterer/files/9175031/KSP.log)
log

**Comment by LGhassen** [comment]
@Bongchong1 can you try deleting ScattererAtmosphereCache from gamedata then try a clean install of 0.0835?

**Comment by Bongchong1** [comment]
ok so i did what you said i when i opened the game it froze at the title screen with no options but when i opened it up again it showed kerbin with a white atmosphere. i then went into the tracking station and zoomed in on eve and it froze, opened up ksp again and this time i saw a green looking eve. i did that for duna and the same happend but duna looked normal albeit a little darker[
![Screenshot (174)](https://user-images.githubusercontent.com/109885551/181133510-69460cfd-cb15-43b8-b354-0e50f5fd8be3.png)
![Screenshot (175)](https://user-images.githubusercontent.com/109885551/181133513-e8c24c35-6287-4bbd-9588-0b2e187dedb3.png)
![Screenshot (176)](https://user-images.githubusercontent.com/109885551/181133562-1b5c7aa4-bdf1-4ad8-bb08-cb255045eafc.png)
](url)

**Comment by LGhassen** [comment]
Alright, I know what's going on, I'll send you a new build to try but it may be a while before I can do that.

**Comment by Bongchong1** [comment]
ok

**Comment by LGhassen** [comment]
@Bongchong1 in the meantime if you can get someone to send you their scattererAtmospherCache folder it will work.

**Comment by Bongchong1** [comment]
will do

**Comment by LGhassen** [comment]
@Bongchong1 please try the .dll I posted in the discord (in reply to your request for the atmo cache)

**Comment by Bongchong1** [comment]
same thing, froze on title screen on first launch then i got the white atmosphere again

**Comment by LGhassen** [comment]
@Bongchong1 try even newer one I just posted in discord

**Comment by Bongchong1** [comment]
currently it has frozen 3 times on the title screen

**Comment by MillsLite** [comment]
I think I have the exact same issue, please share the solution here. I don't know what discord you're using.

**Comment by LGhassen** [comment]
Hi @MillsLite that fix is integrated in version 838 but it's not effective for everyone. If you're still getting the issue on 838 then it won't help you. I will make a better fix soon (hopefully) but in the meantime you can revert to version 778.

**Comment by LGhassen** [comment]
@MillsLite Actually can you test a new version for me? I'm just testing out a new fix for this.
Note: This is based on my patreon-only and will not work with the public version of EVE so if you have EVE installed, remove it and move it to a backup for now while you test this. Also delete existing scatterer and scattererAtmosphereCache before installing this: https://drive.google.com/file/d/1pODz75QWvREXCfa5Lp4ljAJ1zw13cjxs/view?usp=sharing

On the game's main menu the atmosphere will take longer to load and the game should be freezing/unfreezing every few seconds for a bit until the generation finishes. Let me know if it works and I'll make a public release (it won't be immediate becauseI still need to update some things but should happen soon).

**Comment by MillsLite** [comment]
I gave it a shot but the night sky went black. I deleted EVE, scatterer, and scattererAtmosphereCache and placed both of the folders from the link directly into gamedata. It loaded quickly without much fuss and I loaded a save I have specifically for testing mods. The space centre looked fine but when I took control of a rocket I already had in suborbital the sky was black. I could see the celestial bodies but the star-box was gone. I then moved to view the other bodies like Duna and at first there was no difference to the stock game but after a few seconds the atmosphere flickered in and out and then finally back in for good, however, on each "in" flick the star-box would go to black again.

**Comment by LGhassen** [comment]
@MillsLite thanks for testing, would you mind sending your KSP.log file?

**Comment by MillsLite** [comment]
[KSP.log](https://github.com/LGhassen/Scatterer/files/14240700/KSP.log)
@LGhassen Sorry for the slow response. I'll be going AFK until mid-March. I'll follow up when I get back.

**Comment by LGhassen** [comment]
For everyone who gets this, this happens when the atmosphere generation takes a long time and windows thinks the gpu crashed (when it hasn't). You can change the windows setting to fix this as instructed here: https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-windows/2024-1/gpu-adjust-timeout-detection-and-recovery-setting.html
