### ISSUE TITLE
Sunflare is bugged with KScale64

### ISSUE THREAD

**Issue by N70** [LGhassen/Scatterer#17]
I've attempted with the Eden Sunflare, Astroniki Sunflare, and normal scatterer sunflare, but the sunflare is never the right thing...   (I am forcing dx11 btw)  
  
Normal scatterer sunflare:  
  ![normalsunflare](https://cloud.githubusercontent.com/assets/6045353/15819802/6082144c-2bb3-11e6-8024-a87ca5c23cc7.png)  
  
Astroniki:  
![astronikiflare](https://cloud.githubusercontent.com/assets/6045353/15819987/4c60da60-2bb4-11e6-9910-b9f2f3520f4e.png)

**Comment by LGhassen** [comment]
Does it work in dx9? Does it work with stock system in dx9?

**Comment by Quartz101** [comment]
I did not change the config, but let me test to see if it works w/ dx9.

**Comment by Quartz101** [comment]
Same result with KScale64 after -force-d3d9, but working as normally with stock sys and -force-d3d9. Tested with Astroniki, result looks the same.

**Comment by LGhassen** [comment]
Ok, have you tried to rescale the config file like it says in the OP of the forum thread?

**Comment by Quartz101** [comment]
Rescale config? Do you mean this?:  
```
//sunFlare.png
flareSettings = 0.45,1,0.085

//sunSpikes.png
spikesSettings = 0.6,1,0.1
```  
If so, how to adapt it for 6.4x?
