### ISSUE TITLE
Jitters

### ISSUE THREAD

**Issue by MeTeOrMaSh15** [LGhassen/Scatterer#170]
i'm sure by now given how many issue's ive posted you must think my computer is either haunted or i'm putting up BS, but hear me out
whenever i'm controlling a ship now in the map view, everything starts to slightly jitter up&down (link to reddit post: basically what's happening to me: https://www.reddit.com/r/KerbalSpaceProgram/comments/u33v1u/shaky_graphics_in_map_view/
people have identified this as something from Scatterer, can you fix this pls?

**Comment by MeTeOrMaSh15** [comment]
@LGhassen so it was identified as a problem with the antialiasing feature, when its disabled the problem doesn't exist but i'd really like to be able to use the antialiasing feature without the map view jittering. can you possibly fix this?

**Comment by LGhassen** [comment]
@MeTeOrMaSh15 it's fixed

**Comment by MeTeOrMaSh15** [comment]
@LGhassen so it... isn't actually fixed. When in map view, with TUFX TAA off, and Scatterer TAA on, the game still jitters just like it used to.

**Comment by LGhassen** [comment]
You still haven't said if it works if you uninstall tufx and other mods

**Comment by MeTeOrMaSh15** [comment]
TUFX has been uninstalled, the map view in flight still jitters with Scatterer TAA

**Comment by LGhassen** [comment]
No clue since that doesn't happen on my end

**Comment by MeTeOrMaSh15** [comment]
@LGhassen Update: I uninstalled basically every other graphics mod except scatterer and it still jitters in flightmap view and in spacecenter/flight view

**Comment by LGhassen** [comment]
I think TAA is not working for you at all, I mean do you see any antialiasing on the image?
