### ISSUE TITLE
Map Jitters/Tekto still broken

### ISSUE THREAD

**Issue by MeTeOrMaSh15** [LGhassen/Scatterer#172]
Development here: The .838 update did not fix the map view jittering issue for me, and Tekto still has the outline on its horizon. Nobody in the AVP forums or KSP discord modding help has been able to assist with these issues, so if you could give any advice on these issues I would be very thankful. I apologize for bothering you so much with these bugs but I would very much like them fixed.
![image](https://user-images.githubusercontent.com/43767152/185728088-39f9c163-746c-4194-a1d9-0be2705a9d66.png)

**Comment by LGhassen** [comment]
Post video of the jittering + logs.

For the atmo, that is a known issue with old atmo configs or really thick ones, try to make it thinner, and also try changing the mie-G value.

**Comment by MeTeOrMaSh15** [comment]
This is someone else's capture of the jitter but it looks identical to mine. I know that the problem is caused by antialiasing, but I thought that was fixed in 0.0838. I don't know if the OPM configs are updated for Scattered 0.800, I'll have to ask. I'll try the mie-G value thing rn.
https://imgur.com/a/WHZQbtT

**Comment by MeTeOrMaSh15** [comment]
How do I post a log without clogging the entire issue thread?

**Comment by LGhassen** [comment]
Upload it on pastebin or google drive or something

**Comment by MeTeOrMaSh15** [comment]
https://pastebin.com/WN7hpHNN here is the log

**Comment by LGhassen** [comment]
No idea how your game can still jitter ¯\_(ツ)_/¯

**Comment by LGhassen** [comment]
Can you try running with just scatterer and no tufx?

**Comment by MeTeOrMaSh15** [comment]
i have 97 mods installed
do you want all of them off or just visuals

**Comment by MeTeOrMaSh15** [comment]
@LGhassen ok so after a while ive found this
- TUFX TAA makes it jitter in map view as well, but so does Scatterer TAA. this may be why it was jittering still but ill have to see
- TUFX FXAA removes jitters, but TUFX also has other problems
- ill lyk if its still jittering without TUFX at all in map view
