### ISSUE TITLE
Scatterer's TAA interferes with HDR in TUFX

### ISSUE THREAD

**Issue by JonnyOThan** [LGhassen/Scatterer#179]
When scatterer's TAA is enabled, HDR in TUFX is much less effective:

Scatterer not installed; HDR & Bloom on:
![no scatterer, HDR and bloom on](https://user-images.githubusercontent.com/9804078/189532246-edde3985-f292-4814-8674-73a4aab791ce.png)

Scatterer installed, TAA off, HDR & Bloom on:
![scatterer taa off, hdr   bloom on](https://user-images.githubusercontent.com/9804078/189532267-508c4853-7d97-4c5b-bee5-f8849b55275e.png)

Scatterer installed, TAA on (default), HDR & Bloom on:
![scatterer taa, hdr and bloom on](https://user-images.githubusercontent.com/9804078/189532285-ff906a36-0314-4558-a2cf-f206c3894df6.png)

**Comment by LGhassen** [comment]
Can you just use tufx's taa in that case?

**Comment by JonnyOThan** [comment]
Yes, and that's what I do, but this was reported as a bug in the tufx forum thread.  I might take a look if I get tired of VR stuff.

**Comment by LGhassen** [comment]
Ok well two things come to mind: the textures scatterer uses as flip flop buffers may not be 16bit (not sure about this I may have a switch for this), and the order operations are done may be so that the screen copy is done before bloom is applied, then antialiased results are copied to the screen after bloom is applied, removing it. I haven't checked to confirm these ideas.

**Comment by JonnyOThan** [comment]
My hunch is the first thing: a render target somewhere isn't being created as HDR when necessary.  If I enable scatterer's TAA and turn the bloom threshold way down, the bloom still functions.

**Comment by LGhassen** [comment]
It appears to be the case https://github.com/LGhassen/Scatterer/blob/master/scatterer/Effects/AntiAliasing/TemporalAntiAliasing.cs#L162

Jus add an if(camera.hdr) and change argb32 to argbhalf in that case

**Comment by LGhassen** [comment]
Yeah VR was the last thing on my mind when I adapted this 😅
