### ISSUE TITLE
Hard terrain line

### ISSUE THREAD

**Issue by JoelleEmmily** [LGhassen/Scatterer#18]
System and KSP information attached, 64-bit executed.

I've installed scatterer alone on a fresh install of KSP, and no matter what settings I use, hard terrain lines can be seen on a planet's surface, and hard navigation like lines can be seen in the air. Atmospheric lines remain once in orbit, however, as far as I can tell, "space" texturing remains unchanged.

**Comment by JoelleEmmily** [comment]
![screenshot0](https://cloud.githubusercontent.com/assets/3618013/17126506/d83c5c9c-52cb-11e6-8685-f4a6f182ff06.png)
![screenshot1](https://cloud.githubusercontent.com/assets/3618013/17126507/d83f114e-52cb-11e6-82eb-8b6b6a587be5.png)

**Comment by JoelleEmmily** [comment]
[KSP.log.txt](https://github.com/LGhassen/Scatterer/files/383049/KSP.log.txt)
[Player.log.txt](https://github.com/LGhassen/Scatterer/files/383050/Player.log.txt)
[sys_info.txt](https://github.com/LGhassen/Scatterer/files/383054/sys_info.txt)
[settings.cfg.txt](https://github.com/LGhassen/Scatterer/files/383051/settings.cfg.txt)
[buildID.txt](https://github.com/LGhassen/Scatterer/files/383052/buildID.txt)

**Comment by LGhassen** [comment]
Check your driver for any settings that override/force/disable anisotropic filtering, try changing them and see if anything works. I can't frankly comment on what happens with linux drivers. Also try changing the game quality settings and see if anything affects it.

**Comment by JoelleEmmily** [comment]
I've discovered that mesa, KSP, or Unity3d, does not has problems with openGL 3.0 and 3.3. The error is correct using 4.1.
