### ISSUE TITLE
Ghosting/Double Rendering Upside Down of terrain and geometry

### ISSUE THREAD

**Issue by Skezao** [LGhassen/Scatterer#180]
Hello, first time posting here so I apologize if I've done anything wrong.

Ever since I installed the scatterer mod (amazing mod btw), I've encountered an issue with the game, and only happens when Scatterer is running. Everything is like double rendering, I'm not really sure how to describe it but the screenshot will explain.

Let me know what files you need me to send so we can figure this out. 

Thank you and have a good day.

![ffffffffffffffffffffffffffffffff](https://user-images.githubusercontent.com/113313150/189549536-3e1a6e8d-a5fd-4aef-9ba4-6650bf5e0424.png)

**Comment by Skezao** [comment]
Nevermind, i'm a big goober, it was an issue with reshade, my bad.

**Comment by LGhassen** [comment]
No problem, tganks for reporting the cause you found.
