### ISSUE TITLE
planet scaledspace texture unloads sometimes when using kopernicus OnDemand loading

### ISSUE THREAD

**Issue by WhirligigGirl** [LGhassen/Scatterer#183]
This is an issue i've seen in several planet packs in several situations, and only ever when scatterer is installed and there is a scatterer atmosphere on that planet. sometimes when a texture is loading on demand (i.e., tabbing to a planet, going from surface to the map view), there will be a brief stutter (there usually is when dealing with ondemand loading) and the planet textures disappear.

I'm wondering if it could have something to do with adjustScaledTexture, because I believe it only applies to planets with that set to True. It doesn't seem to be reliably replicated. I thought it was a permanent problem that required a game restart, and maybe sometimes it is (i'm recalling instances of this bug from months ago as well as what i'm seeing now), but a scene change (going to the tracking station) seems to have fixed it just now.

Before the bug:
![image](https://user-images.githubusercontent.com/9667986/192162183-fd512bc6-5bff-44be-bcf5-1b2f1c1c2b08.png)

After the bug:
![image](https://user-images.githubusercontent.com/9667986/192162171-61159cca-447b-4bae-95ae-eec589f5dc29.png)

zip file containing KSP.log
[copy of KSP_log.zip](https://github.com/LGhassen/Scatterer/files/9641647/copy.of.KSP_log.zip)

**Comment by LGhassen** [comment]
Yep it's totally due to adjustScaledTexture, I'm well aware of it. Recent changes on the dev branch may have fixed it although I haven't tested with Kopernicus for a while. You can try this dll and see if it makes any change: https://www80.zippyshare.com/v/WfABq3zD/file.html

**Comment by LGhassen** [comment]
This should be fixed now on the latest version, don't hesistate to reopen if it still happens.
