### ISSUE TITLE
Land disappear (v1.8.1)

### ISSUE THREAD

**Issue by Skyfinder84** [LGhassen/Scatterer#186]
With or without any other mods, this happens:
https://preview.redd.it/wopiv7kjkdt91.png?width=2560&format=png&auto=webp&s=68d35eef85d643761c2f3485797d3353a5c6b066

Game version 1.8.1, RTX2080 ti, AMD 5950x, all graphic settings at higher level.

**Comment by LGhassen** [comment]
Check you are not running dx12, and post a log file.

**Comment by Skyfinder84** [comment]
How check it? Where? I gave a look in the wiki, nothing about it.

**Comment by LGhassen** [comment]
Google how to run ksp in dx12, usually people do it by adding parameters to the shortcut or im steam.

Also after your run the game attach your KSP.pog file here so I can check it.

**Comment by Skyfinder84** [comment]
I've add -force-d3d11 or force-d3d11, the bug persist. Now I'm using pretty well other mods, after a clean reinstall. I've tried to reinstall also scatterer too, as last mod, but even forcing DX11, same situation. Here the log:

[KSP.log](https://github.com/LGhassen/Scatterer/files/9785423/KSP.log)

**Comment by LGhassen** [comment]
You're using the newest scatterer with KSP 1.8, it clearly says the newest scatterer is only comaptible with 1.9+

**Comment by Skyfinder84** [comment]
Oh Jesus! I'm very sorry! :( Too many things to read and understand, I don't get this, sorry for the disturb 😅

**Comment by Skyfinder84** [comment]
Anyway, I give another look to the page of the project... where is written that the newest is compatible only with 1.9?... I looking now release and nothing is written...

**Comment by LGhassen** [comment]
Hmm It's written in the forum thread and spacedock. True that it isn't written on github.

**Comment by kipter19** [comment]
I had this exact issue, it can be fixed my going to the scatterer settings > select eve clouds tab > disable the checkbox that says something like "integrate with eve clouds" and restart the game
