### ISSUE TITLE
Invisible Ocean when ever I install the mod KSP 1.12.3 Mod V 3:v0838 according to CKAN

### ISSUE THREAD

**Issue by VirtualGaming1** [LGhassen/Scatterer#189]
So I have noticed that everytime I install Scatter. The water is invisible but it is still there like it did to #123 but try change the config and apply then restart the game and it is still there. Am I missing something or is there Known incompatibility that CKAN dose not have.

I am also using Galaxies Unbound A Stellar Odyssey also require Kopernicus (Just edited this part in just incase)
At the time I do not have Eve installed

![image](https://user-images.githubusercontent.com/20447403/199592875-10e5c65b-4788-40d8-83b5-5da07ab176b7.png)

Not sure but I think Scatter is not doing things right as well
![image](https://user-images.githubusercontent.com/20447403/199593153-07e5cca7-2b7b-4425-b8b7-bbb3f0c0cce3.png)

**Comment by VirtualGaming1** [comment]
After Few bit more testing. I have notice that It have not been loading right. even in the map veiw the lighting look like just base game.

**Comment by KSPFreak** [comment]
im not sure, but it might be something with kopernicus/galaxie unbound. i have the exact same issue, also GU installed and scatterer not loading properly. If i find a solution i´ll post her. Maybe devs can help?

**Comment by LGhassen** [comment]
@VirtualGaming1 please attach your log file (KSP.log file in ksp folder) after you run the game and get the issue

**Comment by KSPFreak** [comment]
since he didnt get back to you imma just submit my logs, as I have the exact same issue.
[KSP.log](https://github.com/LGhassen/Scatterer/files/10195698/KSP.log)
[Player.log](https://github.com/LGhassen/Scatterer/files/10195704/Player.log)

**Comment by Maxsumaxs** [comment]
I've recomend you to foloow this direction
Kerbal Space Program\GameData\ScattererAtmosphereCache
Just reinstall Scatter, and delete cache folder. 
After your scatter will work normally, but I can't guarantee that such a problem won't happen later

**Comment by LGhassen** [comment]
This is usually an install issue, check your log file and you should find a loading exception about missing atmo/ocean configs or something like that
