### ISSUE TITLE
White circle around Kerbin

### ISSUE THREAD

**Issue by Jool402** [LGhassen/Scatterer#192]
I am having an issue with scatterer version v0.0838 running in KSP v1.12.4. There is a white circle around Kerbin instead of scattered atmosphere.

![Capture d’écran 2022-12-14 091553](https://user-images.githubusercontent.com/100031374/207623477-bada208d-a9f7-4e11-89ad-c996caf718e9.jpg)

It also doesn't work for water either.

![Captura de pantalla 2022-12-14 093634](https://user-images.githubusercontent.com/100031374/207624273-84f08fd7-2e49-4d9c-855c-1858a90ac3bc.jpg)

My KSP.log file for debug.

[KSP.log](https://github.com/LGhassen/Scatterer/files/10228702/KSP.log)

And finally my GameData screenshot.

![Captura de pantalla 2022-12-14 093813](https://user-images.githubusercontent.com/100031374/207625276-c0277bf6-5c69-4557-b50b-af4357a56b57.jpg)

**Comment by LGhassen** [comment]
Try this https://github.com/LGhassen/Scatterer/issues/191?notification_referrer_id=NT_kwDOALbGH7M1MDQ5MDUzMTE2OjExOTc4Mjcx#issuecomment-1345268609

**Comment by LGhassen** [comment]
The log seems to be missing, there's only the first few li es.

 Can you install the latest scatterer, get in game, bring up the ui (alt +f11) hit delete atmo cache, check fast preview mode then press generate?

**Comment by kerbalwithbrokenscatterer** [comment]
I may have retrieved my log incorrectly, is this a full version? 
[KSP.log](https://github.com/LGhassen/Scatterer/files/10430065/KSP.log)

I can get as far as loading the latest version of scatterer and opening it's UI, but I can't the "delete atmo cache" or other settings you mention. Please let me know how to navigate that. 
![Screenshot 2023-01-16 160237](https://user-images.githubusercontent.com/122838874/212782779-f3f08a26-22cf-440e-9ed4-2783d5fb0337.png)

**Comment by AsturaPhoenix** [comment]
> The log seems to be missing, there's only the first few li es.
> 
> Can you install the latest scatterer, get in game, bring up the ui (alt +f11) hit delete atmo cache, check fast preview mode then press generate?

For me, this looks fine but then after leaving the flight the game crashes. I haven't tried `useLowResolutionAtmosphere = true` but I'll give that a shot later.

[Player.log](https://github.com/LGhassen/Scatterer/files/10611966/Player.log)

**Comment by LGhassen** [comment]
> > The log seems to be missing, there's only the first few li es.
> > Can you install the latest scatterer, get in game, bring up the ui (alt +f11) hit delete atmo cache, check fast preview mode then press generate?
> 
> For me, this looks fine but then after leaving the flight the game crashes. I haven't tried `useLowResolutionAtmosphere = true` but I'll give that a shot later.
> 
> [Player.log](https://github.com/LGhassen/Scatterer/files/10611966/Player.log)

That by itself is not a fix, it just enables it temporarily. useLowResolutionAtmosphere enables it permanently though so if the first one works for you the useLowResolutionAtmosphere should be a permanent fix.

**Comment by AsturaPhoenix** [comment]
Yep, so far so good, with the updated dll and Scatterer/config/config.cfg `Scatterer_config` / `useLowResolutionAtmosphere = true`, looks reasonable and didn't crash. Thanks!

**Comment by zenet228** [comment]
@LGhassen i have tried uselowresolutionatmosphere=true but it didn't work what should i do?

**Comment by LGhassen** [comment]
> @LGhassen i have tried uselowresolutionatmosphere=true but it didn't work what should i do?

Revert to versions 7xx

**Comment by zenet228** [comment]
dude i need excatly that ne version to make volumetric clouds work

**Comment by zenet228** [comment]
i nedd excatly that on version maybe there is another way to fix it?

**Comment by LGhassen** [comment]
Try the latest version (and clear cache), if it doesn't work find the windows setting to disable GPU timeouts
