### ISSUE TITLE
NRE spam with OPM

### ISSUE THREAD

**Issue by FDAUT** [LGhassen/Scatterer#193]
I am getting massive NRE spam with KSP 1.12.3, Scatterer 0.0838, and OPM 2.2.1. The spam seems to be related to Scatterer. Nothing exact to recreate it, just need to move from in-flight view, map view or tracking station and it will happen sooner or later within 5 mins. Everything seems to work fine I just get the spam every tick which seems to slow the game down in general. 

[KSP.log](https://github.com/LGhassen/Scatterer/files/10416464/KSP.log)
![Capture](https://user-images.githubusercontent.com/122657927/212448829-accbf9df-aeb1-4c18-b347-ad2240d7a687.JPG)

**Comment by LGhassen** [comment]
Try with the latest version
