### ISSUE TITLE
Freezes on title screen

### ISSUE THREAD

**Issue by AverageStardust** [LGhassen/Scatterer#194]
KSP: 1.12.4 Linux x86_64

Problem: Immediately freezes on the title screen

Mods installed:

Scatterer 0.0838

Reproduction steps:

Launch game though launcher or directly with the executable file.
Any graphics settings seem to work, I've tried the minimum and maximum presets from the launcher.
KSP keeps one thread at 100%, but does not crash.
I've waited minutes: much longer than my game takes to load.

Log: [pastebin](https://pastebin.com/14m5LYz3)

**Comment by AverageStardust** [comment]
I just checked with Scatterer 0.0835.
There is still a pause at the title screen, but it only last a few seconds.

**Comment by LGhassen** [comment]
So this works on 835 but not 838?

**Comment by AverageStardust** [comment]
This bug exists in 838 but not 835.

835 only has a small hiccup on the title screen, not exactly a issue. Scatterer has done this for as long as I've used it in both Windows, MacOS and Linux and on many different devices.

For all I know this hiccup has just gotten far far worse in 838. I've waited ridiculous long, and it hasnt subsided like in previous versions.

**Comment by BeFranke** [comment]
I have an issue I guess could be related:
Also on Linux (native version), my game freezes as soon as  I look at any body with an atmosphere in map view, for about 5 minutes. While freezing, my desktop environment gets very laggy and sound (e.g. from youtube videos) gets choppy, so I guess this is some very strong hardware utilization.
My main menu hangs shortly, but nothing I woudn't be used to from previous versions.

I have not tried yet with previous versions of scatterer.

System:
OS: Manjaro Linux x86_64 
Kernel: 5.15.93-1-MANJARO 
Shell: zsh 5.9 
Resolution: 1920x1080, 2560x1440 
DE: GNOME 43.2 
WM: Mutter 
CPU: Intel i7-8700K (12) @ 4.700GHz 
GPU: NVIDIA GeForce RTX 3070 Ti 
Memory: 3806MiB / 32042MiB 


[KSP.log](https://github.com/LGhassen/Scatterer/files/10795929/KSP.log) (Last lines are the freeze (focusing on eve), to which I reacted by killing the game after some fights with my laggy desktop environment)

**Comment by SurvivorBob** [comment]
Adding my findings here, as I'm experiencing a similar issue:

- Also on Linux (Ubuntu 22.04 LTS), KSP 1.12.3, Scatterer 838.
- NVIDIA RTX 2080 Super (8GB VRAM), AMD Ryzen 9 3950X, 64 GB RAM, no swap.
- Hard freeze for some time (tens of seconds to minutes) + 100% GPU utilization (in `nvidia-smi`) + extreme window manager latency **whenever Scatterer has to generate a new atmosphere** for a celestial body (instead of loading one from cache).
- After letting the atmosphere generation finish and produce a cache object, subsequent loads of the same celestial body take essentially negligible time (~1-2 seconds).

Example of log output before and after a hard freeze:
```
[PlanetariumCamera]: Focus: Iomena 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[OD] --> ScaledSpaceDemand.LoadTextures loading KcalbelohSystem/PluginData/Iomena_Scale.dds and KcalbelohSystem/PluginData/Iomena_Normal.dds 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Scatterer][Debug]  Atmosphere config found for: Iomena 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Scatterer][Info] No atmosphere cache for Iomena, generating new atmosphere 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

### ... hard freeze for significant duration while an atmosphere is generated ... ###

[Scatterer][Info] Atmo generation successful 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Releasing render texture that is set to be RenderTexture.active! 
(Filename:  Line: 926)

[Scatterer][Debug] Skynode initiated for Iomena 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Scatterer][Debug] Effects loaded for Iomena 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Kopernicus] No new objects this time. (Probability is 66%) 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

**Comment by LGhassen** [comment]
Closing this because it doesn't seem to be an actual freeze, just takes a while to generate on Linux.

I recommend not running the gimped OpenGL version anyway it runs worse in every way, do yourself a favor and run the game through Proton.
