### ISSUE TITLE
KSP 1.12.5 - At any altitude in the KSC view, the water is pixellated [minor but kindof annoying issue]

### ISSUE THREAD

**Issue by Gravelpoot** [LGhassen/Scatterer#195]
![20230204135927_1](https://user-images.githubusercontent.com/108036569/216746781-7c9e0234-f492-4744-a318-a824fb21b670.jpg)
Image 1: The minor but very irritating issue as stated.
![20230204140212_1](https://user-images.githubusercontent.com/108036569/216746849-9f8c230b-1e04-4e47-a7f8-d782b3b3e5e3.jpg)
Image 2: Issue persists in flight view.
![20230204140753_1](https://user-images.githubusercontent.com/108036569/216746981-44aa2564-47c8-4c4b-a397-3e2fe5ab8894.jpg)
Image 3: What settings do I change and how do I apply specific changes? Also the changes aren't kept after I close KSP. Help.

It is a minor but kindof annoying issue that I can't seem to fix and nobody else seems to have talked about. Help!

**Comment by LGhassen** [comment]
Seems like you have the stock ocean and scatterer ocean rendering at the same time, this was fixed so try latest version.
