### ISSUE TITLE
Gas Giants appear black with JNSQ and EVE

### ISSUE THREAD

**Issue by Thorimus** [LGhassen/Scatterer#196]
Hello,
There seems to be an incompatibility between the 0.08XX versions and EVE when used with JNSQ that causes gas giants to appear black. Unfortunately I haven't had the time to test without all my other mods, although the only other visual mod in the install is DistantObjectEnhancement. Hopefully the log file can still provide some clarity.

Reverting to 0.07XX versions of scatterer fixes the issue but introduces strange artifacting and other old bugs. Removing the EVE cloud layer via the in-game menu also seems to fix it.

[KSP.log](https://github.com/LGhassen/Scatterer/files/10912077/KSP.log)
![screenshot0](https://user-images.githubusercontent.com/23268966/223498368-37be99dd-8a9b-4817-bc16-5b39263596b6.png)
![screenshot1](https://user-images.githubusercontent.com/23268966/223498376-a8dfae75-aa4f-4bbd-a415-96784e1b36a6.png)

**Comment by Thorimus** [comment]
Alright, what do you mean by redo? Does a completely new config need to be written for JNSQ?

**Comment by LGhassen** [comment]
Yeah, probably someone else has already done it though, so look around or search the thread.

**Comment by Thorimus** [comment]
Alright, thanks for the help.
