### ISSUE TITLE
White aura on the dark side of Earth

### ISSUE THREAD

**Issue by kish0167** [LGhassen/Scatterer#198]
![image](https://user-images.githubusercontent.com/128732991/227305932-7f025cf9-f406-4ea2-aab1-d41f686d18c4.png)
Ksp 1.12.5 
windows 64

Mods:
Scatterer 0.0838, Eve-redux v1.11.7.1 - 09/09/2022, Kopernicus, KSRSS

Appears in the map/vessel view only on one half of the dark side.
[Player.log](https://github.com/LGhassen/Scatterer/files/11054474/Player.log)

**Comment by LGhassen** [comment]
No reproduction steps, played with KSRSS and didn't get this.
