### ISSUE TITLE
Planet Radiation Belts Vibrating/Shuddering

### ISSUE THREAD

**Issue by Kebaliscious** [LGhassen/Scatterer#201]
Whenever I install Scatterer with Kerbalism the Radiation belts shake uncontrollably. I did a fresh build of KSP and only installing Kerbalism the problem does not happen. As soon as I install Scatterer the problem starts.

Any ideas on how to fix?

[Video Link Here](https://www.youtube.com/watch?v=Tyt69PfTRp4)

**Comment by LGhassen** [comment]
Yeah try disabling Temporal Anti Aliasing in the scatterer menu (blue orb icon in the ksc screen).

**Comment by Kebaliscious** [comment]
Thankyou so much 😍😍. I could not figure out how to get rid of it.
