### ISSUE TITLE
Scatterer always crash issue

### ISSUE THREAD

**Issue by MifanInSalt** [LGhassen/Scatterer#204]
When I tried to install Scatterer,every times after my KSP was complete loading and get into the main menu,the KSP will "stuck" and "The application has stopped running" and then crash,after I checked the Scatterer will cause the KSP crash,I didn't do nothing,just start the game and loading. My game version is 1.12.5(Build 3169),Scatterer version is 0.838. It always crash whether no any Mods except Scatterer and it's config or with RSSVE.
I had checked KSP.log but it didn't give me any useful information even a error message
KSP.log is below
[KSP.log](https://github.com/LGhassen/Scatterer/files/12577145/KSP.log)
*I am not particularly familiar with Github, please excuse me pls

**Comment by LGhassen** [comment]
This is due to using intel integrated graphics. I don't have a solution for you  right now apart from trying older versions

**Comment by MifanInSalt** [comment]
Thanks,also,how old version should I install?

**Comment by LGhassen** [comment]
Probably anything before 8.xxx

**Comment by MifanInSalt** [comment]
OK,thanks

**Comment by zenet228** [comment]
what do you mean 8.xxx? i also have intel intergrated graphics

**Comment by zenet228** [comment]
> Probably anything before 8.xxx

wha do you mean?

**Comment by MifanInSalt** [comment]
> what do you mean 8.xxx? i also have intel intergrated graphics

the version earlier than 0.08x,so you can use the 0.0772(The latest version before 0.08x)

**Comment by MifanInSalt** [comment]
> what do you mean 8.xxx? i also have intel intergrated graphics

And I had try 0.772 is able to run on Intel intergrated graphics
