### ISSUE TITLE
Separate open- and closed-source shader asset bundles?

### ISSUE THREAD

**Issue by videopilot** [LGhassen/Scatterer#205]
I have some tweaked ocean and atmo shaders from an older install of scatterer, but it is not clear how to use them on the volumetric clouds version.

Would it be possible to make separate bundles for your closed-source cloud shaders and those that are still the same as the older open-source shaders so those can be changed?

Or at least explain how to "replace" shaders as the readme here suggests?

**Comment by LGhassen** [comment]
Won't work, cloud shaders "include" the atmo code and when they are compiled everything is compiled into the shader files, it's not like CPU code that can be dynamically linked.
