### ISSUE TITLE
Scatterer Ocean ksp visual bug

### ISSUE THREAD

**Issue by Ac-ed** [LGhassen/Scatterer#206]
KSP: 1.12
Problem: Ocean visual glitch with Scatterer
Mods installed: Scatterer v0.0838
Reproduction steps:
build rocket
launch rocket
once in air, weird shadow appears in ocean and gets bigger and bigger over time
Screenshot: https://imgur.com/a/UCG1c84

**Comment by LGhassen** [comment]
Just disable godrays, that's the craft's shadow. Technically that's a really effect but the shadowmaps being imprecise and causing the craft shadow to balloon make it worse.
