### ISSUE TITLE
Silvery Sheen on Kerbin's Dark Side When Viewed from the Mun or Minmus

### ISSUE THREAD

**Issue by CouchMaster615** [LGhassen/Scatterer#208]
KSP: 1.12.5 Windows 64bit
Problem: When I land on the light side of either the Mun or Minmus and view Kerbin directly or in the map, the planet's dark side appears to be faintly illuminated as in the screenshots. Kerbin's dark side appears normal in orbit and from either moon's dark side. At first I thought it was PlanetShine causing the issue because it seems as though the light side of the moon is being reflected by Kerbin's dark side, but Scatterer is the only mod that causes this issue for me.

![20231114181518_1](https://github.com/LGhassen/Scatterer/assets/150942421/e0f92b7d-2563-4186-946b-481b51dacfdb)
![20231114181545_1](https://github.com/LGhassen/Scatterer/assets/150942421/1bd91c34-6a1d-4f40-852b-3d7b96779f6f)

In the screenshots I have EVE Redux, Parallax 2.0 and Distant Object Enhancement active among other mods, but so long as Scatterer is installed the effect remains for me regardless of any other mods I have.

Mods installed:

Scatterer 0.0838

Reproduction steps:

Get a vessel into space near either Minmus or the Mun.
As the vessel approaches the light side of the given moon the visual effect slowly fades into view on Kerbin's dark side, with it being most noticeable on the surface.
This happens with a clean install of KSP with only Scatterer installed, previous versions of Scatterer, and any combination of other mods and Scatterer.

I have had no other problems with Scatterer. This one little issue has been driving me insane.

Log:

[Player.log](https://www.dropbox.com/t/YLGyW6qqu8VG3MLo)

**Comment by LGhassen** [comment]
Not a scatterer bug, caused by a stock shader. Remove scatterer and it'll still happen. Sorry I already investigated it many times.
