### ISSUE TITLE
Oceans are missing

### ISSUE THREAD

**Issue by Magnus1001** [LGhassen/Scatterer#209]
The surface of the water is not visible, only the ocean floor is.
![screenshot1](https://github.com/LGhassen/Scatterer/assets/123913125/060f5503-b0c7-4d08-be1c-bac55476f8ae)

**Comment by 1APOPHIS1** [comment]
Same here, but my skies are black alongside this

**Comment by LazyFluf** [comment]
Currently experiencing the same issue

**Comment by LGhassen** [comment]
This is usually an install issue, check your logs for errors and you'll find a loading exception

**Comment by LazyFluf** [comment]
Can confirm that it was an install issue.  Searched for the loading exception and I could find no obvious error.  Not saying there wasn't one, I just didn't find one if there was.  I noticed that the AtmosphereCache folder wasn't created, and that said atmosphere was *also* missing.  Added Scatterer to a new install and there were no issues.
