### ISSUE TITLE
Value rounding

### ISSUE THREAD

**Issue by PhineasFreak** [LGhassen/Scatterer#21]
This is a small "feature" request (if you can call it like that): when editing and saving the atmosphere parameters, the actual values are not exact but they present some rounding issues.

Example:

```
experimentalAtmoScale = 0.800000012
mapExtinctionMultiplier = 2
mapExtinctionTint = 0.400000006
mapSkyExtinctionRimFade = 0.25
```

Note the values of the "experimentalAtmoScale" (was 0.4) & the "mapExtinctionTint" (was 0.8) parameters.

**Comment by LGhassen** [comment]
This is always like this with the configNode system, I noticed it also happens with saved crafts in the editor. Not sure what's causing it.
Is this important? Does it really make a difference?

**Comment by PhineasFreak** [comment]
No, i just noticed it because of a git diff, it was showing a lot more additions/deletions than i remember i had made.

Seems like it is an inherent problem with KSP itself then. Feel free to close this issue!
