### ISSUE TITLE
flickering blue dots on earth

### ISSUE THREAD

**Issue by Kejkub** [LGhassen/Scatterer#210]
I'm dealing with a very irritating bug where Earth textures are flickering with little blue dots (as shown in the example in the link). any help ?

https://imgur.com/a/byc6LLb

**Comment by LGhassen** [comment]
I believe that's "lightning" in one of the visual packs. Look for cloud layers in EVE configs named "lightning" or something like that. If this doesn't fix your issue reopen the issue but include your list of mods and a KSP.log file.
