### ISSUE TITLE
There are no eclipses on satellites

### ISSUE THREAD

**Issue by timns-wt** [LGhassen/Scatterer#211]
There are no eclipses on satellites in the form a map view or at high altitude. If you are at a low altitude (less than about 100 km), then everything works fine, but the further away the satellite becomes brighter. The rocket remains dark and everything looks strange. 
![screenshot16](https://github.com/LGhassen/Scatterer/assets/172169168/fe8e0dac-35e1-4d7a-9547-cd12e206febe)
![screenshot13](https://github.com/LGhassen/Scatterer/assets/172169168/1d755723-ac8b-4e14-b4c1-fb784d5da31e)
![screenshot12-1](https://github.com/LGhassen/Scatterer/assets/172169168/bdc56a3e-cf7e-4b29-88cb-5e9689f39bc8)
![screenshot3-1](https://github.com/LGhassen/Scatterer/assets/172169168/3e174861-c216-4e2d-9280-27d5deda536c)
![screenshot2-1](https://github.com/LGhassen/Scatterer/assets/172169168/a17d8ed8-ca9f-41dd-aab7-54def783cb73)

On satellites with an atmosphere, everything works fine and shadow visible at any distance and from map view.

**Comment by LGhassen** [comment]
Yes, scatterer doesn't do eclipses on bodies without atmospheres, it's a mod for making atmospheres. Use EVE-Redux for eclipses on regular bodies.
