### ISSUE TITLE
Black Sky on multiple planets

### ISSUE THREAD

**Issue by 1APOPHIS1** [LGhassen/Scatterer#213]
KSP: 1.12.5

Problem: Skybox on certain planets in completely black, everything else works just fine.

Mods installed: (its probably GPO because its outdated)
Its refusing to let me paste the modlist
Here are my major ones
KSPIE
Other Worlds
SNW
EVE
Scatterer

Reproduction: Load KSP, enter VAB. Sky is black, as if on an airless planet. Clouds and everything still there.

Log: Pastebin and dropbox are not letting me paste it or save it. They either crash or just wont work

Solution: GPO is incompatible I know that, Im not going to revert my ksp version or any of that. Could someone please just tell me how to either remove the black skies on these worlds manually or change the configs or whatever. Deleting scatterer fixes the black sky but it makes the game lag considerably and breaks the terrain. Someone please just tell me what files I have to remove or edit.

**Comment by LGhassen** [comment]
Not enough info to go on, no logs no screenshots. Likely an install issue
