### ISSUE TITLE
(most) Stock planets aren't updated

### ISSUE THREAD

**Issue by wubblebubbleball** [LGhassen/Scatterer#218]
This only happened recently after I uninstalled Infinite Discoveries, which is really weird. Eve, Kerbin, Duna, Jool, and Laythe now have the regular stock oceans and atmospheres but modded planets have the Scatterer oceans and even update when I tick on water reflections.

**Comment by wubblebubbleball** [comment]
It also for some reason doesn't apply to anything related to OPM, but here's some screenshots that I forgot to add.

![20240720185112_1](https://github.com/user-attachments/assets/e8de16f1-6ab2-4984-a069-4c1f9026d016)
Tekto

![20240720185251_1](https://github.com/user-attachments/assets/7dc87547-9bf8-440e-ab45-b712fc270adb)
![20240720185257_1](https://github.com/user-attachments/assets/bc7b991d-0c7c-4c18-adfa-d9b7b2ebda08)

Aeneas (StrangeNewWorlds)... works to an extent

![20240720185332_1](https://github.com/user-attachments/assets/b24aaa97-24c6-461e-af25-bac6bdecdbf1)
Oceanus (StrangeNewWorlds)

**Comment by LGhassen** [comment]
This is likely an install issue, likely StockScattererConfigs has been deleted. If you followed install instructions precisely then this is an issue with Infinite Discoveries' install procedure

**Comment by wubblebubbleball** [comment]
But the StockScattererConfigs folder isn't deleted? I've even tried redownloading the mod and nothing has changed.

**Comment by LGhassen** [comment]
Bring it up to Inifinite Discoveries dev
