### ISSUE TITLE
Planetary bodies seem to become completely white when on low orbit?

### ISSUE THREAD

**Issue by SimplyTadpole** [LGhassen/Scatterer#219]
Hello!

I've started a new playthrough of KSP using new graphics mods, and I ran into the issue where every planetary body that I reach low orbit around becomes blindingly white (to the point some people I showed screenshots of the issue to assumed I was orbiting the sun). I... think it's best if I show pictures:

![image](https://github.com/user-attachments/assets/03c2c567-e817-45e5-acfe-bef01adcdfbb)

![image](https://github.com/user-attachments/assets/618d20f7-10c9-41a9-87d0-2e870a5752e0)

The pictures are of a probe in low orbit around Kerbin, and a probe doing a Mün flyby (seen on the right side, glowing bright white) respectively.

I initially assumed this issue might've had to do with Spectra or Parallax, but removing either or both of them did not solve the problem - as a last-ditch effort, I tried removing Scatterer, and that ended up doing the trick.

I assume this might have to do with the fact that I'm playing on Linux and the mod might not be dealing with OpenGL very well, but I tried looking through the Issues page for anyone having a similar problem to me and I found nothing of the sort, so I'm not sure. There is the "white sky" glitch, but it's not exactly what I'm dealing with - the atmosphere renders just fine when I'm in the planet's surface, looking at it in map view or even in high orbit around it (you can see Kerbin looks just fine in the second picture), it's *specifically* in low orbit that the issue crops up for some reason.

I've tried deleting and reinstalling Scatterer several times (and as I mentioned earlier, tried using it without Spectra or EVE), but nothing made the problem go away.

**Comment by LGhassen** [comment]
Can't help you without your KSP.log file.

**Comment by SimplyTadpole** [comment]
My mistake... it turns out it really was because I had an outdated version of those mods - I installed them last year and had forgotten that it was never updated. Updating to the latest versions made the issue go away.

Thanks for your patience, and I apologize for taking your time.
