### ISSUE TITLE
Move config cfg files to PluginData

### ISSUE THREAD

**Issue by RealKolago** [LGhassen/Scatterer#22]
ModuleManger builds up a new cache file on every start when changing config cfg files are not stored in a PluginData folder.

GameData\scatterer\config\Planets\Kerbin\atmo.cfg
GameData\scatterer\config\config.cfg

->

GameData\scatterer\PluginData\Planets\Kerbin\atmo.cfg
GameData\scatterer\PluginData\config.cfg

**Comment by LGhassen** [comment]
There is already an issue for this.
