### ISSUE TITLE
Scatterer refuses to load effects

### ISSUE THREAD

**Issue by IapetusAP332** [LGhassen/Scatterer#220]
For some weird reason, Scatterer's effects just.. refuse to load. At all.
![screenshot18](https://github.com/user-attachments/assets/59a02bd6-861e-49ba-ad96-276857e8ef82)
As seen on Kerbin in the picture, Scatterer refuses to display it's nice atmospheric shaders. This in turn causes other graphical mods to break in the visual department. This is also complimented by the fact that in KSC view the oceanic shaders don't appear.
![2024-10-11](https://github.com/user-attachments/assets/d3183ee2-8ff1-495e-97ab-0fc87a7a48e3)
Here's all the mods currently in my install. I have reinstalled Scatterer multiple times through CKAN and the problem still persists.

**Comment by IapetusAP332** [comment]
Here's the logs if you need them. https://www.dropbox.com/scl/fi/qu6ws1fzvedzjkmyouw6h/Logs-Kopernicus.zip?rlkey=za5je7bjo0b10khosr56mamu4&st=dp7zbsrz&dl=0

**Comment by IapetusAP332** [comment]
Small update: manual install didn't work.

**Comment by LGhassen** [comment]
According to the logs, scatterer doesn't have configs for Kerbin and instead has configs for these planets:

`[LOG 17:22:47.112] [Scatterer][Debug] Finding ScattererCelestialBody name: Aeneas. TransformName: Aeneas
[LOG 17:22:47.124] [Scatterer][Debug] Found ScattererCelestialBody: Aeneas, actual ingame name: Aeneas
[LOG 17:22:47.129] [Scatterer][Debug] Finding ScattererCelestialBody name: Usir. TransformName: Usir
[LOG 17:22:47.129] [Scatterer][Debug] Found ScattererCelestialBody: Usir, actual ingame name: Usir
[LOG 17:22:47.129] [Scatterer][Debug] Finding ScattererCelestialBody name: Oceanus. TransformName: Oceanus
[LOG 17:22:47.129] [Scatterer][Debug] Found ScattererCelestialBody: Oceanus, actual ingame name: Oceanus
[LOG 17:22:47.130] [Scatterer][Debug] Finding ScattererCelestialBody name: Denali. TransformName: Denali
[LOG 17:22:47.130] [Scatterer][Debug] Found ScattererCelestialBody: Denali, actual ingame name: Denali
[LOG 17:22:47.131] [Scatterer][Debug] Finding ScattererCelestialBody name: Poseidon. TransformName: Poseidon
[LOG 17:22:47.131] [Scatterer][Debug] Found ScattererCelestialBody: Poseidon, actual ingame name: Poseidon
[LOG 17:22:47.131] [Scatterer][Debug] Finding ScattererCelestialBody name: Vetinghier. TransformName: Vetinghier
[LOG 17:22:47.131] [Scatterer][Debug] Found ScattererCelestialBody: Vetinghier, actual ingame name: Vetinghier
[LOG 17:22:47.132] [Scatterer][Debug] Finding ScattererCelestialBody name: Arkhalo. TransformName: Arkhalo
[LOG 17:22:47.132] [Scatterer][Debug] Found ScattererCelestialBody: Arkhalo, actual ingame name: Arkhalo
[LOG 17:22:47.132] [Scatterer][Debug] Finding ScattererCelestialBody name: Hreveldor. TransformName: Hreveldor
[LOG 17:22:47.133] [Scatterer][Debug] Found ScattererCelestialBody: Hreveldor, actual ingame name: Hreveldor
[LOG 17:22:47.133] [Scatterer][Debug] Finding ScattererCelestialBody name: Kisa. TransformName: Kisa
[LOG 17:22:47.133] [Scatterer][Debug] Found ScattererCelestialBody: Kisa, actual ingame name: Kisa
[LOG 17:22:47.133] [Scatterer][Debug] Finding ScattererCelestialBody name: Gyro. TransformName: Gyro
[LOG 17:22:47.133] [Scatterer][Debug] Found ScattererCelestialBody: Gyro, actual ingame name: Gyro
[LOG 17:22:47.133] [Scatterer][Debug] Finding ScattererCelestialBody name: Boreal. TransformName: Boreal
[LOG 17:22:47.133] [Scatterer][Debug] Found ScattererCelestialBody: Boreal, actual ingame name: Boreal
[LOG 17:22:47.133] [Scatterer][Debug] Finding ScattererCelestialBody name: Mephitis. TransformName: Mephitis
[LOG 17:22:47.134] [Scatterer][Debug] Found ScattererCelestialBody: Mephitis, actual ingame name: Mephitis
[LOG 17:22:47.134] [Scatterer][Debug] Finding ScattererCelestialBody name: Malodor. TransformName: Malodor
[LOG 17:22:47.134] [Scatterer][Debug] Found ScattererCelestialBody: Malodor, actual ingame name: Malodor`

This looks like a config issue, check your configs, check the install instructions of the planet packs you're using and make sure they aren't outdated. I'm gonna close this issue, feel free to reopen it if there's really an issue with scatterer.

**Comment by IapetusAP332** [comment]
I've installed **everything** correctly via CKAN and triple-checked the configs. Kerbin's atmo.cfg and ocean.cfg are working perfectly well.

**Comment by LGhassen** [comment]
You say working perfectly but they are not working in your screenshot and not listed in the configs above. Recheck your configs or report them to those who provide said configs, this is a config issue not a plugin issue.

**Comment by IapetusAP332** [comment]
Here's the proof that the default configs of Kerbin were not tampered with.

1. (ATMOSPHERE) Scatterer_atmosphere
{
	Atmo
	{
		name = Kerbin
		atmosphereStartRadiusScale = 1
		HR = 3.83999991
		HM = 1
		m_betaR = 0.0153407799,0.0357074998,0.0875488967
		BETA_MSca = 0.0121406196,0.0121406196,0.0121406196
		m_mieG = 0.850000024
		ozoneAbsorption = 0.000493593689,0.00142889097,6.45468826E-05
		ozoneHeight = 20
		ozoneFalloff = 12
		useOzone = True
		averageGroundReflectance = 0.100000001
		multipleScattering = True
		godrayStrength = 0.699999988
		flattenScaledSpaceMesh = 0.600000024
		rimBlend = 20
		rimpower = 600
		specR = 80
		specG = 72
		specB = 65
		shininess = 75
		noonSunlightExtinctionStrength = 1
		cloudColorMultiplier = 3
		cloudScatteringMultiplier = 0.200000003
		cloudSkyIrradianceMultiplier = 0.0500000007
		volumetricsColorMultiplier = 1
		EVEIntegration_preserveCloudColors = False
		adjustScaledTexture = True
		scaledLandBrightnessAdjust = 1.32000005
		scaledLandContrastAdjust = 1.79999995
		scaledLandSaturationAdjust = 1.29999995
		scaledOceanBrightnessAdjust = 0.839999974
		scaledOceanContrastAdjust = 1
		scaledOceanSaturationAdjust = 1
		configPoints
		{
			Item
			{
				altitude = 0
				skyExposure = 0.200000003
				skyAlpha = 1
				skyExtinctionTint = 1
				scatteringExposure = 0.200000003
				extinctionThickness = 1
				postProcessAlpha = 1
				postProcessDepth = 0
				extinctionTint = 1
			}
		}
	}
}

2. (OCEAN) Scatterer_ocean
{
	Ocean
	{
		name = Kerbin
		AMP = 1
		m_windSpeed = 7
		m_omega = 0.839999974
		m_gravity = 9.81000042
		maxWaveInteractionShipAltitude = 500
		m_whiteCapStr = 0.469999999
		shoreFoam = 1
		m_farWhiteCapStr = 0.469999999
		m_oceanUpwellingColor = 0.0599999987,0.0599999987,0.0599999987
		m_UnderwaterColor = 0.100000001,0.75,0.800000012
		offScreenVertexStretch = 1.25
		alphaRadius = 1000
		transparencyDepth = 100
		darknessDepth = 800
		refractionIndex = 1.33000004
		skyReflectionStrength = 1
		causticsTexturePath = StockScattererConfigs/Planets/Caustics.png
		causticsLayer1Scale = 0.200000003,0.200000003
		causticsLayer1Speed = 0.0612000003,-0.151199996
		causticsLayer2Scale = 0.277099997,0.267100006
		causticsLayer2Speed = -0.0748699978,0.174869999
		causticsMultiply = 1
		causticsUnderwaterLightBoost = 2
		causticsMinBrightness = 0.5
		causticsBlurDepth = 200
		lightRaysStrength = 1
	}
}

**Comment by LGhassen** [comment]
That doesn't matter, you have other configs overriding/patching them via ModuleManager, here or in the planetslist file

**Comment by IapetusAP332** [comment]
I checked through every config and nothing was wrong.

**Comment by IapetusAP332** [comment]
i'm going to try a full reinstall of KSP

**Comment by IapetusAP332** [comment]
and it didn't work at all

**Comment by IapetusAP332** [comment]
and it turns out this also affects all my other mods except SNW like how the hell did this happen everything was working perfectly and then it just suddenly turned

**Comment by IapetusAP332** [comment]
SOMEHOW scatterer just doesn't load despite having shrunk my mods to around 35.
![2024-10-19 (1)](https://github.com/user-attachments/assets/b235742f-6abf-4205-96f3-4963b1f1dcc5)
i don't even know how this happened

**Comment by LGhassen** [comment]
Look man, just reinstall without mods like SNW, OPM, whatever and work your way up from a working stock install

**Comment by IapetusAP332** [comment]
seems to work perfectly with only eve and scatterer

**Comment by IapetusAP332** [comment]
looks like SNW is the troublemaker, i'll try and let it's creator know when forums are revived
