### ISSUE TITLE
Null Reference Exceptions Spamming log during debug

### ISSUE THREAD

**Issue by gomker** [LGhassen/Scatterer#24]
I was trying to debug another issue with one of my mods however, when running debug mode Scatter spams the logs with null reference exceptions

Sample

     [EXC 12:27:01.691] NullReferenceException: Object reference not set to an instance of an object
	scatterer.Manager.getDirectionToSun ()
	scatterer.SkyNode.InitPostprocessMaterial (UnityEngine.Material mat)
	scatterer.SkyNode.Start ()
	scatterer.Manager.Awake ()
	scatterer.Core.Update ()

Here is a log - https://www.dropbox.com/s/1t2a99ikn96iems/Scatterer.zip?dl=0

Testing on a build from your latest changes from my fork.

Regards,

**Comment by LGhassen** [comment]
Add the line "mainSunCelestialBody = Sun" to all your planets in the planetsList.cfg file.

This was added to allow mods with multiple solar systems to specify which planet receives light from which sun, instead of all using the same sun.

**Comment by ChristopherFunk** [comment]
I'm getting this after adding the `mainSunCelestialBody = Sun`, however I have the [Outer Planets Mod](http://forum.kerbalspaceprogram.com/index.php?/topic/93999-121-outer-planets-mod-21-biome-overhaul-more-biomes-more-interesting-names-better-looking-etc-17-nov/) installed as well. Those planets don't show up in the `planetsList.cfg` file. Does anyone know how to fix that as well? Or is this another issue with that mod completely?

**Comment by LGhassen** [comment]
That means those planets don't have scatterer configs, in which case effects don't run on them and it isn't an issue.
