### ISSUE TITLE
"Integrate effects with EVE clouds" option inconsistent with config file

### ISSUE THREAD

**Issue by WazWaz** [LGhassen/Scatterer#25]
Even though the config file has:

integrateWithEVEClouds = True

The option in the start-up dialog always shows the value turned off.

If you don't set it every time, it reverts to False on the next restart.

**Comment by LGhassen** [comment]
Are there any specific conditions for this happening? I don't seem to have it.

**Comment by WazWaz** [comment]
Ugh, sorry, it seems PoodsOPMVO forces it off. I'll take it up with Poodmund.
