### ISSUE TITLE
[Bug] usesCloudIntegration parameter not applying

### ISSUE THREAD

**Issue by PhineasFreak** [LGhassen/Scatterer#26]
Tested this with the aim to keep the EVE cloud integration feature only for the Earth but it seems that it is overriden by the global **integrateWithEVEClouds** parameter.

* Set the **integrateWithEVEClouds** parameter to **True**.
* Added the **usesCloudIntegration** to all applicable bodies (that have Scatterer entries).
* Set the **usesCloudIntegration** parameter to read **False** for every body apart from Earth.

But the final result was that, for the bodies that should have this feature disabled, it was enabled anyway.

**Comment by LGhassen** [comment]
where did you add usesCloudIntegration?

**Comment by PhineasFreak** [comment]
In the my **Scatterer_planetsList** config, under the **Item** node that specifies the basic Scatterer parameters for the bodies.

**Comment by LGhassen** [comment]
Which version is this on? I tested it yesterday and it was working

**Comment by PhineasFreak** [comment]
Oh shoot...forget it. For some reason i copy & pasted an older dev version of Scatterer.

**Comment by LGhassen** [comment]
Issue closed then?

**Comment by PhineasFreak** [comment]
For that one, maybe, yes. Should i make a new one for the config load problem (or is it my stupidity that also breaks it)?

**Comment by LGhassen** [comment]
Sorry, I didn't see the edit.

Are you sure you have the correct shader files here? Is everything the same apart from RSS being installed?

**Comment by PhineasFreak** [comment]
Something is really going on here. I feel i have to apologize, as i am probably wasting your time with these "bug reports". I'll try to write a clean timeline of my Scatterer dev build testing.

I backtracked a little and started testing every dev assembly from the https://github.com/LGhassen/Scatterer/commit/4435a1ae140e9f11182b3418fd47ee76d890d20e (featureless spheres) up to https://github.com/LGhassen/Scatterer/commit/824aa7edbd7f824740f9668ed05eb1f39709e64e (latest confignode fix):

* https://github.com/LGhassen/Scatterer/commit/4435a1ae140e9f11182b3418fd47ee76d890d20e: everything works perfectly, although the featureless spheres issue still exist for DX11/OpenGL.
* https://github.com/LGhassen/Scatterer/commit/c7d076cdb4e6f6f281eb33abc7b365f6992ba70d: everything works perfectly.
* https://github.com/LGhassen/Scatterer/commit/8718f61876ef5db4ac3f8a08a98fe74d4bb86bab: some problems with the overall appearance, bodies with heavy cloud coverage (Venus, Titan) turn into featureless spheres (exactly the same appearance as the DX11/OpenGL issue). Enabling the cloud integration for these bodies fixes it. Does not occur on bodies with little or no EVE clouds.

The **drawAtmoOnTopOfClouds** option is enabled for the above tests. If i disable this option then these two bodies turn into completely black spheres. On another note, the more i drop the alpha layer value of the EVE clouds from **255** the less black the body appears - enabling or disabling the **EVEIntegration_preserveCloudColors** option does not change something).

* https://github.com/LGhassen/Scatterer/commit/b137d5c836328ba4a87b30c2ef454e412df23de3: works as expected, ocean configs load OK but both atmo and ocean configs are saved with a mix of the old and new confignode formats (new configs are appended at the end of the existing configs):

```
Scatterer_atmosphere
{
	Earth
	{
		name = Earth
		.
		.
		.
	}
}
```

And

```
Scatterer_ocean
{
	Earth
	{
		name = Earth
		.
		.
		.
	}
}
```

* https://github.com/LGhassen/Scatterer/commit/b69894664cc0e1de0f77d5d700851b77721efe4b: this almost fixes the confignode loading. The Atmo nodes are still saved as **Scatterer_atmosphere/Earth/name = Earth** instead of **Scatterer_atmosphere/Atmo/name = Earth** (also occurs with the previous build). The Ocean nodes are saved correctly but they are missing the **name = Earth** parameter. It does not happen in stock KSP so it is limited to only RSS (i store my Scatterer textures under RSSVE/Assets/ScatterTextures and the Scatterer configs under RSSVE/Scatterer_Configs - maybe it gets confused by the path difference somehow?)
* https://github.com/LGhassen/Scatterer/commit/824aa7edbd7f824740f9668ed05eb1f39709e64e: Ocean nodes are fixed.

I am at a loss. And i will understand completelt if you don't want to continue allowing me to post... almost nonsense.

**Comment by LGhassen** [comment]
The only commit you need to test with is 824aa7e since it fixes issues with the previous commits.
You don't need to do any backtracking.
Is everything working correctly in 824aa7e?

**Comment by PhineasFreak** [comment]
Yes, after disabling the EVE cloud integration everything works as expected.

**Comment by LGhassen** [comment]
And with EVE integration?

**Comment by PhineasFreak** [comment]
With the EVE integration enabled i get the following results:

* **usesCloudIntegration = True**, **drawAtmoOnTopOfClouds = True**: The body Scatterer shading is correct, everything works perfectly (**note 1**).

* **usesCloudIntegration = True**, **drawAtmoOnTopOfClouds = False**: The body Scatterer shading is correct, everything works perfectly (**note 1**).

* **usesCloudIntegration = False**, **drawAtmoOnTopOfClouds = True**: Venus and Titan (heavy cloud coverage bodies) turn into featureless spheres. The EVE cloud layer textures for them appear completely black. Reducing the alpha channel value down from 255 turns the layers more transparent (**note 2**). The Scatterer shading for the rest of the bodies is almost non-existent (like if Scatterer only worked for the planet rims instead of the complete body).

* **usesCloudIntegration = False**, **drawAtmoOnTopOfClouds = False**: Venus and Titan (heavy cloud coverage bodies) turn into completely black spheres (same problem as the above but Scatterer does not hide the EVE layer now).

So, it seems that some options cannot be used with others. But that is a problem, since not all bodies can be made to look as expected if the cloud integration is enabled.

**Note 1:** In this mode Jupiter and Titan look...bad, very bad. So, i usually avoid enabling the cloud integration for them.
**Note 2:** This is just a test. Decreasing the alpha channel value is not considered as an option, since the underlying planet surface will become visible.

**Comment by LGhassen** [comment]
The cloud integration can now be used selectively for some bodies to get around this.

However, for the black spheres and the other issues I would need to have your config files or at least instructions on how to replicate your RSS install.

**Comment by PhineasFreak** [comment]
All the latest (dev) configs are uploaded to the KSP 1.3 branch of RSSVE. It is a self-contained package so you only need the very basic RSS install (RSS, RSS Textures and MFI) plus EVE and Scatterer: https://github.com/PhineasFreak/RSSVE/tree/KSP-1.3-Update

* The file **RSSVE_Scatterer_Global_Config** contains the **drawAtmoOnTopOfClouds** switch.
* The file **RSSVE_Scatterer_Planetlist_Config** contains the **usesCloudIntegration** switch.

It is very possible that the actual problem resides in either the way the Scatterer textures are created ot the Scatterer configs are set up. So...be gentle with me!

**Comment by LGhassen** [comment]
I will do it again, but once I update to 1.3, at the moment I'm still on 1.2.2 and using 1.3 might cause additional issues on top of existing ones.

**Comment by PhineasFreak** [comment]
Update: disregard the latest request of mine it is not required.
