### ISSUE TITLE
Mark compatible with 1.3

### ISSUE THREAD

**Issue by dpeters19** [LGhassen/Scatterer#27]
I love this mod, but I'd love it if it was available via CKAN with KSP 1.3 installed.
Could you mark it as working with 1.3?

**Comment by dpeters19** [comment]
On second thought, please don't.
There's still some bugs.

![kerbal space program 6_18_2017 5_10_39 pm](https://user-images.githubusercontent.com/18580297/27265368-4ef343d0-5449-11e7-9bbf-4cd18c4c1252.png)

**Comment by LGhassen** [comment]
It's not yet compatible with 1.3
