### ISSUE TITLE
alternate SQRT-Fix for Halo stopped working

### ISSUE THREAD

**Issue by Epoxid2** [LGhassen/Scatterer#29]
The alternate sqrt-option for fixing the halo seems to have stopped working for OS X users. There is nothing extraordinary I could find in the logs, but I have made the following tests on KSP 1.3.1:

- 320b (1st download link on SpaceDock): Sqrt-fix not working, always halo
- 315 preview (2nd download from top on SpaceDock): Halo is always there, fix is not doing anything on or off
- 275 preview (3rd download from top on SpaceDock): Fix Works: Halo is gone with alternate sqrt "off". This is the latest version where I can remove the halo using the sqrt-option.

I am using a MacBook Pro Retina from mid 2015, 2.8 Ghz Core i7 on macOS Sierra 10.12.6. This machine has two GPUs: Intel Iris Pro 1536 MB and AMD Radeon R9 M370X

**Comment by LGhassen** [comment]
Can you check this is fixed on the newest version (v0.0324)? The alternate SQRT-Fix is now gone from main menu and shouldn't be needed anymore.

**Comment by Epoxid2** [comment]
Hi,

I tried the latest version tonight and I think it’s absolutely fabulous! No problems! Thanks again for making scatterer!

Regards!
