### ISSUE TITLE
Differing CB and scaled/PQS names

### ISSUE THREAD

**Issue by NathanKell** [LGhassen/Scatterer#3]
Hi @LGhassen 
As may or may not have been mentioned in the thread, RSS has a rather special situation: due to certain things in KSP being hardcoded to require the homeworld be Kerbin, RSS only changes the name of the CelestialBody to Earth; it leaves the scaledversion transform/gameobject named Kerbin, and it leaves the PQSs named Kerbin and KerbinOcean. Can Scatterer handle such a situation?

**Comment by LGhassen** [comment]
Hi @NathanKell 
I haven't actually worked on this yet but I don't see any reason why it wouldn't be possible. I will try to work on it as soon as I can.

**Comment by NathanKell** [comment]
@LGhassen awesome, thank you so much! :)

**Comment by NathanKell** [comment]
@LGhassen just wondering how this is going, and if there's anything we can do on our end to help.

**Comment by LGhassen** [comment]
@NathanKell I have some free time today, I'll try to get it done.
