### ISSUE TITLE
Artifacts when using with Trajectories mod

### ISSUE THREAD

**Issue by AlexALX** [LGhassen/Scatterer#30]
Hello, i'm not sure how to properly report about issue, so i'm writing here.

When i install this mod with Trajectories together i have artifacts in map view when there is trajectory prediction - game start flicker with ocean or atmosphere. If there is no prediction for atmosphere entering there is no artifacts.

Here is screenshots:
https://imgur.com/a/pSq0W

I'm not sure what exactly wrong and in what addon is incompatibility, so writing to both addons.
https://github.com/neuoy/KSPTrajectories/issues/119

**Comment by LGhassen** [comment]
Hello, can you try the latest dev version and tell me if you still have this behaviour?

You can grab the .dll from here: https://github.com/LGhassen/Scatterer/blob/d119b3cd5b53ac012f0ae0bc5c68a0623cf6644a/scatterer/bin/Release/scatterer.dll?raw=true

Just overwrite the one in your GameData.

**Comment by AlexALX** [comment]
Ok, i checked and issue still here.

**Comment by AlexALX** [comment]
After some manipulations with my GameData folder i detected when exactly this bug start appear - if use ksp with scatterer + trajectories + WindowShine. If i remove WindowShine then everything is ok for both mods. So incompatibility is with WindowShine and not scatterer/trajectories. So please check it with WindowShine.

**Comment by AlexALX** [comment]
And i'm just qouting:

> [Scatterer] Error calling clouds2d.reassign() on planet: KerbinSystem.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Collections.Generic.Dictionary2[System.String,System.Collections.Generic.List1[System.Object]].get_Item (System.String key) [0x00000] in <filename unknown>:0 at scatterer.SkyNode.UpdateNode () [0x00000] in <filename unknown>:0
> 
> Also a number of NRE's
> 
> NullReferenceException: Object reference not set to an instance of an object at scatterer.RefractionCamera.OnPreCull () [0x00000] in <filename unknown>:0 (Filename: Line: -1) skynode added refraction cam

**Comment by LGhassen** [comment]
I reproduced the issue and will be checking it out.
