### ISSUE TITLE
Effects not visible with some rescale mods between certain altitudes

### ISSUE THREAD

**Issue by LGhassen** [LGhassen/Scatterer#32]
Submitted by Phineas Freak on KSPforum (https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip131-scatterer-atmospheric-scattering-v00324-28012018/&do=findComment&comment=3283479)

KSP Version: 1.3.1.1891 (using x64 binaries)

OS Version: Windows 7 x64

Renderer Version: DX9, DX11 and OpenGL

Issue: Scatterer fails to draw the effects in the flight view on large system rescales (x10) and low orbital altitudes

Mod List:

    Module Manager 3.0.1
    Kopernicus 1.3.1-3
    ModularFlightIntegrator 1.2.4.0

    Sigma Dimensions 0.9.6 (x10.625 stock rescale)
    Galileo Rescale 1.0.2.8 (x10.625 stock rescale)
    RealSolarSystem 13.0 (RSS "rescale")

Reproduction steps:

    Install all dependencies (as listed above), Sigma Dimensions and the x10.625 Galileo rescale config.
    Launch a new vessel into a low orbit by either conventional means or by Alt+F12 orbital editing (less than 100 km for Sigma rescales - less than 200 km for RSS or the x10.625 rescale).
    Observe that no Scatterer effects are visible in the flight view (map view works as expected).
    If the camera distance from the active vessel is increased at a maximum value (by scrolling out with the mouse wheel) then the effects will suddenly become visible.
    If the camera viewpoint is moved around, then the Scatterer effects will appear as a cube around the active vessel.
    It the orbital altitude of the active vessel is increased above the limits specified, then the effects will work as expected.

    The above issue can be also observed when using RSS (same scaling factor as the x10.625 Galileo rescale config) and any stock rescale config above x3.2.
    The above issue is not manifested in stock KSP or, generally, for stock rescales less than x3.2.
    The above issue is not manifested by using the previous v0.0320b Scatterer release.
    The above issue is manifested by using either the v0.0322 Scatterer release or the v0.0325 dev assembly.
    Various renderers (DirectX 9, DirectX 11, OpenGL 4.5) were tested. No differences between them were observed.

**Comment by LGhassen** [comment]
Video demonstrating the issue:
https://www.youtube.com/watch?v=lvqpIh91re4&feature=youtu.be
     01:50: Scatterer effects disappear
    02:50: Scatterer effects reappear
    04:00: A sample of the "cube"

**Comment by Sigma88** [comment]
keep in mind that SD has some code to rescale scatterer sunflare effects

if you need any help with that just ping me

(I'm not sure if this issue can be linked to that, but I thought I mentioned it anyways)

**Comment by LGhassen** [comment]
Thanks, but this has nothing to do with the sunflare.

To add some details: I know what's cuasing this issue, future development on my side to improve the scaled space shaders and layer handling will fix this issue.

**Comment by sgrif** [comment]
It looks like this also is causing the ground to disappear in some cases. At certain angles parts of Mars completely disappear below 400km. 
![20180218150157_1](https://user-images.githubusercontent.com/1529387/36357542-c129f2da-14bc-11e8-8dce-723bf26c3d17.jpg)

**Comment by LGhassen** [comment]
Are you sure scatterer is causing this issue with Mars?

**Comment by sgrif** [comment]
Nope, but since it was causing the atmosphere to disappear at similar altitudes I figured it was possibly related..

**Comment by Sigma88** [comment]
should be pretty easy to check, if you remove scatterer but still get the issue then scatterer is not the cause

**Comment by LGhassen** [comment]
What @Sigma88  said, remove scatterer and see if it still happens

**Comment by fensabriru** [comment]
I have same issue on 1.3.1KSP + RSS v13 + RSSVE 1.3.1-3 + EVE1.2.2-1  + scatterer 0.0320b just attitude differs (atmospheric effect disappear at 140000 - just when you get from atmosphere and appear at 250000... All the time for all vehicles. It appear exactly as shown on video... Is there a solution ?

**Comment by Sigma88** [comment]
https://github.com/LGhassen/Scatterer/issues/32#issuecomment-367345613

**Comment by fensabriru** [comment]
Thanks ! Just re-checked scatterer version and that was the problem. I thought there was 0.0320b installed but there was 0.0324  
0.0320b is working fine !

**Comment by PhineasFreak** [comment]
I finally managed to track down the change(s) that introduced the bug. It is caused by the commit a6ae4b4e2d6ffb254d444876388896dc5617951c. When i reverted the changes in the **SkyNode.cs** file everything worked as expected.

Tested with the latest **dev** Scatterer branch in KSP version **1.5.1.2335**.

**Comment by LGhassen** [comment]
Hi, I'm phasing out the scaled/local sky switching. Basically a permanent and elegant fix to this issue is coming in a few days.

**Comment by laukejas** [comment]
Hey, @LGhassen , were you able to fix this issue for KSP 1.3.1 version of Scatterer?

**Comment by LGhassen** [comment]
> 
> 
> Hey, @LGhassen , were you able to fix this issue for KSP 1.3.1 version of Scatterer?

This will be for a new version only, I don't support older versions but you can always recompile it for 1.3.1 if you feel up to it.

**Comment by laukejas** [comment]
@LGhassen  I see... That is most unfortunate, as RSS-RO only runs on KSP 1.3.1, and won't be updating anytime soon. It is beyond my abilities to compile it myself, I'm afraid.

**Comment by PhineasFreak** [comment]
@laukejas Why not just use the 0.0320b version of Scatterer? It's not like it does not exist or difficult to install...

**Comment by laukejas** [comment]
@LGhassen Well, I would like to, but I can't seem to find a link to download it. The earliest version in the Releases section of this Git is 0.0.324...

**Comment by LGhassen** [comment]
I thought the point was to have the fix on 1.3.1? In case you're just looking for 0.0320b, it's there on spacedock.

**Comment by laukejas** [comment]
@LGhassen Thanks, I downloaded and installed 0.0320b. But now I'm getting dark blue sky everywhere on Kerbin... Is this a known bug?

**Comment by LGhassen** [comment]
Never heard of this, I'd recommend clearing your configs and GameData folder and seeing if it persists, if it doesn't, put everything back step by step to find the issue.

I really don't plan to fix bugs on any older version though, so if you find a legitimate bug unreproducible in newer versions you're on your own.

**Comment by laukejas** [comment]
The only configs related to scatterer are from RSVE. Should I delete them?

**Comment by LGhassen** [comment]
Well, I meant to remove all configs apart from stocks and as well all mods, to see if the issue persists.

Can I see some screenshots of the issue?

**Comment by PhineasFreak** [comment]
@laukejas Please take your RSSVE issues to my GitHub repository, you are not doing anyone a favor by posting them here.

@LGhassen Since you have fixed the bug in the later Scatterer versions i would suggest to lock this one.

**Comment by LGhassen** [comment]
@PhineasFreak I will lock it as soon as I release it officially

**Comment by LGhassen** [comment]
Fixed in latest version
