### ISSUE TITLE
Jool visible through its moons

### ISSUE THREAD

**Issue by xjames50** [LGhassen/Scatterer#33]
KSP: 1.3.1 osx

Problem: 
Jool is completely visible through its moons. (I tried Laythe and Vall). (Sorry if its been reported, I couldn't find it anywhere).

Mods installed:
none besides scatterer. I removed all mods and did a complete reinstall of KSP and a new install of Scatterer. 

Reproduction steps:

Default config on scatterer. 
KSP default config except for:
-screen res 1280x800
-frame limit 60fps
-render quality: beautiful
-texture quality: full res

Fly a craft to laythe and park it in an equatorial orbit. When it passes in front of Jool, you can see Jool behind Laythe through the whole transit. Same with Vall. Tried it with Kerbin and the Mun but its ok there.

Log:

[Player.log](https://github.com/LGhassen/Scatterer/files/1776082/Player.log)

Screenshots:
![screenshot0](https://user-images.githubusercontent.com/36997657/36913284-2b7ee900-1e28-11e8-9217-bc2b8d501a9f.png)
![screenshot1](https://user-images.githubusercontent.com/36997657/36913285-2ba7c1fe-1e28-11e8-8e2c-b0e0335c9c24.png)

**Comment by LGhassen** [comment]
Thank you for posting the issue here, I'm well aware of it and will fix it soon.

**Comment by microstiff** [comment]
Sorry to bother but I get the exact same problem with a KSP 1.3.1 using Scatterer 0.0324, can we get a fix for it anytime in the near future? It would be so great to see Jool in the background while flying around, but not through its moons apparently. Many thanks.

**Comment by LGhassen** [comment]
As I said, I'm aware of this and will fix it soon.

**Comment by LGhassen** [comment]
Fix here, please test: https://github.com/LGhassen/Scatterer/releases/tag/v0.0328dev

**Comment by LGhassen** [comment]
Fixed with the newest version

**Comment by LGhassen** [comment]
I don't plan on doing backwards compatibility, supporting the current version is already a lot of work in itself.

Anyway, here is a backup link for 0.0328dev: https://mega.nz/#!bdgHgKyK!xU0oc8fD4q-z1lKmkmZpu279Nn0x73ulPc1xqZOccA8 

Don't hesitate to ask if you need an old version or something, I usually keep backups.

**Comment by psychonaut25** [comment]
Damn.... looks like 0.0328 doesn't work with KSP 1.3.1 either.  I guess I'm out of luck until I'm ready to upgrade to 1.4

**Comment by psychonaut25** [comment]
Would you consider doing backwards compatibility on one more release for a donation?  I understand you're busy and I appreciate the work you're doing, so if not, I understand, but I thought it might be worth asking.

**Comment by LGhassen** [comment]
I will try look into it these days, no donation needed :) if you only need this fix I can make an exception. Make sure to remind me if a few days ahve passed and you haven't ehard from me again.

**Comment by psychonaut25** [comment]
Indeed, I only need this fix.  Thanks a bunch :)

**Comment by LGhassen** [comment]
Replace the dll from 0.0324 with this: https://mega.nz/#!DNgxnBDT!VO-GQQlEhTzilQ_yo5PmDoAi3FidduU0-97f07q9bl4

**Comment by psychonaut25** [comment]
*in my best Guenter Wendt voice*
It's verking!

Thanks a lot, man :)
