### ISSUE TITLE
underwater fog

### ISSUE THREAD

**Issue by Galileo88** [LGhassen/Scatterer#34]
I have released a mod that provides a stock alike alternative to your ocean shader. It's for those who experience a performance hit with scatterers shaders. Scatterer is by far superior, but its a nice alternative I find. I only have a single issue, though. My mod disables Scatterer's shader, and while everything looks right above the ocean surface, Scatterer seems to disable the "fog" or underwater effect of the stock game. [Here is an example](https://i.imgur.com/fC0NaWh.png)

Hope this has a simple solution! thanks for looking into it!

**Comment by LGhassen** [comment]
Hi, last time we talked about this on the forum I had the impression you wanted to have the scatterer underwater fog enabled when the scatterer ocean shader is disabled, so it can be combined with the mod above or with stock.

Re-reading the text above however I get the impression scatterer disables the stock fog and you want that back instead, is that correct?
