### ISSUE TITLE
DisableEffectsForTextureReplacer nullref spam

### ISSUE THREAD

**Issue by Starwaster** [LGhassen/Scatterer#35]
DisableEffectsForTextureReplacer is firing for a shader mod other than Texture Replacer (shadowmage's textures unlimited)

> NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Renderer:set_enabled (bool)
  at scatterer.DisableEffectsForTextureReplacer.OnPreCull () [0x00000] in <filename unknown>:0 
UnityEngine.Camera:Internal_RenderToCubemapRT(RenderTexture, Int32)
UnityEngine.Camera:RenderToCubemap(RenderTexture, Int32)
KSPShaderTools.ReflectionManager:renderCubeFace(RenderTexture, Int32, Vector3, Int32, Single, Single)
KSPShaderTools.ReflectionManager:renderFace(RenderTexture, Int32, Vector3, Int32)
KSPShaderTools.ReflectionManager:updateReflections()
KSPShaderTools.ReflectionManager:Update()

**Comment by LGhassen** [comment]
Textures unlimited uses the same fix as texture replacer by using the same camera name, this is intended by shadowmage.

Now, do the nullrefs result in any visible issues?

**Comment by Starwaster** [comment]
The issues it causes are log spam which makes it harder to debug real problems (both as a player and as a modder who has come across this in other people's logs) and lags the system by writing to the log continuously.

**Comment by LGhassen** [comment]
If it's spamming continuously then there is a big problem. However I haven't been able to reproduce the continuous spamming. Maybe you can include some reproduction steps?

**Comment by LGhassen** [comment]
Fixed in commit  e738aac

**Comment by LGhassen** [comment]
Fixed in latest version
