### ISSUE TITLE
Scatterer Texture upside-down

### ISSUE THREAD

**Issue by Lubsch** [LGhassen/Scatterer#37]
**KSP:**
1.4.1.2089 Windows 64 Bit
**Problem:**
Scatterer Effect Overlay is flipped
**Mods installed:**
-ModuleManager 3.0.5
-Scatterer 0.0326
-KSP Making History
**Reproduction steps:**
Just launch a vehicle and look for the outline of the Scatterer effect. You notice that it's flipped. It becomes more obvious when you look around
**Log:**
http://www.mediafire.com/file/766coy7lsr6cvm7/KSP.log
**Screenshots:**
https://imgur.com/gallery/7ntmb

Thanks for the great mod! It worked fine in 1.3.1 and I usually use more Mods but they don't have an effect.

**Comment by LGhassen** [comment]
At the moment just turn on antialiasing or switch to OpenGL and it will go away, I have a fix already but didn't release it yet.

**Comment by LGhassen** [comment]
Fix here, please test: https://github.com/LGhassen/Scatterer/releases/tag/v0.0328dev

**Comment by LGhassen** [comment]
Fixed with the newest version
