### ISSUE TITLE
Kerbin is black when loading a game in orbit

### ISSUE THREAD

**Issue by dbeckwith** [LGhassen/Scatterer#38]
Kerbin looks completely black except for a few clouds probably from EVE or something. I've tried disabling my other mods and it's definitely Scatterer that's causing this. Loading from the surface of Kerbin is fine, and travelling to space is also fine. It only happens when I load a game in space.
Love the mod! But this is kinda preventing me from using it.

KSP 1.4.1.2089 Linux
Scatterer v0.0325dev (the settings window in-game says v0.0325dev, but it's from the release tagged v0.0326)
ModuleManager 3.0.6
Other mods:
* CollisionFX
* DistantObject
* EngineLight
* EnvironmentalVisualEnhancements
* GSF
* Kopernicus
* MechJeb2
* ModularFlightIntegrator
* NavyFish
* PlanetShine
* scatterer
* StockVisualEnhancements
* SVT
* TextureReplacer

Config: 
```
Scatterer_config
{
	autosavePlanetSettingsOnSceneChange = False
	disableAmbientLight = False
	integrateWithEVEClouds = True
	mainMenuWindowLocation = 0,0
	inGameWindowLocation = 147,64
	nearClipPlane = 0.0500000007
	forceDisableDefaultDepthBuffer = True
	useOceanShaders = True
	oceanSkyReflections = True
	oceanRefraction = False
	oceanPixelLights = False
	drawAtmoOnTopOfClouds = True
	oceanCloudShadows = True
	fullLensFlareReplacement = True
	showMenuOnStart = True
	scrollSectionHeight = 350
	useGodrays = True
	useEclipses = True
	useRingShadows = True
	terrainShadows = False
	shadowNormalBias = 0.720000029
	shadowBias = 0.5
	shadowsDistance = 50000
	guiModifierKey1String = LeftAlt
	guiModifierKey2String = RightAlt
	guiKey1String = F10
	guiKey2String = F11
	m_fourierGridSize = 128
}
```
I can provide logs too if you need them, but I don't know where to find them.

**Comment by IcArusZ4109** [comment]
yes, I encountered the same problem too.
and I did try to uninstall my all mods one by one, finally I found if you turn off the Ocean Shader, it will be solved.

**Comment by LGhassen** [comment]
I'm in the process of fixing this

**Comment by LGhassen** [comment]
Fix here, please test: https://github.com/LGhassen/Scatterer/releases/tag/v0.0328dev

**Comment by dbeckwith** [comment]
Well it's an improvement haha
![screenshot_2018-03-30_17-24-03](https://user-images.githubusercontent.com/1279939/38155852-ad532216-343f-11e8-86b4-7dffd0138976.png)
Same setup as before except I'm on KSP 1.4.2 now if that's okay. It looks like [it was only bugfixes](https://wiki.kerbalspaceprogram.com/wiki/1.4.2). I tried disabling the ocean shader and it made no difference.

**Comment by dbeckwith** [comment]
I tried disabling all my other visual mods, and Kerbin shows as just a solid white circle.

**Comment by LGhassen** [comment]
Idk what's going on here, can you post more details? Test without EVE? etc

**Comment by dbeckwith** [comment]
Here are my logs from the last run I did with no other visual mods besides scatterer, where it showed only a white circle for Kerbin when loading the Orbiting 101 tutorial.
[KSP.log](https://github.com/LGhassen/Scatterer/files/1865012/KSP.log)
And my config:
```
Scatterer_config
{
	autosavePlanetSettingsOnSceneChange = False
	disableAmbientLight = True
	integrateWithEVEClouds = True
	mainMenuWindowLocation = 0,0
	inGameWindowLocation = 138,49
	nearClipPlane = 0.0500000007
	forceDisableDefaultDepthBuffer = False
	useOceanShaders = True
	oceanSkyReflections = True
	oceanRefraction = False
	oceanPixelLights = False
	drawAtmoOnTopOfClouds = False
	oceanCloudShadows = True
	fullLensFlareReplacement = True
	showMenuOnStart = True
	scrollSectionHeight = 350
	useGodrays = True
	useEclipses = True
	useRingShadows = True
	terrainShadows = False
	shadowNormalBias = 0.720000029
	shadowBias = 0.5
	shadowsDistance = 50000
	guiModifierKey1String = LeftAlt
	guiModifierKey2String = RightAlt
	guiKey1String = F10
	guiKey2String = F11
	m_fourierGridSize = 128
}
```

**Comment by dbeckwith** [comment]
Sorry, ignore that log, something weird was going on with my game folder. I'll post a new one.

**Comment by dbeckwith** [comment]
Okay, here's my log with all other mods disabled, sorry about that.
[KSP.log](https://github.com/LGhassen/Scatterer/files/1865023/KSP.log)

**Comment by LGhassen** [comment]
From your log:
`/home/soscatterer/config/Sunflares/Sun/sunSpikes.png".
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0
  at System.IO.File.OpenRead (System.String path) [0x00000] in <filename unknown>:0
  at System.IO.File.ReadAllBytes (System.String path) [0x00000] in <filename unknown>:0
  at scatterer.SunFlare.start () [0x00000] in <filename unknown>:0
  at scatterer.Core.Update () [0x00000] in <filename unknown>:0`

Make sure all the files are in the correct directory, if you use soft links for scatterer or any of it's files get rid of them.

**Comment by dbeckwith** [comment]
I stopped using symlinks and that fixed it. Looking good now, thanks a lot!
