### ISSUE TITLE
Sky box is completely black

### ISSUE THREAD

**Issue by FabienDehopre** [LGhassen/Scatterer#4]
When I start a game (new or resume), after a couple of seconds, the sky becomes black as if there was no atmosphere on kerbin.
See include screenshot.
![screenshot0](https://cloud.githubusercontent.com/assets/97023/11318570/303cd2b4-9058-11e5-87d0-ad6d83366a7c.png)
![screenshot1](https://cloud.githubusercontent.com/assets/97023/11318571/303f2dac-9058-11e5-8d90-8b59e3c61697.png)

**Comment by FabienDehopre** [comment]
FYI: I run KSP in OpenGL mode

**Comment by DuoDex** [comment]
Can confirm : Running KSP 1.0.5 with the latest version of scatterer

Switching to mapmode and back fixes it however

**Comment by LGhassen** [comment]
Newest update should fix this.

**Comment by FabienDehopre** [comment]
Indeed this is much better.
However, there are still some artifact in the sky (see screenshots).
![screenshot5](https://cloud.githubusercontent.com/assets/97023/11451935/61868058-95d6-11e5-9c74-04a34af6cf41.png)
![screenshot6](https://cloud.githubusercontent.com/assets/97023/11451936/618939d8-95d6-11e5-9f67-79b00fecfb3a.png)

**Comment by LGhassen** [comment]
Sorry about that, I may have included the wrong shader files, try replacing the files CompiledSkyScaled.shader and CompiledSkyExtinction.shader with those from last release and report back if it works.

**Comment by FabienDehopre** [comment]
Yep! Now it's working correctly. Thanks!

**Comment by FabienDehopre** [comment]
Sometimes, there is black object in the sky.
![screenshot7](https://cloud.githubusercontent.com/assets/97023/11457625/1af7db18-96ae-11e5-9068-962869c0b12c.png)

**Comment by LGhassen** [comment]
Add "IgnoreProjector"="True" tags to those 2 shader files you just copied.

**Comment by FabienDehopre** [comment]
Indeed, that fixes the problem. Thanks again :+1:
