### ISSUE TITLE
Mirror image of planet and vessel while in atmosphere

### ISSUE THREAD

**Issue by Parad0xxis** [LGhassen/Scatterer#40]
KSP: 1.4.2 Windows 64bit
Problem:A mirrored ghost image of planet and ship while flying in atmosphere(Image: https://imgur.com/a/5R1wuMn )

Mods installed:
Scatterer 0.0331b
EnvironmentalVisualEnhancements 1.4.0-1
Stock Visual Enhancements 1.3.0.4
Stock Visual Terrain 2.1.4
DistantObjectEnhancement 1.9.1
PlanetShine 0.2.6.1
Kopernicus 1.4.3-1

Reproduction steps:

I have these settings(Deactivated some things to help my computer not fry): https://imgur.com/a/gF9YuS8
From there just launch a ship and it should start showing the mirrored ghost image. It gets more visible as you get higher up.

Log:

https://www.dropbox.com/s/srjwrexdb4htu0s/output_log.txt?dl=0

**Comment by LGhassen** [comment]
0.0331b is for KSP 1.4.2 and not 1.3.1. Update your KSP or use a version of the mod for 1.3.1 (keep in mind I will not provide any support for anything but the latest version).

**Comment by Parad0xxis** [comment]
shit actually that was a mistake that was supposed to say 1.4
I overlooked it while writing the issue

**Comment by LGhassen** [comment]
Hmm, can you try to toggle antialiasing (make sure you do it from main menu options and not from the ingame escape button options, this is important.)? I think my fix is not good enough, for some people it works and others not.

**Comment by Parad0xxis** [comment]
Seems to have fixed the issue. No longer getting the strange mirror image.

**Comment by Poodmund** [comment]
In reference to this issue, I recently saw it occur on a Twitch stream on a 1.4.5 install and can confirm that the issue persists (as would be expected) on KSP 1.5.1 vanilla install with just Scatterer installed.

https://www.youtube.com/watch?v=zqyHC5t66Wc

The above video shows that if you load a vessel with AA disabled via the Esc Settings Menu, the issue occurs. If you then toggle AA on via that menu, it resolves the issue. If you then toggle AA off straight after, the issue does not reappear; however, if you toggle AA off and then change scene (back to the Tracking Station and then back to a vessel) the issue reappears.

As noted above, if you disable AA via the Title Screen Graphics Settings menu, this bug does not occur (for me).

**Comment by MOARdV** [comment]
> As noted above, if you disable AA via the Title Screen Graphics Settings menu, this bug does not occur (for me).

I don't know if this is helpful, but RasterPropMonitor was plagued with this problem when 1.4.0 came out.  The solution was an unpleasant hack:

https://github.com/Mihara/RasterPropMonitor/blob/4fa2c7ff9097f193d66267830503b54ceb25dda2/RasterPropMonitor/Core/RasterPropMonitor.cs#L181

**Comment by LGhassen** [comment]
Fixed in latest version
