### ISSUE TITLE
Black sky at night below 200m

### ISSUE THREAD

**Issue by m4ti140** [LGhassen/Scatterer#41]
**KSP:** 1.4.3 64bit dx9

**Problem:** Skybox is not rendered at night when below 200m. Using default scatterer configs and SVE EVE configs (SVE_Scatterer folder deleted)

**Mods installed:** 
[mods.txt](https://github.com/LGhassen/Scatterer/files/1968636/mods.txt)

**Reproduction steps:**
1. Launch from KSP runway at night, refraction shaders enabled
2. Sky is black
3. Climb past 200m
4. Sky is not black

**Log:**
[output_log.txt](https://github.com/LGhassen/Scatterer/files/1968642/output_log.txt)

**Comment by LGhassen** [comment]
Please test this fix https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip142-scatterer-atmospheric-scattering-v00331b-27042018/&do=findComment&comment=3366891

**Comment by LGhassen** [comment]
Fixed in commit 118efb0a
