### ISSUE TITLE
Effects broken in Jool atmosphere

### ISSUE THREAD

**Issue by m4ti140** [LGhassen/Scatterer#43]
This is the last one, I promise

**KSP:** 1.4.3 64bit dx9

**Problem:** Scatterer (and, to be fair, EVE too) effects are broken in Jool's atmosphere. The sky is black, weird artifacts appear near reference level. Screenshot:
![screenshot8](https://user-images.githubusercontent.com/19916764/39546057-633b6890-4e53-11e8-9dbd-64ea1bf938d8.png)
The EVE artifact isn't present here in particular (I don't know tf I did with that screenshot) but that's probably not a Scatterer issue.
I think this is related to #32 

**Mods installed** See #41 NOTE: 0.0331b used in all 3 issues

**Reproduction steps**
1. Build an OP craft
2. Fill it with expendable crew
3. Try to land on Jool

**Log:** see #41

**Comment by Maffif** [comment]
I second this issue; however, I tested it on clean installs of 1.3.1, 1.4.3, and 1.4.5 (with respective Scatterer versions, and with/without respective EVE/configs from several different packs)

It seems, in 1.4+, in _any_ gas giant, scatterer cuts out below 300km above the "surface"
(Prior to testing on clean installs fetched from steam, I tried on several planet packs such as OWR and OPM)

**Comment by dafrandle** [comment]
I can confirm this to on 1.5.1 on latest version
(although I don't know if its cause by a mod conflict)

**Comment by LGhassen** [comment]
Fixed in latest version
