### ISSUE TITLE
Exception thrown when body has EVE cloud layers but no volumetrics enabled for said body

### ISSUE THREAD

**Issue by Poodmund** [LGhassen/Scatterer#47]
`[Scatterer] Volumetric clouds error on planet: KerbinSystem.NullReferenceException: Object reference not set to an instance of an object
  at scatterer.SkyNode.mapEVEvolumetrics () [0x00000] in <filename unknown>:0 `
Null Ref is thrown when switching to the Planetarium camera (Tracking Station) when a body has EVE cloud layers set to it but none of those layers have volumetrics enabled.

I think the issue originates from this section from Skynode.cs: https://github.com/LGhassen/Scatterer/blob/ddbaecc1a751db0393701eab1699e06c8f988556/scatterer/Effects/DynamicLoaded/Atmosphere/SkyNode.cs#L1548-L1589

**Comment by jrodrigv** [comment]
+ 100

**Comment by LGhassen** [comment]
Fixed in commit  e738aac
