### ISSUE TITLE
Ocean Lights feature produces giant visual artifacts

### ISSUE THREAD

**Issue by Beetlecat** [LGhassen/Scatterer#48]
Latest Scatterer (via CKAN) causes craft lighting to produce a giant visual artifact when ocean light reflection is on, and the craft lights are on --depending on viewing angle. The lights are also *not* reflected on the surface.

KSP: 1.5.1 Windows 64bit

Problem: Ship lighting glitch when ocean lighting enabled

Mods installed:

Scatterer 0.0336 (via CKAN) ((only mod))

Reproduction steps:

With ocean lighting enabled, default scatterer settings: Launch a ship from KSP, turn on craft lights; depending on angle, the craft light source creates a visual glitch that floods the screen (depending on angle).

Log:
https://www.dropbox.com/s/3tc1brse90v686c/output_log.txt?dl=0

**Comment by LGhassen** [comment]
Does this still happen with latest version?

**Comment by Beetlecat** [comment]
Will confirm ASAP. Thanks for checking back on this.

**Comment by LGhassen** [comment]
Great
