### ISSUE TITLE
[Bug] Atmosphere/ocean config loading via GUI (v0.04dev)

### ISSUE THREAD

**Issue by PhineasFreak** [LGhassen/Scatterer#51]
**Description:**

It is not possible to load externally customized atmosphere/ocean configuration files via the Scatterer interface. Any changes to these files will be overridden by the currently loaded config(s). Current scene does not seem to matter, since i tested it in Space Center, Flight/Map and Tracking Station views.

**Notes:**

After opening a fresh KSP instance i proceeded to open and modify some common atmosphere parameters inside the Kerbin "atmo.cfg" file via Notepad++. I then saved and closed the file.

Back in KSP i tried to load the modified file via the GUI. No changes where observed. I then saved the file via the GUI. All custom external changes were immediately overwritten.

**Test Environment:**

Tested in a new **KSP 1.5.1.2335** installation with just **Scatterer 0.04 Dev** installed.

Tested Scatterer parameters include **experimentalAtmoScale**, **skyAlpha**, **skyExposure** and **scatteringExposure**. I also tested some ocean parameters but i observed the same results.

**Comment by LGhassen** [comment]
As far as I know, this is not possible in general with any mod that uses configNodes (ie the configNodes that are editable on-game load by ModuleManager). Does it work in other mods? And also I think there might be some kind of option in the game's Alt+F11 menu to reload them but I could be wrong.

**Comment by LGhassen** [comment]
Well, scatterer reloads from configNode when you press load, it doesn't actually read the file directly.

Therefore try to reload the game database and then load in scatterer.

**Comment by PhineasFreak** [comment]
Oh...that explains it. I though that you reloaded the configuration files directly from the disk...

I can make the connection between these two now so consider me stupid. Closing issue.

**Comment by LGhassen** [comment]
> Oh...that explains it. I though that you reloaded the configuration files directly from the disk...

It used to be like this in the beginning but ModuleManager compatibility was requested so now it reads from configNode.
