### ISSUE TITLE
Dramatic Frame Rate Drop with Kopernicus "Change My Kerbin" 

### ISSUE THREAD

**Issue by gordonfpanam** [LGhassen/Scatterer#54]
I work on [Alien Space Programs](https://github.com/GregroxMun/Alien-Space-Programs), which lets you start a game from a stock world other than Kerbin. Earlier in late 2018 I released a rebuilt version that takes advantage of Kopernicus 1.5.1's "Change My Kerbin" feature, which lets me use a different stock world as the template for the home world. When I do things this way, it preserves that world's easter eggs; you can find the Face on Homeworld Duna, or the cave on Homeworld Tylo, for instance. 

I uncovered a frame rate problem with more complex craft, however; anything greater than 100 or so parts will cause a severe frame rate drop. The physics ticks become slower than a 1/4 second, and time slows down to two real-world seconds per game second. 

This didn't happen with previous versions of Alien Space Programs, and it also doesn't happen if I build the home world using the Kerbin template, use removeAllPQSMods = True, and build the home world from 'scratch,' using data from KittopiaTech. When I do this however, I can't add that world's easter eggs back except for monoliths.

**Here's where I ask about Scatterer**

I narrowed the frame rate problem down to Scatterer and no other add-on. When I remove Scatterer, I get the same frame rates regardless of how I build the home world. This includes adding EVE and a heavy particle count configuration like SVE. When I put Scatterer back though, the frame rate severely drops when I build the home world from a non-Kerbin template, and returns to normal when I build it from scratch. The frame rate drop ceases during on-rails time warp, either landed or in low orbit. 
What I want to know, is if I can change something in how I'm building the home world that would avoid the Scatterer frame rate drop and still preserve that world's easter eggs. 

**To reproduce the problem** 

Since Scatterer's latest KSP release is 1.5.1, use KSP 1.5.1, Kopernicus 1.5.1-x (either -1 -2 or -3), and Alien Space Programs 1.5.1. Get the Scatterer release for KSP 1.5.1. Eve seems to be the easiest place to reproduce the problem, so set the home world to Eve and put a 100+ part craft on the runway or launch pad. On my Intel i4770 CPU plus GTX-1080 graphics I get a frame rate drop to below 15 FPS when I do this. To restore the frame rate to 'playable,' replace Eve.cfg with Eve.full-cfg from the [ASP 1.5.1 project site](https://github.com/GregroxMun/Alien-Space-Programs/tree/master/GameData/AlienSpacePrograms/Eve). You can remove and re-add Scatterer to test Eve.basic-cfg and Eve.full-cfg to observe the frame rate difference. 

**Suggestions?** 

Is there something I can do in my Kopernicus configuration to improve performance when Scatterer is used? 

Part of my thought process is how the home world still needs to be named "Kerbin" internally, at least at first, and use cbNameLater to rename it. It appears Scatterer keys its atmosphere settings on the cbNameLater value, but I wonder if it's trying to draw Kerbin's and Eve's atmospheres at the same time. 

I also have a Scatterer patch file in ASP that renames any configuration for Kerbin to use 'Bin' instead, which is what non-homeworld Kerbin is called internally. Cheating a 100+ part craft to 'Bin' regardless of how 'Bin' is built gives me the same decent frame rate.

**Comment by gordonfpanam** [comment]
Sorry. While part of it was being upset earlier and figuring you didn't need yet another GitHub issue on a frame rate problem, a bigger part of it is I am encountering frame rate problems even without Scatterer in certain cases; when the home world doesn't have an ocean.

I'll look for help sorting that out and then I'll come back to this, assuming it's still a problem.

**Comment by LGhassen** [comment]
Ok, sure
