### ISSUE TITLE
File missiing for Compiling shaders for dev branch

### ISSUE THREAD

**Issue by jrodrigv** [LGhassen/Scatterer#55]
Hi. I was trying to recompile the shaders of your dev branch however I think there is one file missing.

OceanShadows.cginc for the OceanWhiteCapsPixelLights

**Comment by LGhassen** [comment]
It's added now.

Note: As the dev branch is quite different from the release branch, you'll have to reconfigure the planets.

**Comment by jrodrigv** [comment]
Thank you!
