### ISSUE TITLE
All planets are using Laythe atmo config file

### ISSUE THREAD

**Issue by CousinFruitCupz** [LGhassen/Scatterer#56]
Every planet is using Laythe Atmo config file and it won't let me change it. And it is not just a name glitch, every planet now has same Aurora and atmosphere, even Kerbin. I looked through the code and found no visible problems. Help would be appreciated. Thank you. 

![2019-02-19 13](https://user-images.githubusercontent.com/47863609/53186634-5dd12200-35cf-11e9-9611-03bbf9daa7b1.png)

![2019-02-19 17](https://user-images.githubusercontent.com/47863609/53186670-73dee280-35cf-11e9-9c4b-20e46786b7b0.png)

![2019-02-19 12](https://user-images.githubusercontent.com/47863609/53186707-88bb7600-35cf-11e9-9869-b88442b13ffe.png)

**Comment by LGhassen** [comment]
Please detail your issue and make a full bug report, look in the OP of the forum thread for how to report an issue.

**Comment by LGhassen** [comment]
Should be fixed from 0.0767 onwards: https://github.com/LGhassen/Scatterer/releases/tag/0.0767
