### ISSUE TITLE
White Atmosphere and Ocean 

### ISSUE THREAD

**Issue by IWillAskQuestions** [LGhassen/Scatterer#57]
KSP: 1.6.1 MacOS Mojave, 64 Bit
Problem: White atmosphere and ocean.

Mods installed: 
Squad, EVE 1.4.2.2, Scatterer 0.0336 - I have other mods, but even without the mods I have the glitch.

Reproduction steps:
Go onto KSP title screen, see Kerbin all white, then, after loading a world, the terrain is fine, but the ocean and sky is all white.

Log:
[KSP.log.zip](https://github.com/LGhassen/Scatterer/files/2946213/KSP.log.zip) - Again, this has my current mods, but when I tried KSP without any other mods it still had the glitch.

**Comment by LGhassen** [comment]
Is this still happening in the latest version?

**Comment by char1es31** [comment]
I am getting a similar issue with latest version. Issue also occurs without any mods. Only with Squad and SquadExpansion

KSP: 1.6.1 Win 10 64bit

**Mods installed**
Squad,
SquadExpansion,
scatterer-0.053,
BetterBurnTime-1.9.1,
Trajectories-v2.2.2

**Reproduction Steps**
![20190315231441_1](https://user-images.githubusercontent.com/6976747/54470115-f85cf500-4778-11e9-95f8-6a8f4c8da690.jpg)
![20190315231533_1](https://user-images.githubusercontent.com/6976747/54470116-f85cf500-4778-11e9-90a3-174b46319e7c.jpg)
![20190315231736_1](https://user-images.githubusercontent.com/6976747/54470117-f85cf500-4778-11e9-8c5c-b2d64ad8fb94.jpg)

**Logs**
[Kerbal Space Program.zip](https://github.com/LGhassen/Scatterer/files/2973426/Kerbal.Space.Program.zip)

**Comment by char1es31** [comment]
> I am getting a similar issue with latest version. Issue also occurs without any mods. Only with Squad and SquadExpansion
> 
> KSP: 1.6.1 Win 10 64bit
> 
> **Mods installed**
> Squad,
> SquadExpansion,
> scatterer-0.053,
> BetterBurnTime-1.9.1,
> Trajectories-v2.2.2
> 
> **Reproduction Steps**
> ![20190315231441_1](https://user-images.githubusercontent.com/6976747/54470115-f85cf500-4778-11e9-95f8-6a8f4c8da690.jpg)
> ![20190315231533_1](https://user-images.githubusercontent.com/6976747/54470116-f85cf500-4778-11e9-90a3-174b46319e7c.jpg)
> ![20190315231736_1](https://user-images.githubusercontent.com/6976747/54470117-f85cf500-4778-11e9-8c5c-b2d64ad8fb94.jpg)
> 
> **Logs**
> [Kerbal Space Program.zip](https://github.com/LGhassen/Scatterer/files/2973426/Kerbal.Space.Program.zip)

This is resolved for me in version 0.0540.
I also noticed that the issue can be reproduced by having a different folder name at the root of the mod
for example, instead of "./GameData/scatterer/" if you have "./GameData/scatterer-0.0540/" the issue will occur.

**Comment by IWillAskQuestions** [comment]
> Is this still happening in the latest version?

No, I managed to fix it a while ago. Also, sorry for not replying, my Gmails were a bit buggy for awhile. Like Char1les31 said, if you unpackage it from the initial downloaded folder and just have "scatterer" not scatterer and the version number, it works. Again, sorry I wasn't on for a bit, and I know it doesn't really matter anymore.

**Comment by ILoveMoarBoosters** [comment]
![screenshot158](https://user-images.githubusercontent.com/93046908/141615079-09e7035c-9fbc-4e8c-8eab-8c8f56088645.png)
how do i fix this atmosphere bug? im playing on ksp 1.12.2 and scatterer version v0.0825b and this had never happened to me before. it started happening to me yesterday after i updated the mod on ckan.

**Comment by WujekFoliarz** [comment]
> ![screenshot158](https://user-images.githubusercontent.com/93046908/141615079-09e7035c-9fbc-4e8c-8eab-8c8f56088645.png) how do i fix this atmosphere bug? im playing on ksp 1.12.2 and scatterer version v0.0825b and this had never happened to me before. it started happening to me yesterday after i updated the mod on ckan.

same

**Comment by LGhassen** [comment]
See https://github.com/LGhassen/Scatterer/issues/147#event-5917692566

**Comment by WujekFoliarz** [comment]
> See [#147 (comment)](https://github.com/LGhassen/Scatterer/issues/147#event-5917692566)

I reinstalled the game like 5 times and it's still happening, no other mods installed

**Comment by LGhassen** [comment]
So first off, update scatterer, you're using CKAN but a few versions behind still. Secondly at least post logs or something. What am I supposed to do? Magically connect to your game and debug it?

**Comment by TheVrSofa** [comment]
> So first off, update scatterer, you're using CKAN but a few versions behind still. Secondly at least post logs or something. What am I supposed to do? Magically connect to your game and debug it?

I have LOTS of mods. same issue, been pissing about with all of them but discovered if i remove EVERYTHING, and have ONLY scatterer. it still happens.
so seems to be an issue with....just scatterer. Not to blame ya, obviously scatterer is SO amazing i decided id rather have no spectra of eve, id rather just hjaver scatterer, thats how i found out it seems to be an error EVEN when i only have scatterer installed. 

here be an image.

(useing ckan, i tried all versions of KSP from most recent back to 1.10. - im now back to hwere i started on 1.11.1 trying to get it working now i see more than just me having the issue. also Tried the last 4 versions of scatterer, same issue which is weird af i thought. so currently let ckan do its thing to update to latest again, still there and yet, the issue remains. so damn weird)

Im new, but online, ill check this later but if you tell me how to get yo the "post logs" from my game, ill do that and send them to you so you can ger more info. i see its a pain when people post their opinions but thats all i can do. going to google how to get you post logs and see if i can by myself but if you read this, leave a quick how to, and ill get on that asap

**Comment by LGhassen** [comment]
@TheVrSofa sadly I don't see any errors in your log. Could you try again the following again without any other mods (also no gameplay mods just scatterer):

- Delete ScattererAtmosphereCache and Scatterer, reinstall scatterer 0.0829
- If it doesn't work do the same with 0.0825b
- If it doesn't work do the same with 0.0770 (it's outdated now but to just to see if it works)

**Comment by TheVrSofa** [comment]
> @TheVrSofa sadly I don't see any errors in your log. Could you try again the following again without any other mods (also no gameplay mods just scatterer):
> 
>     * Delete ScattererAtmosphereCache and Scatterer, reinstall scatterer 0.0829
> 
>     * If it doesn't work do the same with 0.0825b
> 
>     * If it doesn't work do the same with 0.0770 (it's outdated now but to just to see if it works)

done with all three. no effect :(

**Comment by TheVrSofa** [comment]
> > ![screenshot158](https://user-images.githubusercontent.com/93046908/141615079-09e7035c-9fbc-4e8c-8eab-8c8f56088645.png) how do i fix this atmosphere bug? im playing on ksp 1.12.2 and scatterer version v0.0825b and this had never happened to me before. it started happening to me yesterday after i updated the mod on ckan.
> 
> same

post ya log text file :)

**Comment by LGhassen** [comment]
> > @TheVrSofa sadly I don't see any errors in your log. Could you try again the following again without any other mods (also no gameplay mods just scatterer):
> > ```
> > * Delete ScattererAtmosphereCache and Scatterer, reinstall scatterer 0.0829
> > 
> > * If it doesn't work do the same with 0.0825b
> > 
> > * If it doesn't work do the same with 0.0770 (it's outdated now but to just to see if it works)
> > ```
> 
> I tried all three but had no effect, i tried all the scatterer versions in 1.11.1 easlier today. i can do it again but id fuck up all my saves and thats the reason im was looking for a solution. i dont know how to undo them all and put them back without messing up my games. hehe
> 
> ps: i wiped everything easlier today as well and the same issue happened. even running by itself. do you need the logs for those? i can do it all again but will be tomorrow.

That doesn't make any sense. Are you downloading these from CKAN or from spacedock/github?

**Comment by WujekFoliarz** [comment]
> post ya log text file :)
[KSP.log](https://github.com/LGhassen/Scatterer/files/7933411/KSP.log)

i have some mods installed but it doesn't make any difference i tested with and without mods.

**Comment by TheVrSofa** [comment]
> > > @TheVrSofa sadly I don't see any errors in your log. Could you try again the following again without any other mods (also no gameplay mods just scatterer):
> > > ```
> > > * Delete ScattererAtmosphereCache and Scatterer, reinstall scatterer 0.0829
> > > 
> > > * If it doesn't work do the same with 0.0825b
> > > 
> > > * If it doesn't work do the same with 0.0770 (it's outdated now but to just to see if it works)
> > > ```
> > 
> > 
> > I tried all three but had no effect, i tried all the scatterer versions in 1.11.1 easlier today. i can do it again but id fuck up all my saves and thats the reason im was looking for a solution. i dont know how to undo them all and put them back without messing up my games. hehe
> > ps: i wiped everything easlier today as well and the same issue happened. even running by itself. do you need the logs for those? i can do it all again but will be tomorrow.
> 
> That doesn't make any sense. Are you downloading these from CKAN or from spacedock/github?
> 
> Also just back up your saves folder





I have tried via CKAN, with didnt work on al three scatterer versions, and the last 4 ksp versions.
and today
i doid the same without ckan.
same effect.
only way to remove the white ring is to delete scatterer as far as i have been able to manage.  :(

**Comment by WujekFoliarz** [comment]
>I have tried via CKAN, with didnt work on al three scatterer versions, and the last 4 ksp versions.
and today
i doid the same without ckan.
same effect.
only way to remove the white ring is to delete scatterer as far as i have been able to manage. :(

yea it almost feels like my PC was banned from using scatterer, no matter what I do my game either freezes or gets the white ring

**Comment by LGhassen** [comment]
@WujekFoliarz @TheVrSofa  so scatterer was working fine one day and then the next day poof? And even older versions stopped working with a clean install suddebly? Then this must be something external, a driver update, a windows update, a ksp update or an antivirus update, I don't know exactly.

**Comment by WujekFoliarz** [comment]
Yea it was working before and suddenly stopped

**Comment by LGhassen** [comment]
Then I have no clue, figure out what changed on your system

**Comment by TheVrSofa** [comment]
> @WujekFoliarz @TheVrSofa so scatterer was working fine one day and then the next day poof? And even older versions stopped working with a clean install suddenly? And this happened simultaneously for a lot of people? Then this must be something external, a driver update, a windows update, a ksp update or an antivirus update, I don't know exactly.


Almost.
It went down for all of us when the last scatterer update happened on ckan. Ksp or can maybe to blame but yes, it seems we cant even go back. Its as the other lad says, its like our pcs were banned from using it and undoing the updates dont have an effect. 
:(☹

**Comment by WujekFoliarz** [comment]
@TheVrSofa exactly

**Comment by LGhassen** [comment]
> > @WujekFoliarz @TheVrSofa so scatterer was working fine one day and then the next day poof? And even older versions stopped working with a clean install suddenly? And this happened simultaneously for a lot of people? Then this must be something external, a driver update, a windows update, a ksp update or an antivirus update, I don't know exactly.
> 
> Almost. It went down for all of us when the last scatterer update happened on ckan. Ksp or can maybe to blame but yes, it seems we cant even go back. Its as the other lad says, its like our pcs were banned from using it and undoing the updates dont have an effect.
> 
> @LGhassen It was when we decided to update ckan and see what was new. Scatterer had an update and after we installed it, we have seemed to break our ability to use scatterer at all. Did the last scatterer update change anything drastic?

Nothing drastic, if you find the reason let me know but I have nothing to add to this thread.

There is nothing persisted besides the scatterer config and the atmosphereCache, so there is nothing a clean install and a version rollback wouldn't fix. Try asking this guy what worked for him as he fixed/closed his issue: https://github.com/LGhassen/Scatterer/issues/147

**Comment by TheVrSofa** [comment]
> > > @WujekFoliarz @TheVrSofa so scatterer was working fine one day and then the next day poof? And even older versions stopped working with a clean install suddenly? And this happened simultaneously for a lot of people? Then this must be something external, a driver update, a windows update, a ksp update or an antivirus update, I don't know exactly.
> > 
> > 
> > Almost. It went down for all of us when the last scatterer update happened on ckan. Ksp or can maybe to blame but yes, it seems we cant even go back. Its as the other lad says, its like our pcs were banned from using it and undoing the updates dont have an effect.
> > @LGhassen It was when we decided to update ckan and see what was new. Scatterer had an update and after we installed it, we have seemed to break our ability to use scatterer at all. Did the last scatterer update change anything drastic?
> 
> Nothing drastic, if you find the reason let me know but I have nothing to add to this thread.
> 
> There is nothing persisted besides the scatterer config and the atmosphereCache, so there is nothing a clean install and a version rollback wouldn't fix. Try asking this guy what worked for him as he fixed/closed his issue: #147

he had a different issue. his was that the file naming was wrong. moving the scatterer file into the game data folder properly fixed his issue, however Ckan instals correctly and i manually did it myself. but even a clean install, scatterer just wont work anymore. My mates also have the same issue, so its not just us as it were. the ckan update for scatterer, then it killed itself XD lol

**Comment by TheVrSofa** [comment]
> > > @WujekFoliarz @TheVrSofa so scatterer was working fine one day and then the next day poof? And even older versions stopped working with a clean install suddenly? And this happened simultaneously for a lot of people? Then this must be something external, a driver update, a windows update, a ksp update or an antivirus update, I don't know exactly.
> > 
> > 
> > Almost. It went down for all of us when the last scatterer update happened on ckan. Ksp or can maybe to blame but yes, it seems we cant even go back. Its as the other lad says, its like our pcs were banned from using it and undoing the updates dont have an effect.
> > @LGhassen It was when we decided to update ckan and see what was new. Scatterer had an update and after we installed it, we have seemed to break our ability to use scatterer at all. Did the last scatterer update change anything drastic?
> 
> Nothing drastic, if you find the reason let me know but I have nothing to add to this thread.
> 
> There is nothing persisted besides the scatterer config and the atmosphereCache, so there is nothing a clean install and a version rollback wouldn't fix. Try asking this guy what worked for him as he fixed/closed his issue: #147

it crashed this time, so i took the logs as may be handy to see what went wrong? i dunno. we just decided to remove it for now until its fixed i guess. but sucks as its the only mod i actually wanted to start with :(

**Comment by TheVrSofa** [comment]
> > > @WujekFoliarz @TheVrSofa so scatterer was working fine one day and then the next day poof? And even older versions stopped working with a clean install suddenly? And this happened simultaneously for a lot of people? Then this must be something external, a driver update, a windows update, a ksp update or an antivirus update, I don't know exactly.
> > 
> > 
> > Almost. It went down for all of us when the last scatterer update happened on ckan. Ksp or can maybe to blame but yes, it seems we cant even go back. Its as the other lad says, its like our pcs were banned from using it and undoing the updates dont have an effect.
> > @LGhassen It was when we decided to update ckan and see what was new. Scatterer had an update and after we installed it, we have seemed to break our ability to use scatterer at all. Did the last scatterer update change anything drastic?
> 
> Nothing drastic, if you find the reason let me know but I have nothing to add to this thread.
> 
> There is nothing persisted besides the scatterer config and the atmosphereCache, so there is nothing a clean install and a version rollback wouldn't fix. Try asking this guy what worked for him as he fixed/closed his issue: #147
[Uploading KSP.log…]()

it crashed this time, so i took the logs as may be handy to see what went wrong? i dunno. we just decided to remove it for now until its fixed i guess. but sucks as its the only mod i actually wanted to start with :(

**Comment by TheVrSofa** [comment]
[KSP.log](https://github.com/LGhassen/Scatterer/files/7937445/KSP.log)
@LGhassen 
it crashed this time, so i took the logs as may be handy to see what went wrong? i dunno. we just decided to remove it for now until its fixed i guess. but sucks as its the only mod i actually wanted to start with :(

**Comment by LGhassen** [comment]
> [KSP.log](https://github.com/LGhassen/Scatterer/files/7937445/KSP.log) @LGhassen it crashed this time, so i took the logs as may be handy to see what went wrong? i dunno. we just decided to remove it for now until its fixed i guess. but sucks as its the only mod i actually wanted to start with :(

Try to go in-game, alt-f11 -> atmosphere tab. Then press delete atmo cache, then press fast preview mode, then press generate

**Comment by TheVrSofa** [comment]
nothing came up for me..... f-11 doesnt activate when i press it. gonna do a full reinstall later and try again

**Comment by LGhassen** [comment]
> nothing came up for me..... f-11 doesnt activate when i press it. gonna do a full reinstall later and try again

It's alt + f-11 ...

**Comment by WujekFoliarz** [comment]
> Try to go in-game, alt-f11 -> atmosphere tab. Then press delete atmo cache, then press fast preview mode, then press generate

I have a fix @TheVrSofa 
1. Zoom at a planet with atmosphere in tracking center
2. let your game freeze
3. alt+f4
4. come back to the tracking center and zoom at the same planet, now it won't crash but the planet will have broken atmosphere
5. alt-f11 -> atmosphere tab. Then press delete atmo cache, then press fast preview mode, then press generate (just @LGhassen said)

Now you have to do this with every other planet, it's going to take some time but it works

**Comment by WujekFoliarz** [comment]
oh nevermind it will still crash in-flight

**Comment by LGhassen** [comment]
Ok so I found the issue, it's related to GPU speed, if the atmosphere generation takes too long unity thinks the shader crashed. Fix incoming.

**Comment by LGhassen** [comment]
@WujekFoliarz @TheVrSofa @ILoveMoarBoosters test this: https://mega.nz/file/SQYC3LiQ#b1JQP83FAW4hAtJLkeEO7gcjzSBCFkZOTjjtf3C6IMo

**Comment by LGhassen** [comment]
Confirmed fixed on my old laptop. Try 0.0830

**Comment by WujekFoliarz** [comment]
> Confirmed fixed on my old laptop. Try 0.0830

my game's loading. We'll see if it works

**Comment by WujekFoliarz** [comment]
@LGhassen YES! It works
![image](https://user-images.githubusercontent.com/72314465/151602287-e2911c6f-1104-4105-9cb1-7e8743d724bb.png)

**Comment by TheVrSofa** [comment]
talk me through what to do. i tried to install the scatter you posted 
https://mega.nz/file/GJR2TRKI#fzDcRO_UO_Xmc1Kk7eTOWQFeXGO9WMHqsOBKv0S8I4g
but it didnt work.

**Comment by LGhassen** [comment]
> talk me through what to do. i tried to install the scatter you posted https://mega.nz/file/GJR2TRKI#fzDcRO_UO_Xmc1Kk7eTOWQFeXGO9WMHqsOBKv0S8I4g but it didnt work.

- Delete scatterer and scattererAtmosphereCache manually from GameData folder
- Download 0.0831 from here https://github.com/LGhassen/Scatterer/releases and install it

That's it, if you do this it WILL work. If in doubt do a clean reinstall of KSP.

**Comment by TheVrSofa** [comment]
Fixed! Thanks man. Legendary! Couldn't do without this and it can't have been easy. From all of us who don't say thanks, thank you. We all really appreciate the time you put in.

**Comment by RichardKermanCanCodeAndRocketsAreCool** [comment]
It worked for me, but is there any differences between this version and the latest?

**Comment by LGhassen** [comment]
> It worked for me, but is there any differences between this version and the latest?

The latest version just pushes the fix further to make it work on even slower machines (just cuts the work into even smaller chunks essentially which older hardware can handle).
