### ISSUE TITLE
Black clouds after latest update.

### ISSUE THREAD

**Issue by doubleuudude** [LGhassen/Scatterer#59]
I've had this happen once in awhile before but changing scenes always made it go away.  After installing the latest update from CKAN it's happening all the time.

**Screenshots:**  
![screenshot16](https://user-images.githubusercontent.com/25853712/54573015-91715300-49a7-11e9-9357-10ef5e00b79a.png)
![screenshot17](https://user-images.githubusercontent.com/25853712/54573063-dac1a280-49a7-11e9-920a-38d0a3d363e7.png)

**KSP:** 1.6.1 Windows 64bit

**Problem:** Black, ominous clouds on Kerbin in all scenes except loading screen.

**Mods installed:** See end of bug report, it's a lot

**Scatterer:** 0.0540 CKAN

**EnvironmentalVisualEnhancements:** 1.4.2-2

**Reproduction steps:**

Load into game.  Changing scenes doesn't affect it.  Reverting to previous version fixed the issue.  I apologize but I don't know the version number.  It was simply the prior CKAN version.

**Log:**

[KSP.log](https://github.com/LGhassen/Scatterer/files/2981003/KSP.log)

**Mod List:**
KSP: 1.6.1 (Win64) - Unity: 2017.1.3p1 - OS: Windows 10  (10.0.0) 64bit
000_AT_Utils - 1.6.2
ClickThroughBlocker - 0.1.7.1
Filter Extensions - 3.2.2.16
TexturesUnlimited - 1.3.6.20
Toolbar - 1.7.18
USI Tools - 1.1
ToolbarControl - 0.1.6.20
B9 Part Switch - 2.6
BetterTimeWarpContinued - 2.3.11.2
CactEye Telescopes - 1.5.1.15
Chatterer Extended - 0.6.2
Chatterer - 0.9.96.2332
Color Coded Canisters - 2.0.1
Community Category Kit - 4.1
Community Resource Pack - 1.1
CommunityTechTree - 3.3.6
Contract Configurator - 1.27.1
Contract Pack: Bases and Stations - 3.7.1.4
CryoTanks - 1.1.1
AGExt - 2.3.3.8
DistantObjectEnhancement - 1.9.1
DynamicBatteryStorage - 1.4
Easy Vessel Switch - 1.10.6933.41006
Environmental Visual Enhancements - 1.4.2.2
FASA - 7.2.5
Ferram Aerospace Research - 0.15.9.7
Firespitter - 7.12
FTLDriveContinued - 0.2.2
GroundConstruction - 2.2
HeatControl - 0.4.10
HideEmptyTechTreeNodes - 1.1
Reflection Plugin Continued - 2.1.2
Interstellar Fuel Switch - 3.6.18.3
JanitorsCloset - 0.3.4.6
RasterPropMonitor - 0.30.6
KAS - 1.1.6876.38030
Kerbal Engineer Redux - 1.1.5.7
Kerbal Foundries - 2.2.6.16
KerbalKonstructs - 1.4.5.59
HyperEdit - 1.5.8
KerbalKonstructs - 1.4.5.24
Kerbal Inventory System - 1.18.6971.42939
<b><color=#CA7B3C>Kopernicus</color></b> - 1.6.1.2
KSP-AVC Plugin - 1.2.0.7
KSPWheel - 0.14.12.31
MechJebForAll - 1.3.0.5
MemGraph - 1.1.1.5
ModularFlightIntegrator - 1.2.6
NavHud - 1.3.6.2
NearFutureConstruction - 1.0.6
NearFutureElectrical - 0.10.6
NearFutureProps - 0.5
NearFuturePropulsion - 1.1
NearFutureSolar - 0.8.15
NearFutureSpacecraft - 1.0.3
Final Frontier - 1.5.3.3465
PatchManager - 0.0.16.4
PlanetShine - 0.2.6.1
Precise Maneuver - 2.4.1
Procedural Fairings - 1.5.0.5
Procedural Parts - 1.3.16.1
ProceduralStart - 1.0.2
RealChute - 1.4.7.3
RealPlume - Stock - 1.3.1
SCANsat - 1.1.8.10
ScienceAlert - 1.9.6
ShipManifest - 5.2.1
SpaceY Expanded - 1.4
SpaceY Lifters - 1.17.2
StationPartsExpansion - 0.5.3
StationPartsExpansionRedux - 1.1
Stock Visual Enhancements - 1.3.0.4
Surface Experiment Package - 2.7
Surface Mounted Lights - 1.12.7006.42726
Stock Visual Terrain - 2.1.4.1
TextureReplacer - 3.7
ToadicusToolsContinued - 0.22.3.3
Trajectories - 2.2.2
Kerbal Alarm Clock - 3.10
Transfer Window Planner - 1.6.3
<b><color=#ffffff>Tundra</color> <color=#0090ff>Exploration</color></b> - 1.3.0.5
<b><color=#ffffff>Tundra</color> <color=#0090ff>Technologies</color></b> - 0.9.0.4
TweakableEverything - 0.1.26
TweakScale - 2.4.1
USI Core - 1.1
USI Exploration Pack - 1.1
Freight Transport Tech - 1.1
Konstruction - 1.1
Malemute Rover - 1.1
MKS - 1.1
EVAParachutesAndEjectionSeats - 0.1.16
VaporVent - 1.1.9.2
VenStockRevamp - 1.9.5
KSP Interstellar Extended - 1.20.16.3
Waypoint Manager - 2.7.5
[x] Science! - 5.20

**Comment by LGhassen** [comment]
Do NOT use outdated SVE with updated scatterer. Use the version recommended by SVE as it is configured for it. Otherwise remove SVE and use latest scatterer.
