### ISSUE TITLE
Scatterer and FlareReplacer

### ISSUE THREAD

**Issue by Galileo88** [LGhassen/Scatterer#60]
I have a mod that uses kopernicus to change the sun flare. As reported in the forum thread, it used to work fine alongside Scatterer. FlareReplacer uses module manager to set **fullLensFlareReplacement** to **False** so that Scatterer's sun flare is disabled in favor of the FlareReplacer's. However, disabling that in the Scatterer cfg, also disables the Flare Replacer flare in game. There are no errors in the logs so I haven't posted them here. If you need them just let me know and I'll post em for you.

I have tried scatterer in a pure stock install and disabling the sun flare works as expected and gives  the user the stock flare. Only when you add Kopernicus and FlareReplacer does the issue pop up. 

Here is the release page if you want to test it yourself.
[https://github.com/Galileo88/FlareReplacer/releases](url)

Thanks,
Galileo

**Comment by LGhassen** [comment]
Is there a log that says

`[Scatterer] Disabling stock sunflare for "+_flare.sun.name`

**Comment by Galileo88** [comment]
Let me check and Ill get back to you

**Comment by LGhassen** [comment]
I'm closing this due to no followup
