### ISSUE TITLE
Green Sunlight on Eve

### ISSUE THREAD

**Issue by aurum6** [LGhassen/Scatterer#61]
KSP v1.6.1
Scatterer v0.0540
Clean install, no other mods

Log File: [KSP.log](https://github.com/LGhassen/Scatterer/files/2994842/KSP.log)
 
The side of the craft illuminated by the sun has a green tint, even under the midday sun. Shadows on the other side of the vessel are purple, as they should be.

Speculation: If sunlight color is based on how far it's travelling through the atmosphere, then the fact that Eve's atmosphere is thicker than Kerbin's could be the culprit.

![screenshot2](https://user-images.githubusercontent.com/48805696/54776131-13928f00-4bd5-11e9-96e7-a3ae56038b35.png)

**Comment by Galileo88** [comment]
The light should be green. As the sunlight makes its way through Eve's purple atmosphere, it turns green, much like how it turns orange on Earth or Kerbin. Also pay attention to the terminator color. Its a giveaway for what the color will be.

**Comment by LGhassen** [comment]
The thicker atmosphere on EVE is responsible for the light being green already on midday.
