### ISSUE TITLE
[BUG] scatterer kerbin atmosphere dissappears mid-game. shadows and textures show skybox.

### ISSUE THREAD

**Issue by wal310** [LGhassen/Scatterer#63]
mod list: 
-ablative aerobrake
-B9 part switch
-BetterBurnTime
-BetterTimeWarpContinued
-Celestial Body Science Editor
-Click through Blocker
-Community Category Kit
-Community Delta-v map
-Community Reource Pack
-Community Tech Tree
-Cryogenic Engines
-Cryogenic Engines Extras: LFO Patch
-Cryogenic Tanks
-Deployable Engines Plugin
-DMagic Orbital Science
-Dock Rotate
-Docking Port Alignment Indicator
-Dynamic Battery Storage
-EvaFollower
-Haystack ReContinued
-Kerbal Alarm Clock
-Kerbal Engineer Redux
-KIS
-Kerbal Wind Tunnel
-MechJeb 2
-Module Manager
-MOIST! Underwater Technologies
-Near Future Electrical
-Near Future Electrical - Decaying RTGs
-Near Future Electrical Core
-Near Future IVA Props
-Near Future Launch Vehicles
-Near Future Propulsion
-Near Future Propulsion - Xenon Hall Effect Thrust Configs
-Near Future Solar
-Near Future Solar Core
-Near Future Spacecraft
-Near Future Spacecraft - LFO Engines
-Patch Manager
-Probes Before Crew [PBC]
-Progress Parser
-Radar Altitude
-RasterPropMonitor
-RasterPropMonitor Core
-Reentry Particle Effect
-ReStock
-ReStock +
-scatterer
-scatterer - default config
-scatterer - sunflare
-Toolbar Controller
-TriggerAu Flags

Been having issues with scatterer where you can see the skybox and no atmosphere on kerbin. some textures appear as the skybox and usually crashes soon after exiting to space center or going to the VAB etc. I know I have a lot of mods but it doesn't really make sense why it happens so randomly. Sometimes I'm fine playing for an hour before this issue happens but other times it happens as soon as I enter the game. any insight on what mod/thing might be causing this

**Comment by LGhassen** [comment]
Please provide screenshots and look further into reproducing it reliably. Try to narrow it down by removing mods otherwise I can't really help you.

**Comment by LGhassen** [comment]
Closed due to no further info.
