### ISSUE TITLE
Some bodies are semi-transparent and shadows are broken

### ISSUE THREAD

**Issue by gregtofu** [LGhassen/Scatterer#64]
**Issue description**
- Jool and Duna (at least) are partially transparent and show different layers (it's especially visible on Jool)
- Ring and planet shadows are rendering differently on the scatter effect and the planet itself
**Installed mods:** 
Scatterer 0.0540
TextureReplacer
AVP Textures 4K
AVP 3.74
EVE (latest)
Kopernicus & custom-made Jool rings

**Steps to reproduce**
I'm not certain how to reproduce, for some reason it seems to work with other people.
Here's how i get the issue:
-Install all those mods on a stock KSP 1.6.1 (GOG version) with Making History pack
-Go in orbit around Jool OR go on the tracking center

**Screenshots**
[Layering on Jool](https://cdn.discordapp.com/attachments/295199794102796288/565476514779365407/unknown.png) (Note that the ring shadows are offset on the scattering effect)
[Scattering effect on Duna](https://drive.google.com/open?id=14g8JN3Yd_v_ZRXIQyfvEl1lXumSeY0Pv) (Not very noticeable but it makes a sort of ring (pointed by the arrows), i believe it's the same effect on Jool but with multiple layers somehow)
[Shadows](https://drive.google.com/open?id=1NJ-K5_c23fKHIfKHPyJtrE3JN-DwXDDo)

I know a somewhat similar issue has been reported for the ring shadows already, i hope an additional log will help but i can't find either output_log.txt nor player.log

**Comment by LGhassen** [comment]
> Jool and Duna (at least) are partially transparent and show different layers (it's especially visible on Jool)

I fail to see the issue in your screenshots, can you detail/post better screenshots?

> Ring and planet shadows are rendering differently on the scatter effect and the planet itself

This is a known issue for me, and the way I work around it in my Jool config is to make the atmosphere smaller until it's no longer visible. I think my Jool atmosphere "experimental atmo scale" is between 0.5 and 1, which gets rid of it/makes it more bearable, please take a look at my stock configs.

**Comment by LGhassen** [comment]
Scattering artifacrs arw now fixed
