### ISSUE TITLE
Atmosphere for Kerbin really buggy

### ISSUE THREAD

**Issue by fruitsbar** [LGhassen/Scatterer#65]
the atmosphere keeps flickering at 150000 altitude.

**Comment by LGhassen** [comment]
Screens? Video? Please look here how to report a bug

https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip161-scatterer-atmospheric-scattering-v00540-17032019-fixed-tsunami-bug-11/ (how to report issues section)

**Comment by LGhassen** [comment]
Closed due to lack of info and reproducibility.
