### ISSUE TITLE
Scatterers atmosphere breaks when under a certain altitude

### ISSUE THREAD

**Issue by iGGnite** [LGhassen/Scatterer#66]
This is the worst bug I have encountered with scatterer so far and it really ruins the beautiful effect scatterer usually has. (Notice the altimeter in the screenshots) 
[KSP.log](https://github.com/LGhassen/Scatterer/files/3076309/KSP.log)

![screenshot11](https://user-images.githubusercontent.com/36937528/56081042-08640500-5e09-11e9-9885-e302da125909.png)
![screenshot12](https://user-images.githubusercontent.com/36937528/56081043-08640500-5e09-11e9-8b43-ff0932ebddc1.png)

**Comment by LGhassen** [comment]
Which rescale mods?

**Comment by iGGnite** [comment]
Sigma Dimensions

**Comment by LGhassen** [comment]
Check out this post:

https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip161-scatterer-atmospheric-scattering-v00540-17032019-fixed-tsunami-bug-11/&do=findComment&comment=3593265

Technically a bug, but with the current blending mode and the game's camera limitations, there seems to be no proper way to fix it. The forum post there proposes 2 workarounds.

**Comment by LGhassen** [comment]
I think I could fade in the scaledSpace scattering on areas that are outside the localSpace scattering camera's frustum.

I will take a stab at it. Can you remind me in 1 month if I don't come back?

**Comment by iGGnite** [comment]
Hey, here is the relevant youtube link with the player and output_log log
https://youtu.be/rv_Ac79FazQ
https://www.dropbox.com/sh/2a0mhwi5x2w2sz5/AADE7ZBSI9RPQHkU9Z4DLfeAa?dl=0

**Comment by iGGnite** [comment]
Hello, it's been a month so here I am to remind you

**Comment by LGhassen** [comment]
@iGGnite sorry this didn't make the cut for current release (wasn't working correctly), I will try again soon. Can you remind me in 2 weeks if I don't show up with a fix?

**Comment by iGGnite** [comment]
It has been 15 days so I'm reminding you!

**Comment by iGGnite** [comment]
22 days!

**Comment by iGGnite** [comment]
32 days!

**Comment by LGhassen** [comment]
@iGGnite you will be happy to know that this is now fixed in 0.0722. Enjoy

**Comment by iGGnite** [comment]
THAT IS SO EPIC! In the Christmas holiday, I´ll have some time to enjoy it! Thank you so much!
