### ISSUE TITLE
Planet rings cast very buggy shadows if they are lined up exactly with light source

### ISSUE THREAD

**Issue by MiracleMagician** [LGhassen/Scatterer#67]
https://i.imgur.com/jCawuPx.jpg
https://i.imgur.com/NqJI7i0.jpg

KSP: 1.7.0
Mods installed: The World Beyond, Kopernicus, Scatterer 0.0540
Reproduction steps: Set both the planet's orbit inclination and ring angle as 0

By the way is there a way to completely disable rings' shadow on planets? I don't want to lost the planet's beautiful rings before this glitch is fixed...

**Comment by LGhassen** [comment]
I will try to fix it, in the meantime, to disable them.

In the scatterer config.cfg file:
`useRingShadows = False`

**Comment by MiracleMagician** [comment]
Sorry for asking you that, I didn't noticed that config back then...

**Comment by LGhassen** [comment]
This is fixed in the latest release.
