### ISSUE TITLE
Sunflare not visible with B9PartSwitch parts

### ISSUE THREAD

**Issue by ncanceill** [LGhassen/Scatterer#69]
**Description**
Scatterer's sunflare (`fullLensFlareReplacement`) is not visible out of atmosphere when flying a vessel with B9 Part Switch parts

Running KSP 1.7.0.2483 (Windows x64) with DirectX3D11 and the following (maybe) relevant mods:
- B9 Part Switch 2.7.1
- EVE 1.4.2-2
- Kopernicus 1.7.0-1
- Scatterer 0.0540

Scatterer config:
```
@Scatterer_config:AFTER[Scatterer]
{
    @autosavePlanetSettingsOnSceneChange = False
    @disableAmbientLight = True
    @integrateWithEVEClouds = True
    @overrideNearClipPlane = False
    @nearClipPlane = 0.209999993
    @useOceanShaders = True
    @shadowsOnOcean = True
    @oceanSkyReflections = True
    @oceanPixelLights = False
    @fullLensFlareReplacement = True
    @sunlightExtinction = True
    @underwaterLightDimming = True
    @showMenuOnStart = False
    @useEclipses = True
    @useRingShadows = True
    @terrainShadows = False
    @shadowNormalBias = 0.720000029
    @shadowBias = 0.5
    @shadowsDistance = 100000
    @m_fourierGridSize = 64
}
```
 
**How to reproduce**
Load a vessel out of atmosphere from save or Tracking Station with B9 Part Switch parts

**Additional info**
This happens with any visual pack (AVE, SVE, Spectra, Sunflares of Maar) and with Scatterer's default sunflare
These visual packs use Kopernicus to disable the Stock sunflare, which results in no sunflare being visible at all
Interestingly enough, the following sequence is consistently reproducible:
- Load a vessel from the VAB/SPH or the LaunchPad/Runway with B9 Part Switch parts
- Hit Escape to pause the game after the scene change but before graphics load (screen still black, but Blizzy's Toolbar has moved from the VAB/SPH position to the Flight position)
- Notice that when the graphics load and the pause menu appears, the sky remains black (indicating Scatterer is not fully loaded?)
- Hit Alt+F12 to open the ingame console and put the vessel in Kerbin orbit (above the atmosphere), then hit Escape to unpause the game
- Notice that Scatterer's sunflare (either default or custom) is visible
- Exit to space center and the go back to the vessel
- Notice that Scatterer's sunflare is not visible anymore

**Root cause**
I have no idea whether the problem originates in B9 Part Switch or Scatterer. I have no idea whether this is fixable in Scatterer or not
I see that similar issues have been brought up in the forum thread and I have posted this one there too

In my case, I observe a NullRef on a DepthToDistanceCommandBuffer caused (according to the stack trace) by a call to RenderProceduralDragCubes from B9 Part Switch, which causes Scatterer to give up (`[Scatterer] Removing DepthToDistanceCommandBuffer`) and fail to display the sunflare
I suppose the NullRef could be happening [here](https://github.com/LGhassen/Scatterer/blob/master/scatterer/Core.cs#L423-L427) but I do not know the code and sadly I do not have the dev environment set up to recompile/debug it

---

I have reverted to the Stock sunflare for now (albeit with Kopernicus), but if anyone has suggestions I am open to trying things in order to track down the root cause further.

PS: Hi @LGhassen and thanks for the great mod!

**Comment by ncanceill** [comment]
Well... I have been editing my visual (EVE/Kopernicus/Scatterer) config quite a lot, and now I just tried to reproduce the bug but could not

So this appears to be fixed for me now, I will post back here if it comes back

**Comment by LGhassen** [comment]
@ncanceill Can you check if this persists in the latest release?

**Comment by KZdavid** [comment]
It seems that when using customize parts like procedual parts, B9 wings, sunflare will disappear when exit the atmosphere. And the sunflare only disappear in flight view rather than mapview. I have the same problem with KSP 1.7.3 with all RP-1 mods. It seems to be a normal problem with RP-1, since every player I know have this problem. The sunflare does not always disappear. Reload the vessel after returning back to the KSC may fix the problem.
Here's what it looks like. You may refer to this video:
https://www.bilibili.com/video/av540359528 at 6:42. The tiny white point is the sun.
Here's what I guess:
In flight view, sunflare only shows up when the sun is not block by the vessel. However, we need to get the size of the vessel to decide whether to display the sun flare. I notice that when the sunflare does display with these custmize parts, they disappear when the sun is not block by the vessel but only near it. I guess scatterer mistake the size of the vessel.

**Comment by LGhassen** [comment]
Sorry guys but you have to test this with 1.8.x-1.9.x with the latest version of scatterer (0.0600).

**Comment by orbuno** [comment]
KZdavid
 

> Кажется, что при использовании настраиваемых деталей, таких как процедурные детали, крылья B9, солнечный свет исчезнет при выходе из атмосферы. И солнечный свет исчезает только при виде полета, а не при просмотре карты. У меня такая же проблема с KSP 1.7.3 со всеми модами RP-1. Кажется, это нормальная проблема с RP-1, так как у каждого игрока, которого я знаю, есть эта проблема. Солнечный свет не всегда исчезает. Перезагрузить судно после возвращения обратно в KSC может решить проблему.
> Вот как это выглядит. Вы можете обратиться к этому видео:
> https://www.bilibili.com/video/av540359528 в 6:42. Крошечная белая точка - это солнце.
> Вот что я думаю:
> При виде полета солнечный свет появляется только тогда, когда судно не блокирует солнце. Однако нам необходимо определить размер сосуда, чтобы решить, отображать ли солнечную вспышку. Я замечаю, что, когда солнечный свет действительно появляется с этими частями, они исчезают, когда солнце не блокирует судно, а только около него. Я предполагаю, что рассеиватель ошибся в размере судна.


Answer:
Hi, try changing the values : 
sunGlareFadeDistance = 20000000   (necessarily)
ghostFadeDistance = 100000000   (not necessary, but possibly required)
in the file ...\Kerbal Space Program\GameData\scatterer\config\Sunflares\Sun.cfg
It works for KSP 1.8.1

**Comment by LGhassen** [comment]
Closing this due to no followup on the latest versions.
