### ISSUE TITLE
PPFX breaks ocean shaders

### ISSUE THREAD

**Issue by DuoDex** [LGhassen/Scatterer#7]
With PPFX turned on, OpenGL/Linux, ocean shaders refuse to load, displaying a black surface instead.

![Ocean Shaders Derp](http://i.imgur.com/LwYq17X.png)

With PPFX turned off, viewing from the top down causes ocean shaders to unload again, but this goes away when viewed from any angle.

![Top Down](http://i.imgur.com/995B9bN.png)

**Comment by LGhassen** [comment]
The top down disabling is a separate issue. I'll look into the PPFX thing.

**Comment by DuoDex** [comment]
Upon further testing, it was discovered that spamming the "apply" button in-flight on the graphics settings eventually resulted in success.

**Comment by SilverWingedSeraph** [comment]
I get the same symptoms without PPFX on: 
![screenshot257](https://cloud.githubusercontent.com/assets/3290365/11579013/2c113ac8-99df-11e5-8bad-ad0a78867295.png)
![screenshot258](https://cloud.githubusercontent.com/assets/3290365/11579014/2c131de8-99df-11e5-8858-73d59067716e.png)
![screenshot259](https://cloud.githubusercontent.com/assets/3290365/11579015/2c1422a6-99df-11e5-81ac-06bdf167bb89.png)
![screenshot260](https://cloud.githubusercontent.com/assets/3290365/11579016/2c1435c0-99df-11e5-8b85-f60d7f7a8603.png)

**Comment by DuoDex** [comment]
So, apparently spamming the "Apply" button on the graphics page can actually affect how/whether the shaders are rendering. Dunno why, and PPFX doesn't seem to have much to do with it.

**Comment by LGhassen** [comment]
SilverWingedSeraph could you try it?

**Comment by SilverWingedSeraph** [comment]
@LGhassen Spamming "Apply" works intermittently, but even when the shaders are on I get this effect:

![screenshot282](https://cloud.githubusercontent.com/assets/3290365/11581484/64d5642a-99f7-11e5-802e-737a86cd3866.png)
![screenshot283](https://cloud.githubusercontent.com/assets/3290365/11581485/64d7d53e-99f7-11e5-8838-2b3257c03113.png)

FYI, I'm on a GTX 680 with the most recent nVidia drivers.

**Comment by JustMaximumPower** [comment]
I'm also a affected by the same bug:
![2015-12-07_00005](https://cloud.githubusercontent.com/assets/243302/11666615/ac0dc2de-9ded-11e5-9ec9-0e06d51d51c7.jpg)

Linux with NVIDIA 358.16 GTX 970
Is it possible this bug is Nvidia specific? I can test on Intel later.

**Comment by JustMaximumPower** [comment]
So on Intel mesa 11.2-git ksp crashes when going ingame maybe I can get it to work later. But I can say for sure that my laptop with GT 755M has the same problem also with NVIDIA 358.16. Has anybody gotten scatter to work on linux + Nvidia? If yes what is the driver version?

**Comment by politas** [comment]
I've got NVidia GT960, running 352.41 drivers, and it's all broken for me. Completely ruins the imagery when in orbit.

**Comment by LGhassen** [comment]
Does this still happen on the newest version?

**Comment by politas** [comment]
No, I get different symptoms with the latest version. Launching anything from inside the atmosphere seemed fine, but when I go to a craft in flight, the skybox shows scattered blue light and both the orbited body and my craft don't appear. (Tested for ships in orbit around Kerbin and the Mun)

**Comment by LGhassen** [comment]
I released a fixed version yesterday.

**Comment by politas** [comment]
Ah, I haven't tried that. I'll give it another go.

**Comment by politas** [comment]
The ocean shaders issue certainly seemed fixed in the previous version.

**Comment by DuoDex** [comment]
Fixed on all platforms for me.
