### ISSUE TITLE
Black Sky, Disappearing Ocean, and Infinite Loading Screen

### ISSUE THREAD

**Issue by maxyac** [LGhassen/Scatterer#70]
Before I begin, here is my modlist:
B9 Aerospace
BDArmoryContinued
Distant Object Enhancement
Docking Port Alignment Indicator
Environmental Visual Enhancements
Ferram Aerospace Research
Firespitter
Kerbal Alarm Clock
Kerbal Attachment System
MechJeb 2
ModularFlightIntegrator
Module Manager
Physics Range Extender
PlanetShine
RasterPropMonitor
SmokeScreen - Extended FX Plugin
Texture Replacer Replaced
Transfer Window Planner

All of the above (except for EVE) were installed manually.

KSP Version: 1.7.3.2594
(I'm new to KSP modding. I really enjoy how these mods improve the experience, but please do let me know if any conflict and may cause issues.)

My specs:
i7 7700k, Z270 Mobo
1080ti
16GB 2400MHz RAM
2 512GB SSDs in RAID 0

So it seems that the black sky bug that apparently happens often with Scatterer is happening to me, but with even more issues on top of that. Here is how playing KSP goes for me atm:

1) The game loads, looks great and works just fine when I first load in. Loading into anything a second or third time seems to work well too (i.e. loading into VAB and then launching pad).

2) It seems that after the fourth loading screen or the second time loading into the space center screen, I load in okay but I'm presented with a black sky with clouds and an ocean with no water (I just see a blue surface where I assume the bottom would be).

3) After entering any other loading screen (i.e. into VAB again or to take control of a flight), the game stutters as it normally would during loading and then the little rotating loading indicator starts moving again. Then:

4) The loading screen never finishes and I am forced to force quit the game. This happens **unless** I press ESC to open the pause menu, which seems to close the loading screen and open up whatever instance I was loading into. This only works with 3D instances like VAB.

5) If it was a 3D instance and I pressed ESC during the last step, I am now in the game completely unable to move my camera while still having the black sky and missing ocean.

I am tired of searching for solutions. I've spent hours looking stuff up that might be related to my issue but have never seen the disappearing ocean and infinite loading screen part online. I'm assuming a screwed up mod installs somehow, but I've tried many things like: 
- reinstalling visual mods 
- verifying game integrity on Steam
- disabling certain mods
yet the problem persists. I have tried disabling Scatterer and this did fix the black sky, but it caused a tsunami bug and didn't change the infinite loading screen behavior. I honestly don't even know if it fixed the black sky, as my game behaved the exact same except a darker blue sky came in when the fully black sky would have with Scatterer installed.

I'm desperate at this point. I want to play this game with mods but I guess I will have to go without until anyone can give me any suggestions. Thanks.

**Comment by LGhassen** [comment]
I'm closing this issue since it's unrelated to scatterer
