### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by YaroslavMelnychenko** [LGhassen/Scatterer#71]
White screen sometimes in orbit. KSP version 1.7.0.2483. Scatterer the last version

![20190929161538_1](https://user-images.githubusercontent.com/34866427/65833109-21884180-e2d5-11e9-9b6a-ef12c158223d.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/34866427/65833134-6f9d4500-e2d5-11e9-98b6-83ef84b855be.png)

**Comment by LGhassen** [comment]
@YaroslavMelnychenko does this still happen with the latest version?

**Comment by LGhassen** [comment]
Closed due to lack of information and reprocibility.
