### ISSUE TITLE
option to enable ground scatter atmospheric depth effects

### ISSUE THREAD

**Issue by KSAMissionCtrl** [LGhassen/Scatterer#73]
Knowing it will be a performance hit, allowing trees and other ground scatter objects to appear to haze out in the distance

https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip161-scatterer-atmospheric-scattering-v00540-17032019-fixed-tsunami-bug-11/page/318/&tab=comments#comment-3632152

**Comment by LGhassen** [comment]
@KSAMissionCtrl depth effects are now enabled for them with no performance hit. Check out the pre-release version: https://github.com/LGhassen/Scatterer/releases/tag/0.0767
