### ISSUE TITLE
[0.0541] Issue with ocean shaders

### ISSUE THREAD

**Issue by ThijmenDF** [LGhassen/Scatterer#74]
Noticed there's a 'ghost' version of my ship in the water. Water foaming seems to be effected by it. Only a minor visual bug I suppose.

![Screenshot 2019-10-26 11 36 49](https://user-images.githubusercontent.com/2705853/67617632-4fce4380-f7e5-11e9-8066-043509277634.png)  
![Screenshot 2019-10-26 11 36 33](https://user-images.githubusercontent.com/2705853/67617633-4fce4380-f7e5-11e9-9feb-8962180566a2.png)

**Comment by LGhassen** [comment]
Looks like the depth map is flipped.

Please post:
-Graphics API you're using (D3D9, D3D11, opengl, etc...)
-Ingame anti-aliasing setting
-Operating system

**Comment by ThijmenDF** [comment]
Graphics API I'm guessing D3D11? Not sure how to check. GPU is Nvidia GeForce GTX 1070.
AA is set to x8
OS is windows 10 x64

**Comment by LGhassen** [comment]
Find you KSP.log file, look for a line that says something like this
`[Scatterer] Running on Direct3D 11.0 [level 11.1] on Windows 10  (10.0.0) 64bit`

**Comment by ThijmenDF** [comment]
Yep it's D3D11: [Scatterer] Running on Direct3D 11.0 [level 11.1] on Windows 10  (10.0.0) 64bit

Btw, I've noticed on another mission the 'shape' in the water represented the full launch vehicle and not just the part that splashed down.

**Comment by LGhassen** [comment]
Should be fixed in 0.0767: https://github.com/LGhassen/Scatterer/releases/tag/0.0767
