### ISSUE TITLE
[BUG] Terrain and vessel glitches

### ISSUE THREAD

**Issue by jevk** [LGhassen/Scatterer#76]
Note: Sorry for bad grammar and punctuation English isn't my main language.

So, when I have scatterer installed I get these weird terrain glitches and some other wicked stuff. What I'm trying to say is; very often when I land on a celestial body or start descending altitude towards it, the terrain separates in different "chunks" of different shapes. After that, the "chunks" raise suddenly up about 100 meters at the same time. I hate this bug, because I get scared every time I land. The vessel glitches aren't that common but they are very common too. The vessel glitches are very annoying because it either launches it randomly to very fast speeds or then summons the same ship inside the ship I'm flying, which causes the vessel to blow up mid-air. Can you please fix this, the version is 1.8. And before anyone asks, yes, I have tested this without the mod for long periods of time and reinstalling it too.

Image: Random launch to the high speeds.
![screenshot40](https://user-images.githubusercontent.com/58623854/70372422-60470300-18e7-11ea-9046-ca549a7428b7.png)

Image: Terrain glitches.
![ScattererGlitch](https://user-images.githubusercontent.com/58623854/70372484-3d691e80-18e8-11ea-8f2d-3a491b14f5d6.PNG)

Specs:
GPU: GTX 1060 6Gb
CPU: AMD Ryzen 5 1600
RAM: 8Gb+8Gb DDR4
PSU: CX650M
MB: MSI B350M Mortar
Game installed on a SATA SSD.

**Comment by LGhassen** [comment]
I'm going to need a procedure to reproduce these 100% of the time. I couldn't reproduce either of these bugs.

**Comment by jrodrigv** [comment]
I think this is not a Scatterer issue but a LMP issue.

**Comment by LGhassen** [comment]
Alright, thanks @jrodrigv
