### ISSUE TITLE
Reload/Load issues

### ISSUE THREAD

**Issue by DuoDex** [LGhassen/Scatterer#8]
Scatterer appears to be toggled during save/reload scenarios on Linux/OpenGL.

Looks like this when it's off.

![Toggled Off](http://i.imgur.com/65gioUr.png)

**Comment by SilverWingedSeraph** [comment]
This is for a similar reason, I think, as the reason that spamming Apply in the in-scene graphics menu as noted in #7

**Comment by LGhassen** [comment]
Does this still happen with latest dev .dll?

https://github.com/LGhassen/Scatterer/raw/a6ae4b4e2d6ffb254d444876388896dc5617951c/scatterer/bin/Release/scatterer.dll
