### ISSUE TITLE
Orbit decay contingent on camera angle

### ISSUE THREAD

**Issue by gtstraub** [LGhassen/Scatterer#82]
KSP: 1.8.1 Windows 10 64bit
Problem: When in LKO and camera is aimed more or less straight at Kerbin center (i.e. Kerbin occupies > 50% of the screen), SMA of 86.7km circular orbit decays at a rate of 5m/minute.  Rotating the camera angle slows or effectively stops the decay; when pointed away from Kerbin rate decays at about 1m/35 minutes.  

Mods installed:
https://www.dropbox.com/s/g1f2wv2io528d5u/KSP%20Mods%20v2.txt?dl=0

Reproduction steps:

Started new sandbox save, put single pod in orbit at 86.7km with console and KER up.  Aim camera at Kerbin.  Tried with default settings with a variety of mod combinations including with AVP and Spectra and with scatterer and as standalone on fresh install and new save with same results.  Removing scatterer and leaving rest of the mods eliminates the issue.

Log:
https://www.dropbox.com/s/bbqdysbpx4fh9kg/output_log.txt?dl=0

**Comment by LGhassen** [comment]
Can you compare a stock only game and a stock+scatterer only? I have a bit of trouble believing scatterer is causing this.

**Comment by gtstraub** [comment]
Yes indeed, I was quite skeptical myself which is why the visual mods were the last thing I tried.  I did some more testing this morning with a clean install.   By the way, Orbital Drift Compensation is on in the settings for all these cases:

Stock: Very small decay ~1m/30mins
Stock+KER+Scatterer: Same as stock
Stock+KER+Scatterer+Spectra pack: 5m/1min decay
Stock+KER+Scatterer+AVP pack: 5m/1min decay
Stock+KER+Spectra pack (no scatterer): Same as stock
Stock+KER+Spectra+scatterer (no EVE): Same as stock
Stock+KER+scatterer+EVE+Spectra EVE configs and textures only: 5m/1min decay

So it would seem to be some interaction between EVE when configured for these packs and scatterer since removing either one returns to the decay to the almost imperceptible stock level.  

I made a short video for this and I stumbled across something else... 
https://www.youtube.com/watch?v=XvVGJd1sj-w

The video is at my default 3440x1440 in fullscreen mode to demonstrate the bug.  After that video I decided to make one in 1920x1080 Windowed.... and the bug disappeared, with the exact same configuration (scatterer+EVE+Spectra EVE configs and textures only).  I went then to 1920x1080 Fullscreen and it returned, and was also there in 3440x1440 Windowed.  Now I'm even more confused.

**Comment by LGhassen** [comment]
I'm still skeptical honestly, I would guess that the more your system is under load, the more an existing issue with KSP code is exacerbated.

**Comment by gtstraub** [comment]
Well after basically 2 days of fooling around with mods, 1.9 drops and seems to have fixed this issue.  Even with all the mods installed (minus a couple that were causing outright crashes), orbit change is present but even so small I'm not even going to bother to let it run to measure it, so thanks for giving it a look anyway.

**Comment by LGhassen** [comment]
@gtstraub is scatterer working for you on 1.9? Which version of scatterer are you using? Which video mode?
