### ISSUE TITLE
NullReferenceException and massive FPS drop on mk.2 lander can

### ISSUE THREAD

**Issue by joonoro** [LGhassen/Scatterer#84]
![log](https://user-images.githubusercontent.com/5191426/74592337-cf984c00-5028-11ea-81db-d1e9b8ec489c.jpg)

v0.0541, KSP 1.8.1.2694

steps to reproduce:

1. place mk.2 lander can in VAB and launch
2. right click the can
3. click "open door"
4. FPS drops to single digits and above errors appear in log

**Comment by LGhassen** [comment]
Fixed in the latest release
