### ISSUE TITLE
Blue halos around lights(landing gear and space center)

### ISSUE THREAD

**Issue by jkerman2000** [LGhassen/Scatterer#88]
KSP: 1.8.1 Windows 64bit
Problem: All lights on the space center, as well as landing gear, have these blue halos around them. It seems like the scattering is messing with the alpha transparency of the lightglow textures.

Mods installed:

Scatterer 0.0541

EnvironmentalVisualEnhancements 1.8.1

KS3P

Kopernicus

RealPlume

TexturesUnlimited

SmokeScreen

Spectra

SmokeScreen

TextureReplacer

Firespitter

Reproduction steps:

With all shaders enabled, simply start a flight on the runway, you'll see the halos on the runway lights.

Log:

https://drive.google.com/file/d/1oiQO_D4KZEel0UgWNLuc6xpfYSiKMUWd/view?usp=sharing

**Comment by LGhassen** [comment]
As I responded on the forum thread: I had a fix for these but for some reason those lights override my fix. What you can do is modify the config for the lowest configPoint in your scatterer atmosphere and increase the postProcessingDepth to something like 0.4 or 0.8, should hide it.

Other than that, no "correct" fix for these now, only that workaround.

**Comment by LGhassen** [comment]
Should no longer be an issue in 0.0767 with the new depth buffer mode: https://github.com/LGhassen/Scatterer/releases/tag/0.0767
