### ISSUE TITLE
Telescope Mods Incorporate Scatters

### ISSUE THREAD

**Issue by DuoDex** [LGhassen/Scatterer#9]
![Pics Posted](http://i.imgur.com/AxO3RAt.png)

**Comment by JPLRepo** [comment]
Hmm, interesting. Noticed you are using my TST mod. So thought I'd chime in. I don't get that effect...
![2015-12-04 13_27_06-kerbal space program](https://cloud.githubusercontent.com/assets/9981382/11580363/d5e08260-9a8a-11e5-9398-3760e5da36d2.png)

**Comment by DuoDex** [comment]
Are you on Linux/OpenGL? I'm running a GTX 960 and also using SVE, that might be it.

Also saw this effect with the CactEye telescopes, so I don't think it's a problem on your end.

**Comment by JPLRepo** [comment]
Windows 7, NVIDIA GeForce GTX 775M

**Comment by DuoDex** [comment]
I'd suggest trying again in OpenGL?

**Comment by LGhassen** [comment]
This should be partially fixed in the newest release, everything will work fine in scaledSpace and the effects shoud display correctly with telescopes. However when PQS is active, the postprocessing shader might still interfere with them.

**Comment by Sigma88** [comment]
hi, I was about to open a new issue but I guess this can do for me.

I am trying to write a mod that needs to use a Camera to capture the outside of KSC

when I try to get the atmosphere, stock uses layer 9 but scatterer doesn't use that so the atmosphere image I get is plain black

I thought [scatterer was using layer 23](https://github.com/LGhassen/Scatterer/blob/ddbaecc1a751db0393701eab1699e06c8f988556/scatterer/Effects/DynamicLoaded/Atmosphere/SkyNode.cs#L330), however if I try to use that layer, I don't get any atmosphere.

@LGhassen  could you please point me in the right direction?

thanks

**Comment by LGhassen** [comment]
Hi, in the latest release it's back to layer 15 in local and layer 10 in scaledSpace, so try that.

**Comment by Sigma88** [comment]
Ok so I can leave my code on level nine and it will be automatically fixed I assume

**Comment by LGhassen** [comment]
Try with layer 15 for the moment to confirm that's what's wrong and not something else.

**Comment by Sigma88** [comment]
yes layer 15 is the one, however it won't work for me because that contains the PQS as well.

also, it seems like layer 15 has different non aligned elements while having scatterer installed

**Comment by Sigma88** [comment]
Ok Thanks!

**Comment by LGhassen** [comment]
Fixed in latest version
