### ISSUE TITLE
Crash in 1.8.1 on scene change

### ISSUE THREAD

**Issue by Tonas1997** [LGhassen/Scatterer#90]
**KSP:** 1.8.1.2694 Windows x64

**Problem:** crash on scene change (space center to flight)

**Mods installed:**
Stock assembly: Assembly-CSharp v0.0.0.0
Scale_Redist v1.0.0.0 / v2.4.3.11
ModuleManager v4.1.3.0
ClickThroughBlocker v0.1.9.5 / v1.0.0.0
FilterExtensions v3.2.4.2 / v1.0.0.0
BlendshapeModelLoader v1.0.0.0
TexturesUnlimited v0.0.0.0
aaa_Toolbar v1.8.0.5
USITools v1.0.0.0
ToolbarControl v0.1.9.4 / v1.0.0.0
SolverEngines v3.3.0.0 / v3.7.5.0
AJE v2.15.0.0
ASETPropsIdentifier v1.5.0.0
B9AnimationModules v1.6.0.0 / vv1.6.0
B9PartSwitch v2.13.0.0 / vv2.13.0
B9_Aerospace_WingStuff v0.93.0.0 / v0.93
BetterBurnTime v1.0.0.0
Chatterer v0.9.98.2686
CCK v5.0.0.0 / v4.1.0.0 for KSP 1.6.0
CLSInterfaces v2.0.0.3
ConnectedLivingSpace v2.0.0.3
ContractConfigurator v1.0.0.0 / v1.28.0
CustomPreLaunchChecks v1.0.0.0 / v1.8.1.0
KerbalKonstructs v2.0.0.0 / v1.8.1.15
KerKonConConExt v1.0.0.0 / v1.28.0
SimpleBoiloff v0.2.1.0
CustomBarnKit v1.1.20.0
DeployableEngines v2.2.0.0
DistantObject v1.9.1.29406
DMagic v1.4.3.0 / vv1.4.3.0
DMModuleScienceAnimateGeneric v0.22.0.0
ContractParser v1.0.9.0 / vv9.0
ProgressParser v1.0.11.0 / vv11.0
ContractsWindow v1.0.9.4 / vv9.4
ContractsWindow.Unity v1.0.9.4
DynamicBatteryStorage v1.0.0.0
EngineGroupController v1.0.0.0
UnityGUIFramework v1.0.0.0
EngineLightRelit v1.6.2.3 / v1.0.0.0
Atmosphere v1.8.0.2
CelestialShadows v1.8.0.2
CityLights v1.8.0.2
EVEManager v1.8.0.2
PartFX v1.8.0.2
PQSManager v1.8.0.2
ShaderLoader v1.8.0.2
Terrain v1.8.0.2
TextureConfig v1.8.0.2
Utils v1.8.0.2
_BuildManager v1.8.0.2
Launchpad v6.7.0.0 / v6.7.0
ModularFlightIntegrator v1.0.0.0 / v1.2.7.0
FerramAerospaceResearch v0.15.11.4
ferramGraph v1.3.0.0
Scale_Redist v1.0.0.0 / v2.4.3.11
Firespitter v7.3.7287.12431
FShangarExtender v3.6.0.0 / v3.5.0.0
FTLDriveContinued v0.2.3.1 / v1.0.0.0
HideEmptyTechTreeNodes v1.0.0.0
HullCamera v0.2.0.0
InterstellarFuelSwitch v3.14.2.5
JanitorsCloset v0.3.6.1 / v1.0.0.0
RasterPropMonitor v0.31.3.27057
KAS-API-v2 v2.0.7239.35367 / vKAS API v2
KAS v1.5.7239.36651 / v1.5 for KSP 1.8+
KSPDev_Utils.2.0 v2.0.7231.38433 / v2.0 for KSP v1.8+
KerbalConstructionTime v1.4.7.13
KerbalEngineer v1.1.7.1
KerbalEngineer.Unity v1.0.0.0
0Harmony v1.2.0.1
KerbalismBootstrap v3.7.7356.29312 / v3.7
KerbalJointReinforcement v3.4.1.0
DeployableAeroSurfaces v1.0.0.0
KerbalStats v3.1.0.0 / v3.1.0
HyperEdit v1.5.8.0 / v1.5.8
KIS v1.24.7279.41031 / v1.24 for KSP 1.8+
KSPDev_Utils.2.1 v2.1.7279.39857 / v2.1 for KSP v1.8+
Kopernicus.Parser v1.0.0.0
Kopernicus v1.0.0.0
ICSharpCode.SharpZipLib v0.86.0.518 / v0.86.0
kOS v1.2.1.0
kOS.Safe v1.2.1.0
KronalUtils v0.1.1.0 / v1.0.0.0
KSCSwitcher v1.8.0.0
KSP-AVC v1.4.1.4
KSPWheel v0.0.0.0
MagiCore v1.3.2.3 / v1.0.0.0 / v1.3.1.0
InfernalRobotics v2.0.13.0
Scale_Redist v1.0.0.0 / v2.4.3.11
MechJeb2 v2.5.1.0 / v / v2.9.2.0
DockingPortAlignmentIndicator v6.8.5.1
DPAI_RPM v1.0.0.1
ModuleDockingNodeNamed v1.0.0.1
NearFutureElectrical v1.0.0.0
NearFutureExploration v0.4.0.0
NFPropUtils v1.0.0.0
NearFuturePropulsion v0.9.0.0
NearFutureSolar v0.4.0.0
PatchManager v0.0.17.1 / v1.0.0.0
PersistentRotation v1.3.1.0
Interstellar_Redist v1.3.0.0
PhotonSail v1.5.0.5
Scale_Redist v1.0.0.0 / v2.4.3.11
PhysicsRangeExtender v1.17.0.0
PlanetarySurfaceStructures v1.6.10.0
PreciseManeuver v2.4.4.0 / v / v2.4.4
PreciseManeuver.Unity v2.4.4.0
ProceduralFairings v1.8.1.0
ProceduralParts v2.0.0.0
RCSBuildAid v0.10.0.0
RealAntennas v1.1.0.0
RealChute v1.4.7228.28356 / v1.4.7.5
RealFuels v12.8.4.11 / v12.8.4.11-c9fa
TestFlightAPI v1.0.7347.3151
TestFlight v0.4.0.0
TestFlightRF v1.0.7338.19661
RealHeat v5.1.0.0
RealismOverhaul v0.12.8.1
RealSolarSystem v0.18.0.0
ReentryParticleEffectRenewed v1.8.1.0
DeepFreeze v0.27.0.0
ProgressiveCBMaps v0.1.29.0
ResearchBodies v1.11.0.0
ROEngines v0.0.0.0
ROLib v1.0.0.0
RSSTimeFormatter v1.6.1.0
RSSVE v1.7.3.2594 / v1.7.3.1
SCANsat v1.8.14.0 / vv18.14
SCANmechjeb v1.8.14.0 / vv18.14
SCANsat.Unity v1.8.14.0
scatterer v0.0.0.0
SmokeScreen v2.8.13.0
Stock assembly: KSPSteamCtrlr v0.0.1.35
SSTUTools v0.0.0.0
HabUtils v1.0.0.0
TarsierSpaceTech v7.9.0.0
TestFlightContracts v1.0.7347.3149
TestFlightCore v1.0.7347.3151
TextureReplacer v4.1.1.35052
BetterTracking v1.0.5.0 / v5.0
BetterTracking.Unity v1.0.5.0
TrajectoriesBootstrap v1.0.0.0
KerbalAlarmClock v3.12.0.0
TransferWindowPlanner v1.7.2.0
KSPe.Light.TweakScale v2.1.0.17
Scale v2.4.3.11
VaporVent v1.1.10.0 / v1.0.0.0
Interstellar v1.25.13.5
Interstellar_Redist v1.3.0.0
ZeroMiniAVC v1.1.0.1

**Steps to reproduce:** unclear. I was able to successfuly launch a couple of times (3~4) before the game crashed. Log seems to point out to some unforseen exception inside findCelestialBodies(). I suspect ResearchBodies might have something to do with this.

**Log:** [error.log](https://pastebin.com/Q5kPEvue)

**Comment by LGhassen** [comment]
It is crashing on a Core unity method (UnityEngine.CoreModule) UnityEngine.Object.FindObjectsOfType()). Sorry but this is out of my depth and it is more likely to be a unity issue or some kind of mono issue. Unity objects are also not thread-safe and it might be, although unlikely, that some other thread is trying to access them at the same time (my uneducated guess).

All I can suggest is to try narrowing it down by removing mods.

**Comment by Tonas1997** [comment]
Just stopping by to let you know that the crash happened again, yielding the exact same trace. I'll try to play without ResearchBodies and see what happens.

**Comment by LGhassen** [comment]
@Tonas1997 did you find anything?

**Comment by Tonas1997** [comment]
Yes, sorry for not giving an update. The crash was traced to a planet mod with faulty PQS and unoptimized textures. I will close the issue.

**Comment by LGhassen** [comment]
What was the mod? Just for future reference.

**Comment by Tonas1997** [comment]
Real Expansion. The stability problems are currently being worked on, with some packs (Real Moons) already updated.
