### ISSUE TITLE
Ocean shader errors

### ISSUE THREAD

**Issue by Plakman** [LGhassen/Scatterer#91]
Hello there,

I just tried ckan and i have an issue with the latest shatterer.
Before i was using RTB his version wich worked great.

i tried shatterer alone without spectra and have thesame issue:

https://youtu.be/W48Dicq8kPY

Mods installed:
https://i.imgur.com/1yuX6Zj.jpg

[Player.log](https://github.com/LGhassen/Scatterer/files/4512825/Player.log)

**Comment by LGhassen** [comment]
Closing this since we determined it's just normal whitecaps
