### ISSUE TITLE
Nullreference & "Duplicate instance" error

### ISSUE THREAD

**Issue by Jognt** [LGhassen/Scatterer#94]
I'm seeing this Nullref in player.log on a JNSQ+Scatterer install:

> `[Scatterer][Debug] Celestial Body: 
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Uploading Crash Report
> NullReferenceException: Object reference not set to an instance of an object
>   at scatterer.ScattererCelestialBodiesManager.findCelestialBodies () [0x00100] in <a822e9740b51404b897e7cf406e4df3f>:0 
>   at scatterer.ScattererCelestialBodiesManager.Init () [0x00000] in <a822e9740b51404b897e7cf406e4df3f>:0 
>   at scatterer.Scatterer.Awake () [0x00096] in <a822e9740b51404b897e7cf406e4df3f>:0 
> UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
> UnityEngine.DebugLogHandler:LogException(Exception, Object)
> ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
> UnityEngine.Logger:LogException(Exception, Object)
> UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
> UnityEngine.GameObject:Internal_AddComponentWithType(Type)
> UnityEngine.GameObject:AddComponent(Type)
> AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
> AddonLoader:StartAddons(Startup)
> <LoadObjects>d__89:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> UnityEngine.MonoBehaviour:StartCoroutineManaged2(IEnumerator)
> UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
> <CreateDatabase>d__70:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> UnityEngine.MonoBehaviour:StartCoroutineManaged2(IEnumerator)
> UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
> GameDatabase:StartLoad()
> <LoadSystems>d__11:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> UnityEngine.MonoBehaviour:StartCoroutineManaged2(IEnumerator)
> UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
> LoadingScreen:Start()`

Also seeing the following Error:
`[Scatterer][Error] Destroying duplicate instance, check your install for duplicate mod folders`

I came across these while troubleshooting another problem, so I am not aware of ingame issues related to this. Though I did find that I cannot install Scatterer - Sunflare on CKAN. (checking its box doesn't activate the Apply Changes button)
That may just be a CKAN issue but in case it's a useful hint, there ya go.

[Player-scattererError+inputRIPbug.log](https://github.com/LGhassen/Scatterer/files/4571726/Player-scattererError%2BinputRIPbug.log)

edit: Turned the exception into a quote as it did not properly code format.

Edit 2: This is on 1.8.1 with v0.055 CKAN installed. Just read that the newer version should be 1.8.1 compatible, so will give that one a go.

**Comment by LGhassen** [comment]
[Scatterer][Error] Destroying duplicate instance, check your install for duplicate mod folders

This error is exactly what it says, you have two scatterer installs

**Comment by Jognt** [comment]
> [Scatterer][Error] Destroying duplicate instance, check your install for duplicate mod folders
> 
> This error is exactly what it says, you have two scatterer installs

Guessing it has to do with JNSQ providing a CFG but telling CKAN it depends on the default cfg? There is only one Scatterer folder in gamedata, I confirmed it was gone in between reinstalling Scatterer.

**Comment by LGhassen** [comment]
Not the configs, duplicate scatterer.dll files

**Comment by Jognt** [comment]
I did a search, there is only 1 scatterer.dll in the entire GameData folder. 

Updated to current release, same thing.

**Comment by Jognt** [comment]
Removing the scatterer manually installed folder from the 1.8.1 JNSQ install removed all instances of scatterer in the player.log.

Instanced a fresh 1.9.1 KSP with only module manager & Scatterer 0.0610. Still seeing this in the log
`[Scatterer][Error] Destroying duplicate instance, check your install for duplicate mod folders`

Also have 3 mentions of this one: 
`NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.GetComponentFastPath(UnityEngine.Component,System.Type,intptr)
  at UnityEngine.Component.GetComponent[T] () [0x00020] in <5aeafee3fea24f37abd1315553f2cfa6>:0 
  at DialogCanvasUtil.get_DialogCanvasRect () [0x00027] in <55ba45dc3a43403382024deac8dcd0be>:0 
  at CrewHatchController.get_CrewHatchTooltip () [0x00065] in <55ba45dc3a43403382024deac8dcd0be>:0 
  at CrewHatchController.HideTooltip () [0x00000] in <55ba45dc3a43403382024deac8dcd0be>:0 
  at CrewHatchController.DespawnUIs () [0x00006] in <55ba45dc3a43403382024deac8dcd0be>:0 
  at CrewHatchController.OnDestroy () [0x00058] in <55ba45dc3a43403382024deac8dcd0be>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

I'm reasonably sure there's only the one dll in gamedata, especially with that fresh KSP install.
Log file:
https://cvws.icloud-content.com/B/AdbFHvc1kiydEZdIQ1LHcH8LXo_DAbNnNSWCUfBDeTnOvDcnL2V0mCfc/Player.txt?o=Am9ZbvvpZ_Rt7wbUu34djQDIIQIYEywju5bA91D5pQd1&v=1&x=3&a=CAogQwWzHKjj_o5M8_AjBYCP05azDjd_0bPCF4mMJJ87ZigSHRCj4uSNni4Yw9mbjp4uIgEAUgQLXo_DWgR0mCfc&e=1588630842&k=Ix7biAz37uEuQ9h3hvgdiQ&fl=&r=e55d9d4f-1f4f-48f6-9dc4-05735a0f58e8-1&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=42&s=sarH65Rr_hUqxa_9UVJcanLox3I&cd=i

Sorry for the huge link. At least it works. :/

**Comment by Jognt** [comment]
Let me know if there's anything you need.

**Comment by LGhassen** [comment]
Apart from seeing this error in your logs, are you seeing any malfunction in scatterer?

**Comment by Jognt** [comment]
Yes, but those are problems in the "Where do I even start figuring out why this happens?" category.

In my JNSQ game I get the following two very noticeable problems that I usually resolve with a quicksave/quickload:
- Sometimes* upon returning to Kerbin from another body, high space is missing the scattering effect of the atmosphere for part of kerbin. A bit like when an object is too close to the renderer grid where part of the effect is too close and gets cut off. (it moves around depending on camera angle)
- Sometimes* upon returning to Kerbin from another body the ocean will disappear depending on camera angle. Ocean is visible when looking straight East/West, but disappears entirely leaving only the seabed visible when looking North/South of straight East/West. 

No obvious errors/exceptions when this happens (I have "Show on screen" enabled for those).

*-I don't often return to Kerbin from another SOI, nor do I look at Kerbin much from high space, so it may or may not be related to SOI changes in the first place.

**Comment by Jognt** [comment]
I enabled Verbose Logging. Seems to add additional debug info for Scatterer.

As I have nothing reproducible atm, feel free to close this one. If either of the above happens and the log has some clues, I'll open a new issue.

**Comment by BrettRyland** [comment]
Hi, I know this thread is very old, but I just noticed the "Duplicate instance" error in the KSP.log and figured it was better to necro-post this here instead of opening a new issue.
Anyway, even with a single scatterer dll installed, this error is easy to trigger by going into the SPH or VAB, where the
```csharp
[KSPAddon(KSPAddon.Startup.EveryScene, false)]
```
in Scatterer.cs triggers multiple times for some reason, so `instance == null` is not a reliable way of detecting duplicate dlls.

You can double check this with, for example,
```csharp
[KSPAddon(KSPAddon.Startup.EveryScene, false)]
public class Börk : MonoBehaviour
{
	void Awake()
	{
		Debug.Log($"DEBUG Awake in scene {HighLogic.LoadedScene} BÖRK BÖRK BÖRK!");
	}
}
```
giving the following in the log after loading, then going between the SPH, VAB and flight a few times and then exiting:
```
[LOG 23:19:29.035] DEBUG Awake in scene LOADING BÖRK BÖRK BÖRK!
[LOG 23:20:36.833] DEBUG Awake in scene LOADING BÖRK BÖRK BÖRK!
[LOG 23:20:43.959] DEBUG Awake in scene MAINMENU BÖRK BÖRK BÖRK!
[LOG 23:20:47.726] DEBUG Awake in scene SPACECENTER BÖRK BÖRK BÖRK!
[LOG 23:20:49.155] DEBUG Awake in scene SPACECENTER BÖRK BÖRK BÖRK!
[LOG 23:20:59.832] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:21:01.349] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:21:01.983] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:21:02.207] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:21:09.648] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:21:09.788] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:21:12.994] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:21:13.075] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:21:30.151] DEBUG Awake in scene FLIGHT BÖRK BÖRK BÖRK!
[LOG 23:21:31.819] DEBUG Awake in scene FLIGHT BÖRK BÖRK BÖRK!
[LOG 23:25:49.670] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:25:50.519] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:25:50.727] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:26:04.386] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:26:04.530] DEBUG Awake in scene EDITOR BÖRK BÖRK BÖRK!
[LOG 23:26:16.705] DEBUG Awake in scene SPACECENTER BÖRK BÖRK BÖRK!
[LOG 23:26:26.353] DEBUG Awake in scene MAINMENU BÖRK BÖRK BÖRK!
[LOG 23:26:28.219] DEBUG Awake in scene MAINMENU BÖRK BÖRK BÖRK!
```

**Comment by LGhassen** [comment]
Thanks for the find @BrettRyland
