### ISSUE TITLE
Ocean disappearing on JNSQ

### ISSUE THREAD

**Issue by Jognt** [LGhassen/Scatterer#96]
Like I mentioned in the Duplicate Instance issue I'd get back to you if the ocean disappeared again.
Heya, I'm back.

In a lengthy playsession I once again returned to Kerbin from another SOI, and again the Ocean was missing depending on the direction I looked in.
Sadly the screenshots are pretty dark. Apologies for not changing ambient brightness.

Ocean is there (implied by lack of bright soil): https://1drv.ms/u/s!AjJmMG4x4DXZc7TNoswXpgCl40Q?e=GwdnGn
I look a few degrees to the left/right, Ocean is gone: https://1drv.ms/u/s!AjJmMG4x4DXZcs3zsE-1-Z51pcc?e=vR9acR

Clicking "Rebuild Ocean" in the Scatterer menu brought the ocean back. Toggle wireframe showed no ocean when there visible was not one.
KSP.log: https://1drv.ms/u/s!AjJmMG4x4DXZb03vxws-L5DVTYQ?e=EehfvH
Player.log: https://1drv.ms/u/s!AjJmMG4x4DXZcFTftVmpWF32GYU?e=7G0igh

Do a search for "NoOceanMarker" to jump to the point where it was gone. Jump to "RebuildOceanFixedItMarker" to jump to where the ocean behaved normally again.

What I did notice was a NullrefException when I initially left Kerbin SOI. Which happened at "[EXC 02:30:35.552]". 

I'd appreciate any thoughts you have on this as I'm guessing this is one of those hard to track down issues developers aren't very fond of.

**Comment by Jognt** [comment]
Upon restarting this save there was no Ocean visible at all in the Space Center scene. Did rebuilding the Ocean screw something up? 

Log: https://1drv.ms/u/s!AjJmMG4x4DXZdCWUWf6mdTl7RY4?e=EdK7g9

**Comment by LGhassen** [comment]
Does this still happen?

**Comment by Jognt** [comment]
I haven’t played much since then so I do not know. I’ll close it.
