### ISSUE TITLE
Black ocean

### ISSUE THREAD

**Issue by UnhorsedGoose** [LGhassen/Scatterer#98]
KSP: 1.9.1 Windows 10 64 bit
Problem: Ocean is very black

Mods installed:
A whole lot, here are the visual ones

Environmental Visual Enhancements 1.8.0-2
Scatterer v0.0610
PlanetShine 0.2.6.3
Textures Unlimited 1.5.10.25
Textures Unlimited Recolour Depot v0.3.3

Reproduction steps:

Pretty much just loaded in, all default settings, hopped into a plane (can even see it from the Space Center screen, completely fine from the main menu though) and noticed the whole ocean was a black void 

Log:
https://www.dropbox.com/s/a1h9ejvtaw0pmu6/Player.log?dl=0

**Comment by LGhassen** [comment]
Remove all mods (all not just visual) and try to run with scatterer only, some screenshots would help as well as your Kerbin ocean.cfg

**Comment by UnhorsedGoose** [comment]
Some screenshots from steam: 
https://steamuserimages-a.akamaihd.net/ugc/1011567055129041658/5F400DDC8B1DB64C598732D2BFE427FAEAA10434/

https://steamuserimages-a.akamaihd.net/ugc/1011567055129041939/43A7008A5B88E23FB1F90C7733E9AB7C276572E8/

https://steamuserimages-a.akamaihd.net/ugc/1011567055129042830/4450775EE98C5585F633029A69BBE203C5F392DA/

Kerbin ocean.cfg: https://www.dropbox.com/s/3pop2lv6fwzdq6m/ocean.cfg?dl=0

I'll try to remove my mods in a while and get back to you

**Comment by LGhassen** [comment]
From your screenshots it doesn't look like scattering is working even. So yeah, let's see what happens when you remove all other mods.

**Comment by UnhorsedGoose** [comment]
Backed up & removed all other mods except for scatterer, some custom flags, and Module Manager (I can remove that too if you think that could have an effect) and I'm getting exactly the same result but without clouds, I recorded a short video to demonstrate and took screenshots, I'll link the video upon request, also took screenshots of the Alt + F10 menu, both Atmosphere settings and Ocean settings:

https://steamuserimages-a.akamaihd.net/ugc/1011567142511315842/68403BA6CB76DF8AFB9E85E668BD0DA93A86E260/

https://steamuserimages-a.akamaihd.net/ugc/1011567142511317791/C9C900D616E5D43EFA2AC81C1ED6EA2E4E58AA14/

https://steamuserimages-a.akamaihd.net/ugc/1011567142511316667/3F3464017D5F73D553A8EC3AA485FCB83F4BD61C/

https://steamuserimages-a.akamaihd.net/ugc/1011567142511316932/A90666D519271564AEB3E358DEC0A5CC00651B99/

https://steamuserimages-a.akamaihd.net/ugc/1011567142511317173/B1627E22EF98C0A65B63CFCFAE2167780974344A/

https://steamuserimages-a.akamaihd.net/ugc/1011567142511317450/6E8A758A10273D1974F125603A6E1AA41B71052C/

**Comment by LGhassen** [comment]
Ok, so far I have no idea what's going on.

Rechecking your log above however it seems that the log is only from running in main menu and settings menu, could you provide a more complete log? Run the game in flight for a bit and through a few scene changes before providing the log file.

**Comment by UnhorsedGoose** [comment]
Alright, been flying around for a bit and went back and forth between the hangar and flight and the space center view a bit, hope it helps

https://www.dropbox.com/s/a1h9ejvtaw0pmu6/Player.log?dl=0

**Comment by UnhorsedGoose** [comment]
Alright, due to a lack of response I got bored and felt like trying an earlier version of Scatterer to see what happens, still a non-modded game, only some custom flags, Scatterer version 0.0600 and Module Manager, and guess what, it totally worked fine, ocean is nice and blue with whitecaps and proper refraction and there's much better looking distance fog, only place I found a black ocean was after sunset where there was no light interacting with it.
Screenshots from Steam: 

Space center view  https://steamuserimages-a.akamaihd.net/ugc/1011567362457535986/68613ED589B7525F3A6D5AD56AD56DA1CB065C3F/

https://steamuserimages-a.akamaihd.net/ugc/1011567362457536444/779637FF620C57CF98F610251A04DD7EB301892C/

In-flight view  https://steamuserimages-a.akamaihd.net/ugc/1011567362457536850/4EA9B0BE492D02A6983CD43DA3D2D1A86947C680/

https://steamuserimages-a.akamaihd.net/ugc/1011567362457537138/2B8733704EECACD041B85E84AB47357013BE3A89/

https://steamuserimages-a.akamaihd.net/ugc/1011567362457539871/1BF7514E49297FCDBA13053057145C05D5E40F4F/

https://steamuserimages-a.akamaihd.net/ugc/1011567362457537595/9D8B7080679D1757D3600F25B46CDEA4A5202AEB/

https://steamuserimages-a.akamaihd.net/ugc/1011567362457537881/69D0138B4163897E897635A0D08CD6C098368C1A/

https://steamuserimages-a.akamaihd.net/ugc/1011567362457538269/977D85C8DFA14EB94936067DBD9923C1F3F2C9C9/

https://steamuserimages-a.akamaihd.net/ugc/1011567362457538529/61D0089BDF7F5A7C750FD340DBB21239361A1836/

Log file: https://www.dropbox.com/s/a1h9ejvtaw0pmu6/Player.log?dl=0

**Comment by UnhorsedGoose** [comment]
Well alright, it seems to have fixed itself! I went back to my original Scatterer installation, version 0.0610, and went back in, no mods again, and it's totally fine. Whatever happened has been reverted or fixed or something so I'm all good now, thanks for the help, gonna test it with my mods reinstalled and check back in later

**Comment by UnhorsedGoose** [comment]
Yeah, totally working fine, only problem is the clouds look extra funky in the main menu but they're fine in game so whatever, thanks for the help
