### ISSUE TITLE
Ice World at menu, Black and White globe at tracking

### ISSUE THREAD

**Issue by theicon32** [LGhassen/Scatterer#99]
Planet looks like an Ice World at menu, a solid black and white globe on the tracking screen. Using 1.9.1, new at modding so I don't know if I messed something up.

edit: Ok, I had been linked an older version and didn't realize it. Black ocean problem is gone. I think the ice world look is intentional, a bit too much for me but I'm just getting started with all of this stuff. Leaving this comment in case someone else is as dumb as me and has the same issue with the black ocean.

**Comment by theicon32** [comment]
Oh right, using KSP 1.9.1 update

**Comment by LGhassen** [comment]
In this case I'm closing this. I don't know about your "ice world" issue, as a rule for ambiguous issues like this where you don't know if it's intentional or not post screenshots.
